### ISSUE TITLE
upload new file - same filename: should I edit manifest

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/community#111]
I have just uploaded a new version of some plugs with small bugfixes.
VERSION is the same
filenamame and download URL are the same
I noticed that the SHA256 code remains the same is filename doesn't change

Should I edit the Manifest or should I simply replace the files on my server and that's it?

**Comment by martin-lueders** [comment]
Are you sure about the SHA256 thing? You might have fallen trap of the same mistake I did with he VirusTotal page, which keeps a cache of your files.

I found that they usually change. Isn't that the whole idea of that key, that it differs for each file?

I do update my manifest even if the filenames remain the same.
