### ISSUE TITLE
compressing ZIP file on OSX system: removing unneeded, unwanted folders

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/community#114]
this is not an ISSUE but more an ADVICE:

if you do development on OSX and at the end you compress the package for your plugin using the 
right mouse button : 

  **compress yourpluginpackage**

you can remove the unneeded items doing 2 commands on the the terminal:

1) TO REMOVE the **__MACOSX** dir do:

    **zip -d yourpluginpackage.zip __MACOSX/\***

2) TO DELETE ALL the **.DS_Store** files do:

    **zip -d yourpluginpackage.zip \*/.DS_Store**

@jeremywen, is not so important but, maybe you want to add to you FAQ

**Comment by jeremywen** [comment]
Done. https://github.com/jeremywen/JW-Modules/wiki/Dev-FAQ-for-VCV-Rack

**Comment by jeremywen** [comment]
I added this to my `.profile` 

```
function cleanmaczip(){
	zip -d "$1" '*/.DS_Store' && zip -d "$1" '__MAC*'
}
```

**Comment by AndrewBelt** [comment]
Why are you using the ZIP compressor in MacOS? Why not just run `make dist`?

**Comment by jeremywen** [comment]
I have to go to each OS and make builds copy them to dropbox and then copy them into the right folder then make the zip

**Comment by AndrewBelt** [comment]
Ah, we need a zipmerge.sh utility.

**Comment by jeremywen** [comment]
And with all this manual moving of files and switching computers right clicking to compress is easy

**Comment by AndrewBelt** [comment]
Maybe I don't understand what your workflow is. You have to use all three computers anyway to make the build, so why is your method easier than producing three ZIPs on each computer, collecting them on one computer, and then uploading them to GitHub?

**Comment by jeremywen** [comment]
well then there is only one nice zip url in the manifest and only one zip uploaded to github - less chance for error

**Comment by AndrewBelt** [comment]
Okay, I see, you're using the old combined ZIP method. Using that is still fine if you wish, since I don't plan to remove support for it.

In that case, I propose someone writes a generic `zipmerge.sh` script to take the first N-1 arguments, unzip them, and then recombine them into a ZIP with last argument as the filename. Example:

    ./zipmerge.sh MyModule-0.5.0-*.zip MyModule-0.5.0.zip

**Comment by jeremywen** [comment]
ok i will make that script

**Comment by AndrewBelt** [comment]
Ah, wait, I realized how I could make it easily. I can do it if you want.

**Comment by jeremywen** [comment]
do it 👍

**Comment by AndrewBelt** [comment]
Here you go. I reversed the arguments from my initial post, so its usage is

```bash
./zipmerge.sh MyPlugin-0.5.0.zip MyPlugin-0.5.0-*.zip
```

https://gist.github.com/AndrewBelt/2c8fbe4ca24231a147e348391fa747d6

**Comment by jeremywen** [comment]
ooh adding this to the dev faq - thanks!

**Comment by AndrewBelt** [comment]
Closing since everything here is obsolete. It is no longer recommended to merge ZIP packages, and you shouldn't be running your own ZIP commands, just use `make dist` and remove the `.DS_Store` files prior to running if they're present.
