### ISSUE TITLE
1/10/18 Plugins That Cause the Red Dot

### ISSUE THREAD

**Issue by matthewfriedrichs** [VCVRack/community#173]
Bidoo, Bogaudio, dBiz, and Sonus Modular are all causing the Red Dot issue as of 1/10/18 on Windows. Can any one else confirm this?

**Comment by AndrewBelt** [comment]
For each plugin,
1) Does it load or not?
2) Does it have versions compiled in? If so, does it match the JSON?

**Comment by matthewfriedrichs** [comment]
Bidoo: Loads, versions do not match. DL = 0.5.15, .json = 0.5.16
Bogaudio: Loads, versions do not match, DL = 0.5.2, .json = 0.5.3
dBiz: Does not load, can not check version
Sonus Modular: Loads, versions do not match, DL = 0.5.0, .json = 0.5.1

**Comment by AndrewBelt** [comment]
Cool! That information helps a ton actually. I should ask that in the future.

**Comment by matthewfriedrichs** [comment]
Glad that I could help. I will also just post that information from now on. :)

**Comment by Phal-anx** [comment]
Matthew didnt delete the plugins before updating. Just checked myself on windows (all plugins deleted and fresh install) no red dots for 3 of them.

Bidoo latest version to download is 0.5.16 (the same as in the json)
Bogaudio latest version to download is 0.5.3 (the same as in the json)
dBiz doesnt load - I can confirm (possible wrong SHA256)
Sonus Modular latest version to download 0.5.1 (the same as in the json)

**Comment by AndrewBelt** [comment]
Okay, hold on. I just confirmed myself that Sonus Modular is compiled with the version 0.5.1. How are you getting incorrect information?

**Comment by AndrewBelt** [comment]
Why is it not overwriting the old plugin.dll with the newly downloaded plugin.dll?? @matthewfriedrichs Can you investigate? `log.txt` etc

**Comment by Phal-anx** [comment]
@AndrewBelt  this is the in my log file after trying to update an old plugin of mine to the latest version in the plugin manager... it gets downloaded but not unzipped and replaced

[info] Rack v0.5.1
[info] Current working directory: C:\Program Files\VCV\Rack
[info] Global directory: ./
[info] Local directory: C:\Users\Phal\Documents/Rack/
[info] Loading plugins from ./plugins
[info] Loaded plugin ./plugins/Fundamental/plugin.dll
[info] Loading plugins from C:\Users\Phal\Documents/Rack/plugins
[info] Loaded plugin C:\Users\Phal\Documents/Rack/plugins/Bidoo/plugin.dll
[info] Loaded plugin C:\Users\Phal\Documents/Rack/plugins/Bogaudio/plugin.dll
[info] Loaded plugin C:\Users\Phal\Documents/Rack/plugins/MSM/plugin.dll
[info] Loaded plugin C:\Users\Phal\Documents/Rack/plugins/sonusmodular/plugin.dll
[info] Loaded font ./res/DejaVuSans.ttf
[info] Loading patch C:\Users\Phal\Documents/Rack/autosave.vcv
[info] Loaded SVG ./res/ComponentLibrary/PJ3410.svg
[info] Requesting https://api.vcvrack.com/version
[debug] Opening audio stream 1
[debug] Starting audio stream 1
[info] Loaded SVG ./plugins/Fundamental/res/Scope.svg
[info] Loaded SVG ./res/ComponentLibrary/ScrewSilver.svg
[info] Loaded font ./plugins/Fundamental/res/fonts/Sudo.ttf
[info] Loaded SVG ./res/ComponentLibrary/RoundBlack.svg
[info] Loaded SVG ./res/ComponentLibrary/CKD6_0.svg
[info] Loaded SVG ./res/ComponentLibrary/CKD6_1.svg
[info] Loaded SVG ./res/ComponentLibrary/PJ301M.svg
[info] Loading settings C:\Users\Phal\Documents/Rack/settings.json
[info] Requesting https://api.vcvrack.com/plugins?version=0.5.1&token=N7n0Zrzi%2FIh3WBGy9fNe
[info] Requesting https://api.vcvrack.com/community/plugins
[info] Requesting https://api.vcvrack.com/plugins?version=0.5.1&token=N7n0Zrzi%2FIh3WBGy9fNe
[info] Requesting https://api.vcvrack.com/community/plugins
[info] Syncing plugin MSM
[info] Downloading https://github.com/Phal-anx/MSM/releases/download/0.5.5/MSM-0.5.5-win.zip
[info] Saving settings C:\Users\Phal\Documents/Rack/settings.json
[info] Saving patch C:\Users\Phal\Documents/Rack/autosave.vcv
[debug] Aborting audio stream 1
[debug] Closing audio stream 1

**Comment by AndrewBelt** [comment]
@Phal-anx Don't post your tokens. Printing GET URLs has been removed in `master`, but for the time being, this information needs to be private.

**Comment by Phal-anx** [comment]
ahhh sry!!

**Comment by matthewfriedrichs** [comment]
[warning] Failed to load library C:\Users\Matthew\Documents/Rack/plugins/dBiz.zip/plugin.dll: 126
The only issue in the log.

After deleting the folders and .zip files that were downloaded for the Bidoo, Bogaudio, and Sonus Modular, they did install correctly. Sorry about that. I will always be sure to delete both in the future before updating from Rack.

**Comment by Phal-anx** [comment]
but it should actually override them or am I mistaken?

**Comment by AndrewBelt** [comment]
Yes, it should. I haven't seen this problem before.

**Comment by Phal-anx** [comment]
it never did it on my end... (windows 7)

**Comment by matthewfriedrichs** [comment]
I don't know why, but only some files do not get overwritten. The others update just fine. I could not find anything off in log.txt. The ones that loaded still reported loading correctly.

**Comment by AndrewBelt** [comment]
Okay, let's put this to rest for now. I've disabled the plugin manager until further notice.

**Comment by Phal-anx** [comment]
okay,

**Comment by matthewfriedrichs** [comment]
Understood.

**Comment by Phal-anx** [comment]
maybe one last thing.. add a message on the plugin manager that it got disabled until further notice to avoid 100+ emails why it doesnt show download links (+Free buttons)

**Comment by mdemanett** [comment]
Windows it will lock loaded .dlls (in a running process), which prevents deletion, or at least casual deletion.

**Comment by AndrewBelt** [comment]
@Phal-anx Thanks, done.

@mdemanett Ah, thanks, that's it! My UNIX mind did not think of that.

**Comment by matthewfriedrichs** [comment]
That makes sense. I did not think the .dll would be in use if none of the modules in the .dll were not loaded into the current patch.
