### ISSUE TITLE
Downloads block in manifest should take into account processor architecture and word length

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/community#193]
A future where people want to run VCVRack on Windows 10 ARM devices and Raspberry Pi devices, isn't too far off. We should we using better platform descriptors for our prebuilt plugins. I propose:

As a first go, I propose slug name be:
```bash
`uname -s`-`uname -m`
```

eg  `Darwin-x86_64`

**Comment by Phal-anx** [comment]
people tried to run Rack on Rasperry Pi and failed.. cpu isnt fast enough.. there is even an issue 
https://github.com/VCVRack/Rack/issues/534

**Comment by AndrewBelt** [comment]
The arch names need to match the Rack distribution ARCH identifiers: `win`, `mac`, `lin` so far. If ARM is added, it'll probably be called `arm64` and `arm32`.
