### ISSUE TITLE
Plugins where root folder does not match slug

### ISSUE THREAD

**Issue by cschol** [VCVRack/community#200]
On Windows:

- [X] CastleRocktronics (folder: `CastleRocktronics-0.5.0`)
- [x] s-ol (folder: `solmods`)
- [ ] SonusModular (folder: `sonusmodular`)
- [x] StellareModular (folder: `Stellare-Modular`)
- [x] Valley Free (folder: `ValleyRackFree`)
- [ ] JE (folder: `VCVRack-plugin-JE-0.5.0-Win`)
- [ ] IO-Simple (folder: `VCVRack-Simple`)
- [X] Vult (folder: `VultModules`)

**Comment by AndrewBelt** [comment]
Thanks, will come in handy.

Just brainstorming, perhaps once a centralized build system #6 is configured, it should be required to have source built by them for the open-source plugins. This would reduce malware, since a particular hash could be pulled from the GitHub repo.

**Comment by cschol** [comment]
Yeah, you will need to keep the build system up with dependencies for all plugins. There is currently one (`PulsumQuadratum-rtlsdr`), which I can't get to build on Windows from source. Still trying to figure out if it is a source issue or just a missing dependency. For another one, `dBiz`, the checksum is failing also for Windows ([issue](https://github.com/dBiz/dBiz/issues/21).

**Comment by cschol** [comment]
I am not sure what the CI build does currently, but it could do some sanity check on each plugin to enforce some more rules, e.g check SHA matches on binaries, verify root dir matches slug. This should work for all platforms.

**Comment by KieranPringle** [comment]
PR opened here: https://github.com/VCVRack/community/pull/256

**Comment by AndrewBelt** [comment]
@cschol Thanks! Do you want to be on the review team?

**Comment by cschol** [comment]
@AndrewBelt Sure. Wherever you need help.

**Comment by WIZARDISHUNGRY** [comment]
@cschol PulsumQuadratum-rtlsdr not building is because the dependencies aren't packaged as submodules yet - WIZARDISHUNGRY/vcvrack-rtlsdr#31

**Comment by david-c14** [comment]
Does it cause a problem if the root folder doesn't match the slug.

Because I've only just started, I can easily move my repository if you prefer

**Comment by david-c14** [comment]
ok, thanks. Sorry for the noise
