### ISSUE TITLE
Popularity

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/community#226]
clickthrough stats - any notice of popularity, or lack thereof, would be awesome.

**Comment by AndrewBelt** [comment]
It's planned, I just need to make sure I can give out the information I'm giving out. At the mimimum, there will be rankings with popularity.

And it will be after the Plugin Manager opens for third-party plugins again, since right now it would only be able to list the commercial and VCV open-source plugins.

**Comment by JerrySievert** [comment]
thanks - as an aside, I don't need to know about the numbers for other developers, mostly just wondering if the niche I'm hitting is successful (though it would be good to compare with friends like @almostEric, bet beer or the like)

**Comment by sanderbaan** [comment]
Would it be possible to get statistics of how many times a plugin has been downloaded?

**Comment by AndrewBelt** [comment]
From the Linux/Windows/Mac icons? No. GitHub might know if you're serving the files from Releases.

After Rack 0.6 with third-party open-source plugins added to the plugin manager, most people (except compile-from-source nerds) click the add buttons on the plugin manager page, so I'd be able to just run a SQL query to get the numbers. If someone asks me and I'm not busy, I'd be willing to tell the developer of the number.

I'm fine with making "popularity rankings" public, so users should be able to sort by "most popular" on the plugin page.

**Comment by sanderbaan** [comment]
OK the info from the Add button would be good also, with github I am afraid it only shows the statistics of the last month, I did not find a way yet to change the date range there...

**Comment by AndrewBelt** [comment]
https://api.vcvrack.com/community/manifests now injects a `"rank"` property into each manifest, and https://vcvrack.com/plugins.html is now sorted by rank.

**Comment by AndrewBelt** [comment]
Reverting, will not re-add in the future. This is detrimental to the community.

**Comment by almostEric** [comment]
While I think sorting the plug-ins by popularity (especially be default) was not a good idea, the original request was for developers to have some insight on the download numbers so they know if their plug-ins are resonating with the community.

**Comment by AndrewBelt** [comment]
In that case, data privacy laws could be a problem.

**Comment by almostEric** [comment]
How so? It's not like "who" is downloading is being revealed? It is just a number? That is like saying Youtube can't show many times a video has been viewed, which last I checked, I still can

**Comment by AndrewBelt** [comment]
That's how data laws work these days. It was an oversight and was quickly corrected.

**Comment by almostEric** [comment]
Not quite sure how? The company I own deals with GPDR quite well.

**Comment by AndrewBelt** [comment]
Locking this down since further discussion will need a legal review, not community involvement, sorry.
