### ISSUE TITLE
Checksum verification fails: dBiz v0.5.2

### ISSUE THREAD

**Issue by cschol** [VCVRack/community#253]
@dBiz Can you please check into the following [issue](https://github.com/dBiz/dBiz/issues/21) I filed a while ago. The checksum of the `dBiz` plugin still fails on Windows.

@AndrewBelt @Phal-anx Maybe we should remove that particular version of the Windows build from the manifest until it is fixed? Linux and MacOS are checking out fine.

**Comment by AndrewBelt** [comment]
Removed in 39c3807
