### ISSUE TITLE
av500 plugin uses -fshort-enums and crashes Rack

### ISSUE THREAD

**Issue by cschol** [VCVRack/community#255]
`av500` uses `-fshort-enums` in the Makefile, which crashes Rack when using the search field for modules.

Issue reported [here](https://github.com/av500/vcvrackplugins_av500/issues/12) around 20 days ago.

Recommend removing from manifest until Makefile is updated.

**Comment by WIZARDISHUNGRY** [comment]
If we were going to put a general sort of linter in the community repo, this would be a good first step.

**Comment by AndrewBelt** [comment]
I would remove just the av500 "downloads" property, but since it already doesn't exist, there is nothing to do here.
