### ISSUE TITLE
Feature Req: Release date

### ISSUE THREAD

**Issue by Skeyelab** [VCVRack/community#266]
Is it possible to get a column added to the table that represents release date?

**Comment by WIZARDISHUNGRY** [comment]
Might be worth putting the release date of the latest Rack on the vcvrack.com homepage too.

**Comment by AndrewBelt** [comment]
The only way this would work is if the Build team in #248 (using scripts that automatically modify the JSON) adds a timestamp (UNIX time) to each build in the JSON. The manifest format will undergo large changes when the teams begin working, so we can design this in.

**Comment by Skeyelab** [comment]
Thanks.  This would be helpful to me, as I went thru and downloaded a ton of plugins, but would like to see whats new/updated w/o having to crosscheck.

**Comment by AndrewBelt** [comment]
Because of the switch to a centralized build system, the Build Team is now able to add a certain timestamps to the manifest upon certain events. I think we only need one, `buildTimestamp` which is set to "now" when `latestVersion` is updated.

**Comment by AndrewBelt** [comment]
Closing, since "buildTimestamp" has been around for a while now.
