### ISSUE TITLE
error "could not find plugin"

### ISSUE THREAD

**Issue by nerdbeere23** [VCVRack/community#273]
Hi.
I'm trying to open some patches and getting the message "could not find plugin ...".
"mscHACK or "ML_Modules" for instance, but these are installed and i'm able to see and open the modules.

any idea what could be wrong.
I'm on Windows 7_64

Thanks
Rico

**Comment by AndrewBelt** [comment]
Looks like plugin developers are being careless with the capitalization of their slugs. Mind complaining on those plugins' GitHub issues?
