### ISSUE TITLE
Future Request favorite list for plugins 

### ISSUE THREAD

**Issue by Klangspagat** [VCVRack/community#296]
Could it be possible to add an favorite list for plugins instead of searching everytime thru the whole list to find the right plugin?
Greetings

**Comment by AndrewBelt** [comment]
Rack feature requests go in this repo. https://github.com/VCVRack/Rack
Duplicate of https://github.com/VCVRack/Rack/issues/452

**Comment by phdsg** [comment]
wow your fast @AndrewBelt 
https://github.com/VCVRack/Rack/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+favorite
