### ISSUE TITLE
'text' is not a member of 'rack::MenuEntry' error

### ISSUE THREAD

**Issue by cschol** [VCVRack/community#299]
After the latest pull this morning all publicly available `v0.6` versions of plugins compile fine, except `hetrickcv` (@mhetrick).

```
src/BlankPanel.cpp: In member function 'virtual rack::Menu* BlankPanelWidget::createContextMenu()':
src/BlankPanel.cpp:174:53: error: 'text' is not a member of 'rack::MenuEntry'
     menu->addChild(construct<MenuLabel>(&MenuEntry::text, "Panel Art"));
```

[BlankPanel.cpp](https://github.com/mhetrick/hetrickcv/blob/master/src/BlankPanel.cpp) source for reference.

@AndrewBelt Is this an update to the API and/or should this code be implemented some other way?

**Comment by AndrewBelt** [comment]
Oh yes, `MenuEntry` should be replaced with `MenuLabel`

**Comment by cschol** [comment]
[PR](https://github.com/mhetrick/hetrickcv/pull/13) to fix `hetrickcv`.

**Comment by cschol** [comment]
Some more instances of open Repair Team PRs needed updates for this. I am going through and amend those.

**Comment by phdsg** [comment]
i think the ones i requested still work. will go through again tho.

**Comment by cschol** [comment]
PR was merged. I am closing this and we will be on the lookout for more instances as they come up.
