### ISSUE TITLE
Tags in plugin manager on VCV website?

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/community#313]
With the increasing number of manufacturers in the plugin list at vcvrack.com/plugins, and the fact that we can loose track of who does what kind of module, would it be possible/reasonable to add tags to the VCVRack plugin manager? If we are searching for sequencers in the plugin manager, for example, TheXOR would show up, along with all manufacturer that have sequencers in their packages. It would be a great help when searching for a certain type of module to install, however, it comes at the expense of having to add tags to the plugin manifest files and the developers maintaining such tags. Any thoughts?

**Comment by cschol** [comment]
I just had the same thought looking for a clock divider on a new machine that only has a limited set of modules installed.

**Comment by AndrewBelt** [comment]
This is a subset of https://github.com/VCVRack/community/issues/243
