### ISSUE TITLE
Adding link to issues/support page

### ISSUE THREAD

**Issue by modlfo** [VCVRack/community#341]
For all the open source plugins hosted on github it's clear that the github issues page is the channel to contact for support. The issues page can be accessed through the "Source" link.

However since I don't have the sources in my public github it would be good having some way of redirecting the users wanting to contact me to my github issues page. I can add a link in my Manual page and contact email. But I wonder if the plugin manager should provide support/contact/issues information so the users can report any problems without jumping to find the page.

I raise this because one user (of my commercial plugins) told me he had some problem to find how to report an issue with my plugins.

**Comment by AndrewBelt** [comment]
It would be nice to have a contact email address, but there's not really space for it, and emails links are bad UX. I think most people would expect it to be on the "homepage" URL, so if you want contact info to be clear, I'd suggest putting a Contact link on the header of your website.

**Comment by modlfo** [comment]
If the comercial plugins are gonna have some piece of web page in the VCV site with description etc. it seems like a good place to put the support information.

I'll close this one for now.
