### ISSUE TITLE
RACK_DIR

### ISSUE THREAD

**Issue by gbrandt1** [VCVRack/community#350]
what's the idea with setting RACK_DIR? we do it by hand / in .bashrc?

**Comment by AndrewBelt** [comment]
See https://github.com/VCVRack/Rack/issues/258#issuecomment-365346155. Also subscribe to that if you aren't already.
`RACK_DIR` is now required, just in time for Rack 0.6.

**Comment by gbrandt1** [comment]
i have that, as recommended
RACK_DIR ?= ../..
it isn't picked up since today

**Comment by AndrewBelt** [comment]
Could you post the error message? Also mind creating an issue in the Rack repo?

**Comment by gbrandt1** [comment]
sorry for the noise, i figured out what happened: a script i'm using to keep things up to date had accidentally checked out the master (which is still on 0.5) overwriting the 0.6 branch
