### ISSUE TITLE
VultModulesFree

### ISSUE THREAD

**Issue by modlfo** [VCVRack/community#377]
I have my binaries ready but I found that I didn't add the last zero to the version number. I have v0.6 instead of v0.6.0. I don't know if this is an issue.

https://github.com/modlfo/VultModules/releases/tag/v0.6

In any case, I'll update my binaries in a couple of hours with the full version number and I'll wait for instructions to make them available.

**Comment by modlfo** [comment]
I have added new binaries with the full version: 0.6.0.

**Comment by modlfo** [comment]
Here are the necessary updates for the manifest file of the VultModulesFree

```
  "name": "Vult Modules (Free Version)",
  "author": "Leonardo Laguna Ruiz",
  "authorEmail": "modlfo@gmail.com",
  "authorUrl": "http://modlfo.github.io",
  "pluginUrl": "https://modlfo.github.io/VultModules",
  "manualUrl": "https://modlfo.github.io/VultModules",
  "latestVersion": "0.6.1",
  "license": "proprietary"
}

```

**Comment by modlfo** [comment]
Hi Andrew. Can you add the "manual" link to the VultModules Free as well. The link is the same as for the other Vult modules 
```
"manualUrl": "https://modlfo.github.io/VultModules"
```

**Comment by AndrewBelt** [comment]
Thanks, updated.
