### ISSUE TITLE
Plugin links gone?

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/community#378]
well, maybe I am just idiot today or I missed something....
but how do i link my plugins for download if they are not on a repo but on my server?
I had no problem with the direct link approach we had before, but can't understand how to create the manifest now...

**Comment by AndrewBelt** [comment]
Yes, they are gone. All plugins distributed through the Plugin Manager now must be served from api.vcvrack.com. You and about 10 other developers are special since you have plugins which are neither open source nor on the VCV Store. I'll announce a program later to handle this cast, so stay tuned.

**Comment by antoniograzioli** [comment]
well I dind't see it coming or announced....

**Comment by AndrewBelt** [comment]
I've added documentation here. https://github.com/VCVRack/community#for-plugin-developers-addingupdating-your-plugin
Will announce when I have time.

**Comment by AndrewBelt** [comment]
Announced at https://www.facebook.com/groups/vcvrack/permalink/168344337159052/

**Comment by antoniograzioli** [comment]
yeah but when was this decision taken?
I updated all my community files just to discover they are now gone...

**Comment by AndrewBelt** [comment]
A few days ago.
