### ISSUE TITLE
Autodafe, Autodafe-REDs, Autodafe-REDsFREE, Autodafe-DrumKit

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/community#380]
please update

**Comment by phdsg** [comment]
i'm a bit puzzled here...
the manifests for the open source plugins point to defunct repos.
@antoniograzioli any plans to fix this or are you distributing exclusively on your website?

**Comment by AndrewBelt** [comment]
What's the current version of each of these? I believe you have 0.6.* released, but they say 0.5.* in the manifests.

**Comment by antoniograzioli** [comment]
it's 0.6 I had edited the manifest file but it was never updated...

**Comment by AndrewBelt** [comment]
Thanks. Because your PRs were correct, I've merged them, but we no longer expect PRs from developers. They are handled by the Library Team #352, so if you have any changes, just post them here (in English rather than JSON) and someone will handle it.
