### ISSUE TITLE
Valley

### ISSUE THREAD

**Issue by ValleyAudio** [VCVRack/community#385]
Valley master branch has been updated to 0.6.0

name: Valley
author: ValleyAudio
license: BSD-3-Clause, GPL-3.0-only
contactEmail: valley.audio.soft@gmail.com
pluginUrl: https://github.com/ValleyAudio/ValleyRackFree
authorUrl: https://github.com/ValleyAudio/ValleyRackFree
manualUrl: https://github.com/ValleyAudio/ValleyRackFree
sourceUrl: https://github.com/ValleyAudio/ValleyRackFree
donateUrl: https://www.paypal.me/valleyvcv
latestVersion: 0.6.0

**Comment by AndrewBelt** [comment]
Duplicate of #407
