### ISSUE TITLE
Bidoo fails to build againsthe SDK

### ISSUE THREAD

**Issue by ZuluEchoRomeOscar** [VCVRack/community#395]
Bidoo fails to build because of the absence of `/dev/lib/libcurl.a` in the SDK.

Raised with the dev too: https://github.com/sebastien-bouffier/Bidoo/issues/68#issuecomment-377168019

**Comment by AndrewBelt** [comment]
Yes, he's assuming that the file is present at `$(RACK_DIR)/dep/lib/libcurl.a` (or something) rather than building his own static libcurl, so Bidoo needs to fix this before being added to the community.

**Comment by ZuluEchoRomeOscar** [comment]
Thanks.

**Comment by sebastien-bouffier** [comment]
ok didn't knew that I had to do that ....

**Comment by AndrewBelt** [comment]
Rack itself doesn't even statically link libcurl. Maybe it will in the future if I can figure out how to build curl and openssl statically on all three platforms.

**Comment by sebastien-bouffier** [comment]
yes dep building can lead to headaches ... (mpg123 has been a nightmare for me and I think I could do better because the make configuration is not optimized regarding my usage) ... thanks for the information I will do my own dep for libcurl

**Comment by AndrewBelt** [comment]
Dynamic linking from one library to a library loaded by the application works on Mac and Linux, but not Windows, so you have to statically link the library, or Rack itself has to statically link it. But don't do that for glfw. Why do you need to call a glfw function?

Your osdialog usage looks correct.
