### ISSUE TITLE
mscHack

### ISSUE THREAD

**Issue by mschack** [VCVRack/community#398]
0.6.0
https://github.com/mschack/VCV-Rack-Plugins

**Comment by phdsg** [comment]
Updated information

**Comment by mschack** [comment]
Note I have made an update in the meantime, this is now v0.6.1.  if you require me to add a new issue for this, then I will.
Thanks

**Comment by phdsg** [comment]
damn. i just filed PR for the addition of your plugin. but i was still at 0.6.0.

reuse this issue for all further updates.

**Comment by phdsg** [comment]
other than that, your `Makefile` needs to reflect the correct version.

**Comment by mschack** [comment]
aw sorry... will fix the makefile

**Comment by phdsg** [comment]
in your case i guess it doesn't matter too much, since the plugin is a new addition, but future updates will only succeed if you increase the version.

**Comment by mschack** [comment]
ok, I updated the version anyway... thank you.

**Comment by phdsg** [comment]
added in #412

**Comment by AndrewBelt** [comment]
Going to have to disable automatic builds for this repo temporarily. The repo size is 150MB, which is huge and is killing the build times.
@phdsg I believe there's a way to enable shallow submodule checkouts?
Either way, @mschack should find the huge commits and remove them. https://blog.ostermiller.org/git-remove-from-history

**Comment by phdsg** [comment]
@AndrewBelt ok. i'll take a look.

**Comment by phdsg** [comment]
ok, cloning this repo with `depth=1` significantly decreases the volume (to ~5mb).

**Comment by mschack** [comment]
I used to save a zip of the build folder in my commits, do you want me to remove them?

**Comment by cschol** [comment]
> I used to save a zip of the build folder in my commits, do you want me to remove them?

Please. That is a very bad practice, especially with git, where you always download ALL of the history (unless you do a shallow clone). Thank you!

**Comment by AndrewBelt** [comment]
```
error: Server does not allow request for unadvertised object 2057b6e92deb128bf87c1c71cae8d98cc7625184
Fetched in submodule path 'repos/mscHack', but it did not contain 2057b6e92deb128bf87c1c71cae8d98cc7625184. Direct fetching of that commit failed.
```

**Comment by mschack** [comment]
Did I screw something up when removing the build zips?

**Comment by phdsg** [comment]
could be my screw-up too. not sure if i added the repo before or after your cleanup.
but i also can't reproduce the error. submodule updates fine here.

**Comment by phdsg** [comment]
@AndrewBelt how to fix this? just update the repo-pointer?

**Comment by phdsg** [comment]
@mschack the repo is still around 150 megs.
i tested the guide andrew linked on a fork of your repo up to step 6.
after i removed `mscHack.zip` and `build/src/*.o` from the history, the forked repo's size is now around 5megs.

**Comment by AndrewBelt** [comment]
The `./configure` step for libsamplerate with mingw cross-compile from Linux doesn't work, so I'm removing this from `repos/`

**Comment by mschack** [comment]
Is this something I did?

**Comment by AndrewBelt** [comment]
Same reason as https://github.com/VCVRack/community/issues/418#issuecomment-382461744

**Comment by mschack** [comment]
Well I don't think I actually need the libsamplerate stuff, if I remove it would that solve the issue?

**Comment by phdsg** [comment]
yes, if you don't use it anymore, remove it.

**Comment by mschack** [comment]
ok, thanks.

**Comment by mschack** [comment]
ok updated with a new makefile.

**Comment by phdsg** [comment]
all fine now.
Updated build.

**Comment by mschack** [comment]
Thanks all!

**Comment by mschack** [comment]
Updated to v0.6.2

**Comment by AndrewBelt** [comment]
Updated build
