### ISSUE TITLE
Why do some plugins show up in plugin manager for download, and some don't?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/community#404]
I notice that now most of the free plugins show up with a "free" icon on the right that lets you add them to your account and be automatically managed in the app. Hooray.

Some of them, including ours, do not show up there, but do show up with 0.6.0 download links.

Is this just a time lag?

thanks in advance! (and really great job so far with the 0.6 rollout)

**Comment by phdsg** [comment]
my guess:
the webpage for the plugin manager gets automatically updated from the manifests.
the add/remove button appears as soon as andrew manually adds updated modules for distribution...

**Comment by squinkylabs** [comment]
@phdsg : I'll bet you are right!

**Comment by AndrewBelt** [comment]
Manifests with `"status": "available"` get an add button.
The Build Team sets that flag, and the ball gets rolling when the Review Team #354 starts work on a plugin.

**Comment by squinkylabs** [comment]
Nice! tx.

**Comment by AndrewBelt** [comment]
Updated https://github.com/VCVRack/community#for-plugin-developers with the complete instructions for plugin developers to add/update their plugins.

**Comment by AndrewBelt** [comment]
I'll close this now.
