### ISSUE TITLE
LindenbergResearch

### ISSUE THREAD

**Issue by lindenbergresearch** [VCVRack/community#435]
Version : 0.6.0
Hash: 1bb8a4d

I hope this is ok, if you need more info please tell me.
All links and versions can be found at my git:

https://github.com/lindenbergresearch/LRTRack

Thanks for updating.

**Comment by phdsg** [comment]
currently there's already a build using version 0.6.0.
in order to trigger a new build in the next build cycle you have to bump the version.

**Comment by mdemanett** [comment]
@AndrewBelt So to get this queued to build: 1) review it, 2) fix the submodule pointer, 3) change manifest to have repoVersion 0.6.0, and 4) delete currentVersion?  The last step because then repo and currentVersion will be different, and that's the flag to build?

**Comment by AndrewBelt** [comment]
Correct, and remove `"status": "available"`

**Comment by AndrewBelt** [comment]
Update build
