### ISSUE TITLE
ErraticInstruments

### ISSUE THREAD

**Issue by bafonso** [VCVRack/community#443]
name: ErraticInstruments
author: Bruno Afonso
license: BSD-3-Clause
pluginUrl: https://github.com/bafonso/Erratic
authorUrl: https://brunoafonso.org
manualUrl: https://github.com/bafonso/Erratic/blob/master/README.md
sourceUrl: https://github.com/bafonso/Erratic
donateUrl: https://www.paypal.me/ErraticModules
latestVersion: 0.6.1

**Comment by AndrewBelt** [comment]
The lines
```
include ../../arch.mk
ifeq ($(ARCH), win)
LDFLAGS += -L"../../dep/lib" -lrtmidi
endif
```
in Makefile reference the Rack directory with RACK_DIR so my scripts can't build them.

**Comment by AndrewBelt** [comment]
Something like

```Makefile
RACK_DIR ?= ../..
include $(RACK_DIR)/arch.mk
ifeq ($(ARCH), win)
LDFLAGS += -L"$(RACK_DIR)/dep/lib" -lrtmidi
endif
```

**Comment by dizzisound** [comment]
@bafonso Sorry Bruno, I forgot the quotes, so as per Andrew asks, the line:
`LDFLAGS += -L$(RACK_DIR)/dep/lib -lrtmidi`
should be:
`LDFLAGS += -L"$(RACK_DIR)/dep/lib" -lrtmidi`

**Comment by bafonso** [comment]
I've now changed the code in v0.6 to the following:
```make
include $(RACK_DIR)/arch.mk
ifeq ($(ARCH), win)
	LDFLAGS += -L"$(RACK_DIR)/dep/lib" -lrtmidi
endif
```

**Comment by dizzisound** [comment]
@bafonso Thanks to @AndrewBelt for this, and I hope to see MPE back soon in Plugin Manager :-)

**Comment by phdsg** [comment]
can't update the repo-pointer right now...
probably later today if no one else is faster.

**Comment by phdsg** [comment]
@bafonso oh, now i see that you changed the `SLUG` from __Erratic__ (`master` branch) to __ErraticInstruments__ (`v0.6` branch).
this is a patch-breaking change, see...
https://vcvrack.com/manual/PluginDevelopmentTutorial.html under _Naming_.
please decide and let us know.

**Comment by bafonso** [comment]
I'd like to use erraticInstruments going forward. Please ignore master for
now, use v0.6

**Comment by phdsg** [comment]
@AndrewBelt what's the proper way to change the repo pointer? delete the old one and add a new one? just edit .gitmodules? or is there a fancy git command?

**Comment by AndrewBelt** [comment]
Edit .modules and `git submodule sync`

**Comment by bafonso** [comment]
Changed default branch to v0.6. Just a FYI if it makes things easier for you guys :)

**Comment by phdsg** [comment]
@AndrewBelt that didn't work for me... now i removed the old one with `git submodule deinit` and `git rm` and then added the new one...

@bafonso 
1. tried building vs Rack-SDK on windows. getting this error:

```
make[1]: Entering directory '/h/devel/vcv/community/repos/ErraticInstruments'
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MPEToCV.cpp.o src/MPEToCV.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/QuadMPEToCV.cpp.o src/QuadMPEToCV.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MPEBaseWidget.cpp.o src/MPEBaseWidget.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Erratic.cpp.o src/Erratic.cpp
g++ -o plugin.dll build/src/MPEToCV.cpp.o build/src/QuadMPEToCV.cpp.o build/src/MPEBaseWidget.cpp.o build/src/Erratic.cpp.o  -L"/h/devel/vcv/Rack-SDK/dep/lib" -lrtmidi -shared -L/h/devel/vcv/Rack-SDK -lRack
H:/devel/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lrtmidi
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/h/devel/vcv/Rack-SDK/compile.mk:52: plugin.dll] Error 1
make[1]: Leaving directory '/h/devel/vcv/community/repos/ErraticInstruments'

```
2. small v0.5 leftover that's deprecated now.
https://github.com/bafonso/Erratic/blob/v0.6/src/Erratic.cpp#L14-L15
see:
https://github.com/VCVRack/Rack/blob/master/include/plugin.hpp#L35-L37

**Comment by dizzisound** [comment]
@bafonso Hi Bruno, for what it concerns the first point, it looks like the build infrastructure has changed, so with the new headless build against Rack-SDK I think you can get rid of the LDFLAGS specific assignment for the Windows platform. The SDK, for what I know, takes care to build and link the required dependencies, that in your case (_librtmidi_) is also a Rack dependency.

Following the new reference [Rack 0.6 API](https://github.com/VCVRack/Rack/issues/258) (see at the bottom of the linked page), after commenting the above line of the makefile, I tested the Windows build launching the new makefile script against Rack-SDK, i.e.: 
`RACK_DIR=<my Rack SDK path> make dist`
and it worked.

So, it seems you can simply comment out the line:
`LDFLAGS += -L"$(RACK_DIR)/dep/lib" -lrtmidi`
or better remove the following entire block:
```
include $(RACK_DIR)/arch.mk
ifeq ($(ARCH), win)
	LDFLAGS += -L"$(RACK_DIR)/dep/lib" -lrtmidi
endif
```
and the makefile should be compliant with the new build facility.

@phdsg Can you confirm if this solves the issue?

**Comment by bafonso** [comment]
@phdsg let me know if you'd like me to temporarily make these changes on my repo or if you can simply test out the proposed changes.

**Comment by phdsg** [comment]
@dizzisound @bafonso confirming suggested change fixes the build error.

**Comment by bafonso** [comment]
ok, I've removed that bit of code

**Comment by phdsg** [comment]
@AndrewBelt what did i miss, that this wasn't included in the latest run?

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by bafonso** [comment]
Updated to 0.6.2.

**Comment by AndrewBelt** [comment]
Updated build.
