### ISSUE TITLE
Superbooth '18 meetup anyone!?

### ISSUE THREAD

**Issue by phdsg** [VCVRack/community#448]
don't know if here is the right place to ask this, but: who's coming?

**Comment by WIZARDISHUNGRY** [comment]
I was on the fence about attending, but it looks like I won't be able to. This is definitely the right place to ask (IMO).

**Comment by AndrewBelt** [comment]
Not me unfortunately.

**Comment by AndrewBelt** [comment]
New thread https://github.com/VCVRack/Rack/issues/902
