### ISSUE TITLE
SubmarinePrototype

### ISSUE THREAD

**Issue by david-c14** [VCVRack/community#457]
Slug: SubmarinePrototype
Version: 0.6.0
Source repository: https://github.com/david-c14/submarine-prototype-vcv.git
Commit: 32365b0eea13431692e28cbc46db8048481c63e6
Tag: 0.6.0
License: Proprietary
Author: carbon14
Website: https://github.com/david-c14/submarine-prototype-vcv
Manual: https://github.com/david-c14/submarine-prototype-vcv/blob/master/manual/index.md

**Comment by phdsg** [comment]
@AndrewBelt i was just about to post that `make dist` would fail without a LICENSE file, but it seems that's not the case anymore!?

**Comment by AndrewBelt** [comment]
The build will fail if the Makefile adds particular files to `DISTRIBUTABLES` which don't exist. But in https://github.com/david-c14/submarine-prototype-vcv/blob/master/Makefile#L21, the wildcard will match zero files and return an empty string, so it doesn't cause a problem.

**Comment by phdsg** [comment]
@david-c14 not that it matters much, but are all those unused svgs meant to be part of the package?

**Comment by david-c14** [comment]
@phdsg Is there a good way to exclude them from the dist? 

It really doesn't matter much, but I am hoping to start another module in there soon, so I can certainly try to tidy up before my next release.
