### ISSUE TITLE
PG Instruments

### ISSUE THREAD

**Issue by imekon** [VCVRack/community#459]
Slug: PG-Instruments
Version: 0.6.0
Source repository: https://github.com/imekon/PG-Instruments.git
Commit: 5f88dea26b6a9697727305b99e7f4402e3369c6f
License: MIT
Author: Pete Goodwin
Website: https://github.com/imekon/PG-Instruments

**Comment by AndrewBelt** [comment]
See License section of https://github.com/VCVRack/Fundamental#license. You need to design your own SEQ-3 panel from scratch.

**Comment by imekon** [comment]
I've updated the SEQ-3 panel.

**Comment by AndrewBelt** [comment]
Thanks! Looks good

**Comment by phdsg** [comment]
@imekon one more small thing:
LICENSE.txt in your repo is a CC license, not MIT.

**Comment by imekon** [comment]
My bad.

License: CC0 1.0 Universal

**Comment by imekon** [comment]
Updated 0.6.1

Added a few more plugins - panning and filter

**Comment by phdsg** [comment]
Updated build.
