### ISSUE TITLE
PulsumQuadratum-SDR

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/community#462]
This plugin is open source, but needs a bit of build massaging right now; so we'd ask to provide the builds for now.

**Comment by WIZARDISHUNGRY** [comment]
Version: 0.6.0

https://github.com/bongozone/vcvrack-rtlsdr/files/1966761/PulsumQuadratum-SDR-0.6.0-win.zip
https://github.com/bongozone/vcvrack-rtlsdr/releases/download/v0.6.0/PulsumQuadratum-SDR-0.6.0-mac.zip

I'm unclear if I should bother submitting a pull request to update URLs, etc. in the manifest.

**Comment by WIZARDISHUNGRY** [comment]
Is there any chance of getting this added to the manifest? Again, I'd like to have this built from source eventually, but I don't have librtlsdr and libusb as part of the build process yet.

**Comment by mdemanett** [comment]
Think this is up to date; closing the ticket til next there's something to do.

**Comment by WIZARDISHUNGRY** [comment]
@mdemanett The zip files aren't in the manifest. Are open source modules required to be built by the build team?

**Comment by mdemanett** [comment]
Right, if you want to be updatable through the plugin manager, the build team does the builds.  Otherwise you're in the directory with a link to your site, where you can post builds to download.

@AndrewBelt jump in here if that's incorrect.

**Comment by WIZARDISHUNGRY** [comment]
That makes sense. I'll spend some engineering effort to get the dependencies building correctly.

Do open source modules have to be on all three problems ? Having link problems on Linux. 😟

**Comment by mdemanett** [comment]
I imagine it's all or nothing.

We can try to help here.  Or the new developers forum on facebook might be a good place to ask for help on weird issues like that.

**Comment by AndrewBelt** [comment]
Yes, the solution is to statically build dependencies required by your plugin and not rely on system libraries.
