### ISSUE TITLE
Add Wiki page for Contribution Guide

### ISSUE THREAD

**Issue by mgoin** [VCVRack/community#463]
When looking on how to make my own Rack plugin, I couldn't find a contributor guideline in the wiki. This is a commonplace resource in most open-source projects, especially ones that explicitly encourage community participation. I believe it would be worthwhile to add some sort of concrete guide to start people off.

I found a link to [this issue](https://github.com/VCVRack/community/issues/248) in the README and I feel like the majority of the process has already been documented here. It will just be a matter of rewording, restructuring, and placing it in the wiki. 

I will gladly implement this but it seems that only owners of the repository can add a wiki. Once I have have permissions, I will work on a PR.

**Comment by AndrewBelt** [comment]
Actually I should probably disable the wiki feature on this repo. If you'd like to contribute, join a team at https://github.com/VCVRack/community/issues/352, https://github.com/VCVRack/community/issues/354, or https://github.com/VCVRack/community/issues/269.
