### ISSUE TITLE
RODENTMODULES

### ISSUE THREAD

**Issue by RODENTCAT** [VCVRack/community#464]
Am I doing this right ?

{
  "name": "RODENTMODULES",
  "author": "RODENTCAT",
  "license": "CC0-1.0",
  "sourceUrl": "https://github.com/RODENTCAT/RODENTMODULES",
  "latestVersion": "0.6.0"
}

**Comment by mdemanett** [comment]
Almost - please bump your Makefile VERSION to 0.6.1.  Your manifest already has latestVersion 0.6.0, so need a new version number to trigger the build.

**Comment by AndrewBelt** [comment]
Awaiting developer response to ^
