### ISSUE TITLE
TorpedoDemo

### ISSUE THREAD

**Issue by david-c14** [VCVRack/community#473]
This is a place-holder for the TorpedoDemo plugin. Torpedo is not designed for end-users, it's designed for module developers, so I don't really think it should be downloadable from the plugin manager, and I wanted to make that clear in case anyone asked for it.   I don't object if it appears on the plugin manager web-page, it is open source, but I don't think it should be built by the community team, or selectable for automatic downloads. Thanks

Slug: TorpedoDemo
Version: 0.6.1
Source repository: https://github.com/david-c14/Torpedo.git
License: GPL-3
Author: carbon14
Website: https://github.com/david-c14/Torpedo
Manual: https://github.com/david-c14/Torpedo/wiki

**Comment by AndrewBelt** [comment]
Thanks, added.

A personal opinion: Since only 4 Rack plugins are GPL, this suggests that your license might be a bit too restrictive if your plan is wide adaptation of this library.

**Comment by david-c14** [comment]
Corrected.  Sorry, that's the second time I've made that typo
