### ISSUE TITLE
MSM

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/community#478]
Created this issue after my issue got closed and I cant re-open it.

MSM plugin version 0.6.1 is now available. 

"name": "MSM",
"author": "Phal-anx",
"authorUrl": "https://phal-anx.github.io",
"license": "CC BY-NC-ND 4.0",
"contactEmail": "phal.anx.art@gmail.com",
"manualUrl": "https://drive.google.com/file/d/1Cjof90oYVltSJuXu0hqpw9hIN3r3U94T/view",
"latestVersion": "0.6.1"

About the question of Andrew if I want to add my repo to the build system: my modules are closed source. I would only give it to 1 guy to do the build for the plugin manager (e.g. Andrew himself). But I m not sharing the code via github as I have an agreement with Rob Hordijk for the TVCF module to keep the source closed.

**Comment by AndrewBelt** [comment]
I'll reopen the existing repo.
