### ISSUE TITLE
How to build on a Mac now? Noob question.

### ISSUE THREAD

**Issue by biomassa** [VCVRack/community#481]
Hi. Could someone please explain how do I build the community plugins now? There's no makefile and if I do 'python ./build_updates.py' from the community/scripts directory all i get is this: 

`File "./build_updates.py", line 12
    raise Exception(f"Failed command: {cmd}")`

Thanks!

**Comment by AndrewBelt** [comment]
That script is used by the Build system and isn't designed for others' use. If you want to build plugins, use the normal method described at https://github.com/VCVRack/Rack#building-plugins.

**Comment by biomassa** [comment]
oh thanks, i didn't realize that. i was using the community repo for updating / building all free plugins at once.
