### ISSUE TITLE
moDllz

### ISSUE THREAD

**Issue by dllmusic** [VCVRack/community#488]
Update. Better (7x less) cpu load on MIDI Poly 16

version 0.6.5
hash: eb5687066f1ceda99a9162a49f309a269632cb8c
Master branch
https://github.com/dllmusic/moDllz

...had to open a new issue because I didn't close mine #389

**Comment by AndrewBelt** [comment]
Post your request at the bottom of the existing issue.

**Comment by dllmusic** [comment]
I posted it there but I cannot re-open the issue.... #389

**Comment by AndrewBelt** [comment]
VCV community members will reopen threads when we receive a new request.

**Comment by dllmusic** [comment]
Got it. Thanks
