### ISSUE TITLE
Vcv Rack not launching

### ISSUE THREAD

**Issue by KalAraneta** [VCVRack/community#496]
Hi Andrew and all,

I 've used VCV Rack and i am having a blast with it. Thank you. However, i tried putting Autodafe's new plugin in the plugin folder, after that the software won't launch anymore. Prior to this i already made 2 sessions and have updated to the latest firmware. Please help. 

Thank you

Kal

**Comment by AndrewBelt** [comment]
Use the Rack repository for posting issues with Rack (and perhaps Autodafe's email address for problems with Autodafe.)

**Comment by KalAraneta** [comment]
Hi Andrew,

I have figured it out and it was a plugin bug that’s preventing it from launching. Also, I have found a way to install properly the Autodafe or any 3rd party plugins that are not in the vcv market as a windows user just by extracting zip on the plugin folder, and by deleting the linus and mac folders in it , as well as a lot of copy and paste methods to unlayer the folder counts of the .dll file.

Thanks again for responding to this and may you continue to have prolonged patience and creativity in your road to making vcv rack from being a beta to a legendary program.

Regards,
Beer

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
