### ISSUE TITLE
Does the plugin developer provide builds for all platforms?

### ISSUE THREAD

**Issue by freddyz** [VCVRack/community#497]
Greetings - I'm developing my first VCV Rack plugins and preparing to submit them to the plugin repository.  My question is: do I need to create builds for all platforms (Mac, Windows, Linux) when submitting the plugin?  Apologies if this is the wrong place to ask this question, or if the answer is clearly available somewhere in the instructions - I wasn't able to find it.  Thank you!

**Comment by AndrewBelt** [comment]
For open-source plugins, the Build Team #353  builds and distributes plugins from source.
