### ISSUE TITLE
VCV version rack-0.6.2b-win.exe listed as threat by Symantec

### ISSUE THREAD

**Issue by pjc123** [VCVRack/community#499]
This could be one of those false positives, but anyway just letting you know that Symantec automatically removed your program when I attempted to installed it.  Threat name = WS.Reputation.1.  I don't remember this happening with my current version (0.5.1).

**Comment by AndrewBelt** [comment]
If you click "allow" or something, most antivirus programs will add it to their big database.

**Comment by pjc123** [comment]
Yes, I am aware of how to bypass it.  I just wanted to make sure you were not aware of any issues and to inform others.  You can close this thread.  Thanks.
