### ISSUE TITLE
Segmentation fault upon insertion of OG 104 (or gates)

### ISSUE THREAD

**Issue by WouterSpekkink** [VCVRack/community#503]
I am having a lot of issues with the OG 104 OR Gates on Debian 9. When I insert them, and sometimes when I use the context menu VCV rack often (but not always) crashes with a segmentation fault (illegal memory address accessed). It can create permanent problems with patches, causing immediate crashes on startup.

**Comment by AndrewBelt** [comment]
This is not the correct place for bug reports for "OG". Please use the contact information for that plugin.

**Comment by WouterSpekkink** [comment]
Oops, my mistake. I thought I was on the SubmarineFree repository.

**Comment by david-c14** [comment]
For anyone who finds this issue:

This has been fixed in SubmarineFree v0.6.8
