### ISSUE TITLE
SubmarineUtility

### ISSUE THREAD

**Issue by david-c14** [VCVRack/community#512]
First release of new plugin

Thank you.

Slug: SubmarineUtility 
Version: 0.6.1
Source repository: https://github.com/david-c14/SubmarineUtility.git 
Commit: f743399251e5c48bc2d7429c61493a8c5e9a6178 
Tag: v0.6.1 
License: BSD-3 
Author: carbon14 
Website: https://github.com/david-c14/SubmarineUtility 
Manual: https://github.com/david-c14/SubmarineUtility/blob/master/manual/index.md

**Comment by AndrewBelt** [comment]
Updated build

**Comment by david-c14** [comment]
Update to include 1 new module and 1 major bug fix

Thank you.

Slug: SubmarineUtility 
Version: 0.6.2
Source repository: https://github.com/david-c14/SubmarineUtility.git 
Commit: 12cac86eaed62fcf27b4c6c32d4c6f5e951f298c 
Tag: v0.6.2 
License: BSD-3 
Author: carbon14 
Website: https://github.com/david-c14/SubmarineUtility 
Manual: https://github.com/david-c14/SubmarineUtility/blob/master/manual/index.md

**Comment by AndrewBelt** [comment]
Updated build
