### ISSUE TITLE
BeckstromResearch

### ISSUE THREAD

**Issue by chrisbeckstrom** [VCVRack/community#513]
plugin name: Beckstrom Research
slug name: BeckstromResearch
Repository: https://github.com/chrisbeckstrom/Beckstrom_Research_Rack
email address: chris@chrisbeckstrom.com

**Comment by mdemanett** [comment]
Hey @chrisbeckstrom,

I added this to the system, which means it'll be queued to build and send out through the plugin manager.  

However you should make a fix: you don't want to check your .o, .so and .dylib files into git...these should be built by whoever uses the code (like the build system for the plugin manager).  Something like ```git rm -rf build/* plugin.so plugin.dylib```, and then commit and push, will take care of it.

**Comment by cschol** [comment]
@chrisbeckstrom you also will need to remove those binaries from the **HISTORY** of the repository. See this [link](https://help.github.com/articles/removing-sensitive-data-from-a-repository) for more information on how to remove files from the repository history.

**Comment by chrisbeckstrom** [comment]
Thanks @mdemanett and @cschol ! I think I have a lot to learn, thanks for helping me with this.  
I removed those unnecessary files, then purged them from git (I hope!).  
Am I correct in understanding that 
> it'll be queued to build and send out through the plugin manager . 
...means that at some point in the future, folks will be able to add my plugins via the plugin manager and have them automatically added to their plugins folder on their local machine? I.e. they won't have to build anything, the files will just appear and be ready to use

**Comment by cschol** [comment]
Sorry, this is not quite enough yet, as the files are still in the HISTORY of the repository, i.e. I can check out an earlier revision of the repo and the files are back.

See the steps in this issue https://github.com/chrisbeckstrom/Beckstrom_Research_Rack/issues/7 to resolve it.

**Comment by AndrewBelt** [comment]
It's not a huge issue because it's probably only a MB or two, but it does add up. We just don't want a recursive checkout to take up 20GB of space.

**Comment by AndrewBelt** [comment]
Updated build
