### ISSUE TITLE
aP-Modules

### ISSUE THREAD

**Issue by aptrn** [VCVRack/community#517]
Hello there, got some modules going!

name: aP Modules
author: Alessandro Petrone
license: BSD-3-Clause
contactEmail: alessandro.nge@gmail.com
pluginUrl: https://github.com/aptrn/aP-Modules
authorUrl: https://www.facebook.com/mai.piu.cioccabbiocco
manualUrl: https://github.com/aptrn/aP-Modules/blob/master/README.md
sourceUrl: https://github.com/aptrn/aP-Modules.git
donateUrl: https://www.paypal.me/aptrn
latestVersion: 0.6.0

**Comment by cschol** [comment]
Thank you for submitting your plugin. It has been integrated into the community repository. With the next round of updates it should become available via the plugin manager. Please let us know in **this issue** when new versions are available. We will reopen the issue then and integrate the changes.

**Comment by AndrewBelt** [comment]
Updated build
