### ISSUE TITLE
arjo_modules

### ISSUE THREAD

**Issue by ArjoNagelhout** [VCVRack/community#518]
```
{
  "name": "arjo_modules",
  "author": "Arjo Nagelhout",
  "license": "CC-BY-NC-4.0",
  "authorUrl": "https://github.com/ArjoNagelhout",
  "authorEmail": "arjo.nagelhout@gmail.com",
  "manualUrl": "https://github.com/ArjoNagelhout/arjo_modules/blob/master/README.md",
  "sourceUrl": "https://github.com/ArjoNagelhout/arjo_modules",
  "latestVersion": "0.6.0",
  "repoVersion": "0.6.0",
  "status": "available"
}
```

**Comment by cschol** [comment]
Thank you for submitting your plugin. Please clarify the following for me:

1. "slug": Is it just `arjo` or `arjo_modules`?
2. License: The `json` above states `MIT`, but the `LICENSE.txt` file in the repository is `Creative Commons`. Please choose one or the other and update accordingly.

**Comment by ArjoNagelhout** [comment]
I updated `LICENSE.txt` and the `json` above with the license CC BY-NC 4.0. I also updated all the names to `arjo_modules`. Let me know if there are any more issues, I'm quite new to this.

**Comment by cschol** [comment]
The slug in the `Makefile` is still just `arjo`. Understand that the slug determines the name by which the module is known to Rack, i.e. how it shows up in the module browser. Either way is fine, but it needs to be consistent. Thanks.

**Comment by cschol** [comment]
Your plugin was integrated in the community repository and will be available in the plugin manager the next time the builds are updated. Please let us know about new versions of your plugin in **this issue**. We will reopen it and track the new version. Thank you for providing your plugin to the Rack community!

**Comment by cschol** [comment]
Andrew updated build yesterday.
