### ISSUE TITLE
STS 0.6.0.3 relese

### ISSUE THREAD

**Issue by SmallTownSound** [VCVRack/community#532]
0.6.0.3 release.  No source code with this one yet,

[STS-0.6.0.3-lin.zip](https://github.com/VCVRack/community/files/2715891/STS-0.6.0.3-lin.zip)
[STS-0.6.0.3-mac.zip](https://github.com/VCVRack/community/files/2715892/STS-0.6.0.3-mac.zip)
[STS-0.6.0.3-win.zip](https://github.com/VCVRack/community/files/2715893/STS-0.6.0.3-win.zip)

**Comment by AndrewBelt** [comment]
For closed-source free plugins, see https://github.com/VCVRack/community#addingupdating-your-plugins-build-for-closed-source-free-and-commercial-plugins.
