### ISSUE TITLE
AnimatedCircuits

### ISSUE THREAD

**Issue by AnimatedCircuits** [VCVRack/community#576]
Hi,

I'm happy to submit my 1st plugin to be available via the PM (only one module atm) ! 

source URL : [https://github.com/AnimatedCircuits/RackModules](https://github.com/AnimatedCircuits/RackModules) 

Please tell me if anything is wrong or missing.
Thank you and have a nice day !
note : I can't see how to add the "plugin" tag

**Comment by AnimatedCircuits** [comment]
v2.0.0
0177eb679a822bc11125987dc9ce29aa6bd7ac67

**Comment by cschol** [comment]
Fails to load SVG: https://github.com/AnimatedCircuits/RackModules/issues/5

**Comment by AnimatedCircuits** [comment]
Hi,
It should be corrected with this commit 
3bc8a88494f413f1665fe28fbac821280ec507f6
Thank you

**Comment by AnimatedCircuits** [comment]
Hi !
V2.1.0
bd45fc5e9b472182bcc74da264f865d1424a76be

Thank you

**Comment by AnimatedCircuits** [comment]
Hi !

v2.2.0
6577880b5680c0b6487ff981de468bfe117a6f0a

Thank you
