### ISSUE TITLE
Ahornberg

### ISSUE THREAD

**Issue by Coirt** [VCVRack/community#577]
Hi, looking to add Ahornberg-Microtonal to the PM/PL

Version: 1.0.1
Commit: 65c3ac2
License: CC0
Manifest: https://github.com/Coirt/Ahornberg-Microtonal/blob/master/plugin.json

**Comment by cschol** [comment]
`plugin.json` issues:

```
[Ahornberg] Issues found in `plugin.json`:

Invalid license ID: CC0
-- License must be a valid Identifier from https://spdx.org/licenses/
```

**Comment by Coirt** [comment]
What is the valid identifier for CC0, got that from the manual.

https://vcvrack.com/manual/PluginLicensing.html

**Comment by Coirt** [comment]
CC0-1.0 ?

**Comment by cschol** [comment]
`CC0-1.0`, yes per the SPDX website. It is supposed to be the SPDX **identifier** not just the license name.

**Comment by Coirt** [comment]
Fixed in 13af260

**Comment by Ahornberg** [comment]
version 1.0.2
commit c8beb50de1bbdd4d8129ad84e6c04ebd856980d2

**Comment by Coirt** [comment]
Just to note this version is no longer my fork. Changes are in the original repo here: https://github.com/Ahornberg/Ahornberg-Microtonal

Manifest: https://github.com/Ahornberg/Ahornberg-Microtonal/blob/master/plugin.json

**Comment by cschol** [comment]
@Coirt Are we switching this plugin to the original source in @Ahornberg repository?

**Comment by AndrewBelt** [comment]
If @Ahornberg's version is more "standard", then yes.

**Comment by Ahornberg** [comment]
I changed the in's and out's to support polyphonic cables and I corrected the way the "fine-tune" knob works.

**Comment by Coirt** [comment]
@cschol yeah whatever @Ahornberg wants to do, it is his repo!

**Comment by Ahornberg** [comment]
version 1.1.0
commit 64e3f8eaa5e05345051a339a9055f431a9f1c986

**Comment by Ahornberg** [comment]
added 2 new modules
version: 1.2.0
commit: 2e0f1775c412f8a6c4ac15f79e1945cbf6e66c06

**Comment by Ahornberg** [comment]
added 1 new module
version 1.3.0
commit: c9c0fbba13a5043f129a4b470b1bf86af8a42047

**Comment by Ahornberg** [comment]
minor changes in module 'Fun With Frames'
version: 1.3.1
commit: 135bbace495381c104c08ee805916e3f8d25436a

**Comment by Ahornberg** [comment]
added apreggios to module 'Fun With Frames'
version: 1.3.3
commit: c1d336a542aa1e41957e632463a738cde3e1bcc5

**Comment by Ahornberg** [comment]
added module 'Tape Recorder'
version: 1.4.0
commit: 44030962803598bb3f426093685d5af63415dfe9

**Comment by Ahornberg** [comment]
added module 'MIDI over Audio'
version: 1.5.0
commit: f34fa187ae4512e534fb63a3f1765ff81940b11d

**Comment by cschol** [comment]
Build failure on macOS platform: https://github.com/Ahornberg/Ahornberg-VCV-Modules/issues/12

**Comment by Ahornberg** [comment]
removed unnessesary 'extern'

commit: c5510a1ccc1490c0a1769dc2219d5b6f123efe00

**Comment by cschol** [comment]
Rack crash when enabling MIDIOverAudio module: https://github.com/Ahornberg/Ahornberg-VCV-Modules/issues/13

@AndrewBelt can you please take a peek at the issue? Looks like this is a known issue in Rack and I need a decision whether the approach the module took is acceptable (warn of the crash dialog).

**Comment by AndrewBelt** [comment]
Because of the module being disabled by default with the option to disable again once enabled, I think it should be accepted to the VCV Library for Rack v1.

**Comment by cschol** [comment]
Sounds good. Will be integrated today.

**Comment by Ahornberg** [comment]
added a parameter loop-mode to module 'Tape Recorder'
version: 1.5.1
commit: 968b381ec1dc3720e3d05e8441d3455496c4115e

**Comment by Ahornberg** [comment]
some minor additions to TapeRecorder to make it usable as a tape delay
version 1.5.2
commit 48eed8937b216c5d76974bd428784c7743955d01

**Comment by Ahornberg** [comment]
added module Flying Fader
version 1.6.0
commit 39a9cd60560ef94b05abc127c76d1617377e983d

**Comment by Ahornberg** [comment]
bugfix in module Flying Fader
version 1.6.1
commit cba9ea4b259633f2c09a63a26fcad2557fe3c49c

**Comment by Ahornberg** [comment]
two new features in module Flying Fader: polyphonic modes, CV-scaling modes
version 1.6.2
commit 7fb2d0a6ef13d16c18286ee7184e7b961dd675eb

**Comment by Ahornberg** [comment]
port to v2
version 2.0.0
commit 1ba3fde3bc617569e8179b66deba59e4fcd5d00c

**Comment by Ahornberg** [comment]
added a new module "MIDI Poly Expression" to support the LinnStrument
version 2.1.0
commit 78ff7fd73cf4646a6abe589a7286658c6041b866

**Comment by Ahornberg** [comment]
bugfix for module "MIDI Poly Expression"
version 2.1.1
commit 6f48187fabafa09fdfd6d8fae7a1144e4c83b54c

**Comment by Ahornberg** [comment]
additional parameter for module "MIDI Poly Expression"
version 2.1.2
commit 07f812d3aafe5fa1765f9b0f719495d4182a68bf

**Comment by Ahornberg** [comment]
added menu entry for loading factory selections
version 2.1.3
commit def54562a9da90e71f1fc6b8ab3804ad529c2923

**Comment by Ahornberg** [comment]
module TapeRecorder: added linear interpolation on playback
version 2.1.4
commit 1bafab9c41c783e645982288e161827636050dbb

**Comment by Ahornberg** [comment]
module MIDIPolyExpression: added parameter 'Volume Shape'
version 2.1.5
commit 13e58d7d1724a5b292c53761806a1aa8701bcd09

**Comment by Ahornberg** [comment]
added new module CopyPastePreset
version 2.1.6
commit 5a4728eec9b027de7696e8cf9ba5e8c734170a8d

**Comment by Ahornberg** [comment]
bugfix in module TapeRecorder
removed decorative screws from all modules
version 2.1.7
commit c9f11d396458cbe6fffe5ae6106a583a70bdca23

**Comment by Ahornberg** [comment]
module MidiPolyExpression: additional parameter for decay, z-axis accepts midi cc 11
version 2.1.8
commit d2f81147fa5478e61ca77304889b9e355bde22d8

**Comment by Ahornberg** [comment]
refinements on module MidiPolyExpression
version 2.1.9
commit 72b98b51cb957d5b05380944e8a0c1d3bb27d99f

**Comment by Ahornberg** [comment]
bugfix on loading/saving module asset and loop cycle mode in TapeRecorder
and refinements in module MIDIPolyExpression
version 2.1.10
commit 2d030f5ce12572bf9f6e94639bc66d921478fd69

**Comment by Ahornberg** [comment]
load/save presets with audio data on TapeRecorder
version 2.1.11
commit c02ae78d1bd121ea36ae0a412964f9b68dd78ec4

**Comment by Ahornberg** [comment]
added 2 buttons for fine-tuning loop points on TapeRecorder
version 2.1.12
commit 704d1857e3d2efc07ab8eaabed3de35ceb21f3a8

**Comment by Ahornberg** [comment]
added module Tape Inspector, an expander module for Tape Recorder
version 2.2.0
commit 36247a9a3d1d0106037594c0341035a62d93567f

**Comment by Ahornberg** [comment]
fixed Tape Recorder not loading from selection, added module X-Glide
version 2.3.0
commit 76836c9bd564c45542970a785319bf5f58223d2e

**Comment by Ahornberg** [comment]
added modulation input and output to module X-Glide
version 2.3.1
commit e1c38a19b31c7a4ad656bd8bec5915255e78c3f1

**Comment by Ahornberg** [comment]
added small enhancements on module tape inspector
version 2.3.2
commit 395d677d7b9cec449e6fd8d29a546df6b8fd7f27

**Comment by Ahornberg** [comment]
added dark panels for all modules and minor enhancements to MPE module
version 2.3.3
commit 4cd51dced35683622e5dd118249d28e2bc234fc0

thanks in advance for publishing in the VCV library!

**Comment by Ahornberg** [comment]
are there any problems/issues with my version 2.3.3?

**Comment by Ahornberg** [comment]
version 2.3.4
bugfix in MPE module
commit 3a9441f594d6a7cc8b6f11c19ff81d95ff8977ad
