### ISSUE TITLE
Prism

### ISSUE THREAD

**Issue by AmalgamatedHarmonics** [VCVRack/community#578]
This contains the port of 4ms' SMR module to VCV; I have been in contact with Dan Green at 4ms and he was actually quite enthusiastic about it.

Version: 1.0.0
Commit: 7ac4ddb5fda2ecca781d97c73adba10ad6106384
License: BSD-3-Clause
Manifest: https://github.com/AmalgamatedHarmonics/Prism/blob/master/plugin.json

**Comment by AmalgamatedHarmonics** [comment]
Version: 1.0.1
Hash: db876803f8879a5d3e274880a062801301c07afe

**Comment by AmalgamatedHarmonics** [comment]
Version: 1.0.2
Hash: b25df8f87a8a51636d7fe0f11572a1b319cbb1bc

**Comment by AmalgamatedHarmonics** [comment]
Version: 1.0.2
Hash: d741a93182694a2087756ef93bfe8867405dc240

**Comment by AmalgamatedHarmonics** [comment]
Version 1.1.0
Hash: b501cfff078f3506fc5e1e6bd195c1aea1742708

**Comment by AmalgamatedHarmonics** [comment]
Hi,

A linux build problem was spotted, It's fixed in hash

fdf6bfd39ad6f466516c12aad3c024664c54b5cb

Sorry about that

**Comment by cschol** [comment]
Compile error on Mac: https://github.com/AmalgamatedHarmonics/Prism/issues/6

**Comment by AmalgamatedHarmonics** [comment]
Fixed in ee9e636c92fbd3dad2fb89a8fd7c436d8c90c0d3

**Comment by AmalgamatedHarmonics** [comment]
Version 1.2.0
Hash: 34094a5e78048816e608063b45e11a538c0341eb

**Comment by SteveRussell33** [comment]
New repo URL: https://github.com/SteveRussell33/Prism
Branch: Rack2
Version: 2.3.0 (as it would've been v1.3.0 for v1)
Commit: fe972657288188a7ba112ca161eb2f5cf0741070

**Comment by SteveRussell33** [comment]
New repo URL: https://github.com/SteveRussell33/Prism
Branch: Rack2
Version: 2.3.0 (as it would've been v1.3.0 for v1)
Commit: 6fffd027173683433b86a8d6dbd5bf35952fc2f6

**Comment by cschol** [comment]
@AndrewBelt Ownership transfer for Prism from John to Steve documented here: https://github.com/AmalgamatedHarmonics/Prism/pull/19#issuecomment-980235943

**Comment by SteveRussell33** [comment]
Tag update

Version: 2.3.1
Commit: 50dbf1aeeeaa20d0cf669de0dfaa8d8f7e84b215

**Comment by SteveRussell33** [comment]
Changelog and manifest updates

Version: 2.3.2
Commit: 0397896320ddd4b3e92ab36c4b047e410c472f6f

**Comment by SteveRussell33** [comment]
Hotfix for DarkMode LEDs and the odd patch load crash

Version: 2.3.3
6b2510c601db8bd3b57cd5eef8c2924cb8badfc7

**Comment by SteveRussell33** [comment]
Hotfix for DarkMode LEDs and the odd patch load crash

Version: 2.3.3
6b2510c601db8bd3b57cd5eef8c2924cb8badfc7

**Comment by SteveRussell33** [comment]
Various fixes

Version: 2.3.4
12db31e801907bf60f70d27fa133e72903415304
