### ISSUE TITLE
ByteBeatMachine

### ISSUE THREAD

**Issue by bokontep** [VCVRack/community#579]
Hello,
I updated ByteBeatMachine for rack 1.X
I created a new Github repository:
Github code URL:
https://github.com/bokontep/ByteBeatMachine.git
git hash:
6ed688e65bd458dd127a90be4dfb2c308a26af44
manifest:
https://github.com/bokontep/ByteBeatMachine/blob/master/plugin.json

**Comment by cschol** [comment]
Please reuse issue #465.
