### ISSUE TITLE
repelzen

### ISSUE THREAD

**Issue by wiqid** [VCVRack/community#580]
please include the repelzen plugin in the plugin library

code: https://github.com/wiqid/repelzen
branch: master
version: 1.1.0
commit hash: 5ef6052ad79973c75d2083123ee64c90da9e2807

**Comment by cschol** [comment]
Thank you for submitting your plugin to the Plugin Manager. It has been integrated and will be available for all platform with the next build system update. 

Please let us know in **this** issue when a new version is available. We will reopen it. Thank you!

**Comment by wiqid** [comment]
update to 2.0.0
commit hash: 78b1765eb9ccb9e4e2a1967ee02f4126b1846806
