### ISSUE TITLE
LomasModules

### ISSUE THREAD

**Issue by LomasModules** [VCVRack/community#581]
https://github.com/LomasModules/LomasModules

branch: master
version: 1.0.1
commit e8e2dea6bb291ebb78fdf92e48977cf91492e424

**Comment by cschol** [comment]
Thank you for submitting your plugin to the Plugin Manager. It has been integrated and will be available for all platform with the next build system update. 

Please let us know in **this** issue when a new version is available. We will reopen it. Thank you!

**Comment by LomasModules** [comment]
https://github.com/LomasModules/LomasModules

branch: master
version: 1.0.2
commit 004f343539a76ba256b6c07b2724801275a935ae

Hello,
Could you update the module on the Plugin Manager?

Thanks in advice.

**Comment by LomasModules** [comment]
https://github.com/LomasModules/LomasModules

branch: master
version: 1.0.5
commit ddfdf170be09d0f0d065f3691e9bbc90942e8131

Hello,
Could you update the module on the Plugin Manager?

Thanks in advice.

**Comment by AndrewBelt** [comment]
Version in `plugin.json` is not updated to 1.0.5.

**Comment by LomasModules** [comment]
Sorry for the mistake Andrew. I had to make a new tag because I have no clue how git works. 

https://github.com/LomasModules/LomasModules

branch: master
version: 1.0.6
commit: ff0a19bcbe8816e0c808b8f98b0860fee6f652b8ranch: master

**Comment by LomasModules** [comment]
Hi,

Could you please update the module on the Plugin Manager?

https://github.com/LomasModules/LomasModules

branch: master
version: 1.0.9
commit 533a79609cc1066d552195deb1b4fb6f003807e3

Thanks in advice.

**Comment by cschol** [comment]
Update requested:

Git-URL: https://github.com/LomasModules/LomasModules
Branch: master
Commit: 1def9f3
