### ISSUE TITLE
WrongPeople

### ISSUE THREAD

**Issue by WrongPeople** [VCVRack/community#584]
https://github.com/WrongPeople/WrongPeopleVCV

**Comment by cschol** [comment]
The dependencies `luajit` and `midifile` do not compile in a cross-compilation environment on Linux. Linux build works fine. The Rack build system uses cross-compilation to build Windows and Mac builds. You either need to update this to work with cross-compilation on Linux or @AndrewBelt needs to add this to the list to be built manually. Any thoughts @AndrewBelt?

**Comment by WrongPeople** [comment]
How I can set up the same environment for cross-compilation? Is there a dockerfile?

**Comment by cschol** [comment]
I don't have one unfortunately. I run Ubuntu 18.04 with `mingw` tool chain installed to cross-compile for Windows. `osxcross` toolchain for Mac.

**Comment by WrongPeople** [comment]
Now it compiles from Linux for Windows with
`CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ STRIP=x86_64-w64-mingw32-strip HOST_CC="gcc -m64" CROSS=x86_64-w64-mingw32- TARGET_SYS=Windows make`.
Please, tell me exact commands which you using for cross-compilation for Mac and Windows.

**Comment by cschol** [comment]
For Mac:

```
CC=x86_64-apple-darwin17-clang CXX=x86_64-apple-darwin17-clang++ STRIP=x86_64-apple-darwin17-strip make
```

**Comment by WrongPeople** [comment]
I added `LUAJIT_CC` option to Makefile, so you can try to use the following command:
`CC=x86_64-apple-darwin17-clang CXX=x86_64-apple-darwin17-clang++ STRIP=x86_64-apple-darwin17-strip LUAJIT_CC=clang HOST_CC="gcc -m64" CROSS=x86_64-apple-darwin17- TARGET_SYS=Darwin make`

**Comment by WrongPeople** [comment]
Done.
Now it can be compiled for all platforms with no need to pass additional options like `LUAJIT_CC=... HOST_CC=... CROSS=... TARGET_SYS=...`.

**Comment by WrongPeople** [comment]
All builds tested and it works.

**Comment by AndrewBelt** [comment]
The build system runs `make cleandep` before building, but you have git submodules in here which it removes. You need to move those submodules out of that directory.

**Comment by WrongPeople** [comment]
[Done](https://github.com/WrongPeople/WrongPeopleVCV/commit/a1f99402e2d4ae66fc00fbf91b0b7a48e07b32d1).

**Comment by cschol** [comment]
The plugin has been integrated and will be available for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the VCV community.

**Comment by WrongPeople** [comment]
Version: 1.0.1
Commit: 74c8d2bd7246813ff60887e0bd9068a84b7b21b3
