### ISSUE TITLE
GoodSheperd

### ISSUE THREAD

**Issue by jensschulze** [VCVRack/community#585]
Please include the GoodSheperd plugin into the VCV plugin library.

Code: https://github.com/jensschulze/GoodSheperd

BTW thanks for your great work 👍

**Comment by cschol** [comment]
Thank you for submitting your plugin to the library repository. It has been integrated and will be available for all supported platforms with the next build update. Please use **this** issue to notify us about new versions of the plugin. We will reopen the issue.

**Comment by jensschulze** [comment]
New version: 1.0.1
Hash: be789e5685e10ca06feb1316b3f9dd06ea455cec

Thanks 😃

**Comment by jensschulze** [comment]
New version: 1.1.0
Hash: c90fde23d5a058722bd16eba36c73369661e33d9

Thanks 😀

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/jensschulze/GoodSheperd/issues/14

**Comment by jensschulze** [comment]
Fixed it:
New version: 1.1.0
Hash: b0aa60de0ddc71a776f254d5156db0b29aaa4a21

**Comment by jensschulze** [comment]
New version: 2.0.0
Hash: 636351059f2eec629f3b8a537451dd3d0eb01c30
