### ISSUE TITLE
SignalFlux

### ISSUE THREAD

**Issue by signal-flux** [VCVRack/community#586]
Repository: https://github.com/signal-flux/Signal-Flux-VCV-Rack-Modules
Branch: Master
Latest Version : 1.0.1
commit hash: 39cdfdb9048b18e35eb29460231a1ee7aca20a53

It's simple, but I felt it was necessary for a class I am going to be a teaching so I figured I would make my first VCV module!  Will be slowly adding to this...

**Comment by signal-flux** [comment]
Added a small update already!

**Comment by cschol** [comment]
Invalid license Id: https://github.com/signal-flux/Signal-Flux-VCV-Rack-Modules/issues/1

**Comment by signal-flux** [comment]
Okay I fixed that!

Repository: https://github.com/signal-flux/Signal-Flux-VCV-Rack-Modules
Branch: Master
Latest Version : 1.0.1
commit hash: 7ad20f35a0b4ede7a90118610894a92a4ad794f3

**Comment by cschol** [comment]
Thank you. Your plugin has been integrated and will be available in the Plugin Manager for all supported platforms with the next update. Please let us know in **this** issue when a new version is available. We will reopen it.

**Comment by signal-flux** [comment]
Hi - 

A new version is available, which adds three modules.  Please see below.

Repository: https://github.com/signal-flux/Signal-Flux-VCV-Rack-Modules
Branch: Master
Latest Version : 1.1.0
commit hash: cca69215d807b3736a7601d3bce15c69f03331e4

**Comment by signal-flux** [comment]
@cschol 

Hi! 

I was wondering if you knew if this will be pushed to the repo by September 3rd?  I am teaching a class that will be using these modules, and would like to figure out if I should send the students a package with the modules, or if they will be able to update the plugin from VCV Rack's manager - thanks!  If you do not know the answer, no worries!  Just wanted to check since I do not have a general sense of how often these updates get folded into the library.

Sam

**Comment by AndrewBelt** [comment]
@cschol is on vacation, so I have reviewed and updated your plugin.
