### ISSUE TITLE
Admiral

### ISSUE THREAD

**Issue by wapiflapi** [VCVRack/community#587]
Admiral has been tested on linux and windows and seems to work fine. The integration with travis-ci automatically builds (successfully) for linux, windows and mac on my github repository.

I think this is ready to be included in the official library but please tell me if I should change or check anything. It's my first time working with VCV.

**Admiral** - version: `1.0.0`
git: https://github.com/wapiflapi/admiral/
tag `v1.0`, commit hash: `2d853f2badced2175a49aa0e7f2f888c3755319b`

The release can be found on github at: https://github.com/wapiflapi/admiral/releases/tag/v1.0

**Comment by cschol** [comment]
The plugin has been integrated and will be available for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the VCV community.

**Comment by wapiflapi** [comment]
Hey, I have **updated Admiral** to a new version, adding a module and adding some features to existing ones. Everything is retro-compatible and shouldn't break any patches.

**Admiral** - version: 1.1.0
git: https://github.com/wapiflapi/admiral/
tag v1.1, commit hash: 2885b72e1e82b1103eb2cb4db2a226c57c9e5f40

The release can be found on github at: https://github.com/wapiflapi/admiral/releases/tag/v1.1
