### ISSUE TITLE
CatroBlanco

### ISSUE THREAD

**Issue by catronomix** [VCVRack/community#589]
A new plugin pack with some decorated panels :)
e0dd5beb22f2ff03324e600d0ca0dfc3c4336cf2
https://github.com/catronomix/Catro-Blanco/commit/e0dd5beb22f2ff03324e600d0ca0dfc3c4336cf2

```
"slug": "CatroBlanco",
  "name": "Catro/Blanco",
  "version": "1.0.0",
  "license": "BSD-3-Clause",
  "brand": "Catro/Blanco",
  "author": "catronomix",
  "authorEmail": "catronomix+dev@gmail.com",
  "authorUrl": "https://www.instagram.com/catronomix/",
  "pluginUrl": "https://github.com/catronomix/catro-blanco",
  "manualUrl": "",
  "sourceUrl": "https://github.com/catronomix/catro-blanco",
```

**Comment by cschol** [comment]
The plugin has been integrated and will be available for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the VCV community.
