### ISSUE TITLE
Chiptuner

### ISSUE THREAD

**Issue by The-Great-Assyr** [VCVRack/community#591]
Hello! :-D
This is my Chiptuner blank plates plugin, finally updated for the latest VCV release!
The source code URL is the following: https://github.com/The-Great-Assyr/Chiptuner-0.6.2
David O'Rourke (david-c14) helped me rebuilding the code, migrating it from the previous version to the 1.1.4
Hoping to see it soon in the official library!

Kindly,

AG

**Comment by AndrewBelt** [comment]
Might be a good idea to change the repo URL and all the URLs in the manifest.

**Comment by The-Great-Assyr** [comment]
> 
> 
> Might be a good idea to change the repo URL and all the URLs in the manifest.

You are right, I hadn't figure out how to do it but now it's done. It should work properly.

Kidnly,

AG

**Comment by AndrewBelt** [comment]
Why are you including the version name in the repo at all?

**Comment by The-Great-Assyr** [comment]
Because I saw it done it like that by David O'Rourke when he updated my plugin so I just let it as I found it. I can barely manage github so I do not dare to touch things I don't know or I am not totally sure about.

Kindly,

AG

**Comment by cschol** [comment]
What's the status of this? I recommend in general that you get familiar with Github and learn how to use it properly. Having a version number in your repo name is generally a bad practice. Versions are handled by SHAs and tags.

**Comment by AndrewBelt** [comment]
git and GitHub are easy to use. Here's what I suggest.
- Remove version `10` from slug.
- Remove version `1.0` from name.
- Rename GitHub URL to just `Chiptuner` and update manifest accordingly.

At the end of these changes, the `"version"` property should be the only place that the version is defined. See [DRY Principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by The-Great-Assyr** [comment]
Thanks for pointing me to the DRY Principle. :-)
So...

- Removed version 10 from the slug

- Removed version 1.0 from the name

- Renamed GitHub URL to Chiptuner and manifest updated.

**Comment by AndrewBelt** [comment]
Must have forgotten to close this. Build updated yesterday.

**Comment by The-Great-Assyr** [comment]
Hello there and friendly greetings! After A LOT of difficulties and the precious help of some rackheads from the forum, I think now the plugin is now ready to be updated and added to the library. Please, have a little patience here. I still don't know 100% what I am doing and I am struggling to follow the suggestions....

FORUM LINK - https://community.vcvrack.com/t/who-wants-to-upgrade-my-modules/19986

**Comment by The-Great-Assyr** [comment]
Hello there! Thanks to the help of Evan Murray (even if I haven't checked it at the time) and Steve Russel two days ago, I think my plugin is now ready to be updated and added to the library. If you need something, kindly let me know and I'll do my best to accomplish.
