### ISSUE TITLE
GlueTheGiant

### ISSUE THREAD

**Issue by gluethegiant** [VCVRack/community#592]
https://github.com/gluethegiant/gtg-rack

**Comment by gluethegiant** [comment]
Added a couple of minor improvements and bumped to 1.0.1. (Starting work on new modules so these should be stable now.)

**Comment by cschol** [comment]
Since it has not been built yet, I integrated this fix as version 1.0.0. Next time you need to update the version in `plugin.json`.

**Comment by gluethegiant** [comment]
Perfect. I just changed my release notes back to 1.0.0 and my git tag to not confuse users. Thank you!

**Comment by gluethegiant** [comment]
Plugins updated to 1.0.1.
commit 0029836fb0b6816e76c3e598aec96bdbf99d0277

**Comment by gluethegiant** [comment]
Plugin updated to 1.0.2
commit 1e99fc1192c4432cb5cae1c4c58f6a864e896bf9

**Comment by gluethegiant** [comment]
Just wrote a User's Guide (manual) with examples and a tutorial that uses mix group features newly available in this release. Thanks in advance!

commit 5fbe74cc4e5fe58277dea0091e1caaf0481274ce

**Comment by gluethegiant** [comment]
commit 21b4d3bcba7cbc3df6c0531337ad9802dfec594f
A Halloween release with a new Night Ride theme (and exp fade, optional CV input filters, etc). Thanks!

**Comment by gluethegiant** [comment]
The Audition Release 1.0.5. Thanks!

commit 361bc56b7245ce8d28200c1a253dda34d7f01f70

**Comment by gluethegiant** [comment]
Oh my, an even quicker release cycle, but I need to fix a bug (a knob with a glitch). Thank you all again! Only a couple more releases and then I'll get busy with music and slow down my development.

commit ab01f6b5b290c21c760a9ea1f31556520557f5c4

**Comment by gluethegiant** [comment]
The Solo Release:
commit 6a6227eaa406c0aec5b0c4709809afae84b01ea5

**Comment by gluethegiant** [comment]
Time to make some music! These are now 1.1.0. Thanks!
commit d24848c03d0a0cd98fcb0dae92a2e62cb597f9a2

**Comment by gluethegiant** [comment]
While optimizing, I accidentally made vu meters too insensitive. Noticed while making music. If this build gets in, I'll adjust the tags on my end as this should be the 1.1.0.
commit 084654d3d30907af9a20bfd8f4c7b43d47e6d60c

**Comment by gluethegiant** [comment]
Fixes and improvements:

commit 69433fdd15855cc789b508a9312b0832ba3fe72f

**Comment by gluethegiant** [comment]
Fixed bug when saving defaults and upped to v 1.1.2:
commit 1734a4c904bb79b1a4f2939388eef1d718a32b2f

**Comment by gluethegiant** [comment]
Updated with vu meters that won't die after infinities and NANs, reworked context menus, and a new panel theme setting:
commit be55cf1058ae9bcb28456ef8e1615cc49227feed

**Comment by gluethegiant** [comment]
Updated for v2 commit 54fed7f78bbaac1f1d6275aa737acc39aebc6e72

**Comment by AndrewBelt** [comment]
I'm unable to build this for Mac ARM64 using Rack SDK 2.4.0 because of a name clash with `ThemedSvgPort` and `ThemedSvgScrew`. An easy fix is to rename those classes, or use namespacing, and request an update.

**Comment by cschol** [comment]
Build failure with latest Rack SDK 2.4.0: https://github.com/gluethegiant/gtg-rack/issues/13

**Comment by gluethegiant** [comment]
Release 2.0.2. Updated for build with SDK 2.4+. Commit: 3266554
