### ISSUE TITLE
vitamin

### ISSUE THREAD

**Issue by xaviershay** [VCVRack/community#593]
Hello! I'd like to add my modules to the library:

https://github.com/xaviershay/vitamin-vcv-modules

This is my first contribution, hopefully I've done everything right. Was motivated to make them because I wasn't able to find the polyphonic modules I wanted use with my synth.

Thank you :heart:

**Comment by AndrewBelt** [comment]
Sorry, I have no idea why this plugin didn't go through the build script yesterday. Should be live now.

**Comment by xaviershay** [comment]
New release 1.0.1. Fixes a memory corruption bug.

Commit: [ee5ec5634403ea8d752968dafe404111366faa9f](https://github.com/xaviershay/vitamin-vcv-modules/commit/ee5ec5634403ea8d752968dafe404111366faa9f)

:pray:

**Comment by xaviershay** [comment]
New release 2.0.1. Rack 2 compat. Sorry took me a bit to get sorted.

Commit: [8e822066a72a671ca7c603daad0a558a9fcb58ad](https://github.com/xaviershay/vitamin-vcv-modules/commit/8e822066a72a671ca7c603daad0a558a9fcb58ad)

Thanks 🙏
