### ISSUE TITLE
luckyxxl

### ISSUE THREAD

**Issue by luckyxxl** [VCVRack/community#596]
Hi,

I finally upgraded my plugin to the v1-API.

code: https://github.com/luckyxxl/vcv_luckyxxl
commit: 56a83c74cda95dc445364138150424dc5895d1fa

Thanks :)

**Comment by cschol** [comment]
The GitHub URL for this project is invalid and the submodule has been removed from the library repository. Please resubmit a valid URL for this plugin in this thread and we will re-add the plugin. Note, that this does not affect availability of existing binaries of the plugin via the VCV Rack Plugin Manager.

**Comment by luckyxxl** [comment]
Indeed I recently deleted the code for my plugin from github. I didn't remember that this repository still linked to that, sorry for that. However, I haven't figured out an alternative host for the code so far, so the code is no longer available from my side for now. As I don't intend to continue working on the plugin, you may want to consider removing it completely :)
