### ISSUE TITLE
ChordController

### ISSUE THREAD

**Issue by wilsontr** [VCVRack/community#598]
Hi, first-timer here. 

Version: 1.0.0
Commit: 6517d5b5a57b8908dc8bf62d443814e393dcc52f
License: MIT
Manifest: https://github.com/wilsontr/ChordController

Thanks!

**Comment by cschol** [comment]
Your plugin has been integrated in the Plugin Manager. It will be made available for all supported platforms on the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the VCV Rack community!
