### ISSUE TITLE
LifeFormModular

### ISSUE THREAD

**Issue by TimeControlledOrganism** [VCVRack/community#599]
Hello 
Made a few plugs because I like too much the soft and I have to learn "code"
I'd like to share them , hoping they are working correctly, they build OK on win10
source : 
https://github.com/TimeControlledOrganism/LifeFormModular
thx for your time!

**Comment by AndrewBelt** [comment]
Those panel files are quite large. Can to try to optimize those down to a normal size? Something like 100kb is normal.

**Comment by TimeControlledOrganism** [comment]
OK, thx Andrew, didn't noticed, I used an illustrator effect on labels for pseudo 3D, deleted it on all panels.
Panel size is normal now.
Again thanks Andrew for your time and for the software.


    Le mardi 24 septembre 2019 à 14:50:53 UTC+2, Andrew Belt <notifications@github.com> a écrit :  
 
 
Those panel files are quite large. Can to try to optimize those down to a normal size? Something like 100kb is normal.

**Comment by TimeControlledOrganism** [comment]
Hello 
Updated to V 1.0.1
latest commit hash : 0a9a0e344a118cddba55f50c6a742bfaef4848be 
I hope it's ok 
thx

**Comment by TimeControlledOrganism** [comment]
Sorry found a bug in  Pitch Integrator
latest commit : acaad22cda5b8c28fd856f5e3381f825d17bb30c
thx

**Comment by TimeControlledOrganism** [comment]
Sorry forgot to update version number 
please use this commit : b0b11e7f5e6fdecd64c66395796c5cfca4bb0243
THX

**Comment by cschol** [comment]
Module defined in `plugin.json` but not in source code: https://github.com/TimeControlledOrganism/LifeFormModular/issues/3

**Comment by TimeControlledOrganism** [comment]
Argh sorry
latest commit : d0cb4928b264d24727aabe42a75222ef09b61bf0
thx a lot

**Comment by TimeControlledOrganism** [comment]
Hello I'm updating to 1.1 with a new osc and a cv utility ! 
Hope everything works !
Thx as always!
Latest commit : e05ede491eb99914371e0b0c42664c460b35527d

**Comment by TimeControlledOrganism** [comment]
Hello 
Made a V2 branch
hope it works 
d1673014007bab2a17c74e1b061905bdc780f09d
Thanx a lot
