### ISSUE TITLE
Mental Modules Updated for Version 1

### ISSUE THREAD

**Issue by Strum** [VCVRack/community#600]
Ok, so I've finally got the mental modules ready to go for a release.
still work to do but i'll add that to further updates, they are working as they were before the upgrade now at least.

check the code and let me know if anything needs changing.

https://github.com/Strum/Strums_Mental_VCV_Modules

Cheers

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/Strum/Strums_Mental_VCV_Modules/issues/45

**Comment by cschol** [comment]
Please re-use issue #458 for this plugin.
