### ISSUE TITLE
TercerBrazo

### ISSUE THREAD

**Issue by diegodorado** [VCVRack/community#601]
TercerBrazo has been tested on linux only. First time working with VCV (and it's great!)

TercerBrazo - version: 1.0.0
git: https://github.com/diegodorado/TercerBrazo
commit hash: d59d8ed50ad1fe0c4bb658bb8586935e308e21f5

**Comment by cschol** [comment]
Module is not defined in .cpp: https://github.com/diegodorado/TercerBrazo/issues/1

**Comment by diegodorado** [comment]
just updated module definition to match plugin.json
commint hash :  2fe16827182e16bfd8fbf0f922a9e858e2bc9e4c

**Comment by cschol** [comment]
Thank you for the update. Your plugin has been integrated in the Library repository and binaries for all supported platforms will be available in the Plugin Manager with the next build update. Please use **this** issue to notify us of updates for your plugin. We will reopen it. Thank you for providing your plugin to the VCV Rack community!

**Comment by diegodorado** [comment]
Great!

**Comment by diegodorado** [comment]
I have pushed an update to this plugin.

TercerBrazo - version: 1.0.1
git: https://github.com/diegodorado/TercerBrazo
commit hash: bfadfb5b3a2f5c7fa6c84fdda3ba3753360a3c49

**Comment by AndrewBelt** [comment]
This is really cool. In college I built a controller for a YM2612 torn out of a Sega Genesis that supported MIDI and MIDI CC for controlling the chip registers.

**Comment by diegodorado** [comment]
Thanks! I 've also made a MIDI controllable synth out of an ym2612 chip some years ago.... and now we are releasing and eurorack module out of it!
Here's a demo of the first expermients with it: https://www.youtube.com/watch?v=pZgkEBuqn0s&t=591s

Indeed, I made this VCVRack module so people can have a taste of what can be achive with this chip in an eurorack environement.

It is very rough right now, but I will publish the updates of this module here:
https://diegodorado.com/es/works/cv2612/

**Comment by diegodorado** [comment]
Pushed another update to this plugin, which adds a custom widget to view which algorithm is selected.

TercerBrazo - version: 1.0.2
git: https://github.com/diegodorado/TercerBrazo
commit hash: 55cc0d51e537b61288968d1dba1212d935171336

**Comment by diegodorado** [comment]
Another update: fixes a bug with AM not working.

TercerBrazo - version: 1.0.3
git: https://github.com/diegodorado/TercerBrazo
commit hash: d6797cd4c63eded9b3b99c495c9adfa93372071d
