### ISSUE TITLE
Nozoid

### ISSUE THREAD

**Issue by ch-nry** [VCVRack/community#602]
This is a request to add nozori modules to VCV library :
url : https://github.com/ch-nry/VCV_nozori

thanks

**Comment by ch-nry** [comment]
This modules are clone of nozori modules by nozoïd.
They are based on the modules firmware to provide the same sound. 
Since the hardware run at fixed sampling rate, the emulation must run at the same frequency for best result. For other sampling rate, a message is display on the module but you can still use it.
Since I'm the author of both original hardware and clone, there is no copyright conflict.

**Comment by cschol** [comment]
You could maybe implement an automatic samplerate conversion? Take a look at the [AudibleInstruments](https://github.com/VCVRack/AudibleInstruments) modules. Some of them implement this.

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/ch-nry/VCV_nozori/issues/1

**Comment by ch-nry** [comment]
Since this emulation are demo of the hardware, it's important for me that they have the same sound : a sample conversion will change the sound quality : I want to avoid it.
The module can still run at other sampling rate, I just warn the user that it's not optimal.

**Comment by ch-nry** [comment]
increase version number with commit : f6dc57e66cb62020947305ca2fe9e8206fc89bc0

**Comment by ch-nry** [comment]
new version to reflect minor fix : 3390d2ad884618fad324d4fe248921654e33d90c

**Comment by ch-nry** [comment]
new version that remove the warning after few seconds : 88483049ea016d2b1dc38a88f160d98373d38ff4

**Comment by cschol** [comment]
Before I add this: are the plugins called "Nozoid" (that's the slug) or "Nozori"?

**Comment by ch-nry** [comment]
Nozoïd is the brand name. there was a pb with ï, so I put nozoid.
For now, I port only 1 module to VCV : the nozori 68. I'll port the nozori 84 as soon as I have more time. In a more distant future, I'll probably create more hardware, so more module may come. This is why I regroup this nozori module under the nozoid brand.
is that OK?

**Comment by ch-nry** [comment]
Thanks!

**Comment by ch-nry** [comment]
I made an update and include all nozori 84 modules. This update also include minor modifications.
With commit : 73c84730ff22ea237cdc26e8c4a0c06ca5851771 the version number is now 1.1.2

**Comment by ch-nry** [comment]
Thanks to Andrew suggestion, I add tags and description to all module.
with commit 1dca966052118429164c576219842ed7b4a56731, theversion number is now 1.1.3

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/ch-nry/VCV_nozori/issues/7

**Comment by ch-nry** [comment]
new version (1.1.4) with commit 3775f2e6018c33d6338478acba4448c8893b98c0, to fix this bug : https://github.com/ch-nry/VCV_nozori/issues/8

**Comment by ch-nry** [comment]
new version (1.1.5) with commit d2f1872e6ad6feade50d6bf49403bbaec0d63ed8, to fix a bug : https://github.com/ch-nry/VCV_nozori/issues/6

**Comment by ch-nry** [comment]
new version (1.1.7) to fix a bug: https://github.com/ch-nry/VCV_nozori/issues/11
last commit : a0578a44cff73c61cfb92d1e14c2673a422b817d

**Comment by ch-nry** [comment]
new version (1.1.8) to fix 2 bugs related to variables initialisation (that are not mandatory in the hardware)
https://github.com/ch-nry/VCV_nozori/issues/13
https://github.com/ch-nry/VCV_nozori/issues/14
last commit : 6276602f2d4a8ac21d6428f22434cac06db5d546

**Comment by ch-nry** [comment]
new version (1.1.9) to fix an other bugs related to variables initialisation.
https://github.com/ch-nry/VCV_nozori/issues/15

last commit : 312293c65691a00d100cb38dde98ef845eb0888f

**Comment by ch-nry** [comment]
update to Rack version 2 with this last commit (97cefe3c98d01060446395d4e18f11c4028bb4d4)
