### ISSUE TITLE
JE

### ISSUE THREAD

**Issue by eres-j** [VCVRack/community#605]
https://github.com/eres-j/VCVRack-plugin-JE

**Comment by eres-j** [comment]
1.0.0
5bb543a477332f52ed9c9c51a782d47db3d4f27a

**Comment by cschol** [comment]
Did you compile your plugin against the latest 1.1.5 Rack SDK or `master`?

Please try the 1.1.5 Rack SDK. It does not compile against the SDK for me.

**Comment by eres-j** [comment]
Was on HEAD of master.
It should compile fine with Rack v1.1.5 tag now.
152f95efaf972f2cffa4e2a51b2cca58dcd1fea9

**Comment by AndrewBelt** [comment]
I'm not sure what the previous changes were, but let's stick to using `APP` rather than `rack::APP`. Macros are not namespace-able, so it's best to not pretend they are. My attempt at supporting `rack::APP` was foolish, so switch back to using `APP`, and I'll build this. I now prefer to use the HEAD SDK rather than the last SDK version.

**Comment by cschol** [comment]
The build failure was against 1.1.5 SDK and the issue was `APP`. If you want me to build against the `HEAD` SDK instead of the released SDK that's fine. Let me know and I'll update my build scripts.

**Comment by AndrewBelt** [comment]
@cschol Hmm, I think that would be best. This allows me to fix issues with the API without plugins waiting on the next stable Rack version. I've added an SDK build of a recent commit. https://vcvrack.com/downloads/

**Comment by cschol** [comment]
Thanks. I'll point my build env to that one. Do we still need @eres-j to revert the last commit?

EDIT: Plugins compiles fine with the new SDK against rev 5bb543a.

**Comment by AndrewBelt** [comment]
Sure, @eres-j  should either revert to the code with just `APP` (or manually change them again), or we should just point the submodule at the old commit.

**Comment by cschol** [comment]
OK. I'll hook up the old commit for now and we can update this on the next build update.

**Comment by eres-j** [comment]
Should I revert my last commit?

**Comment by AndrewBelt** [comment]
Yes, revert from `rack::APP` to `APP` etc as that is the working syntax from now on.

**Comment by eres-j** [comment]
89fecee9302ae457ed6f83985486ea860d659dd2
