### ISSUE TITLE
PdArray

### ISSUE THREAD

**Issue by mgunyho** [VCVRack/community#606]
Hello, I'd like to submit two plugins.

Both are in the same repository: https://github.com/mgunyho/vcvrack-plugins

Commit hash: https://github.com/mgunyho/vcvrack-plugins/commit/bb28dcc5832202cbb86d622e5b53b6bb5a9af23b

**Comment by AndrewBelt** [comment]
Could you split this into two repos? The automated build system doesn't support subfolders in repositories.

**Comment by mgunyho** [comment]
Yeah I'll do that. Originally the idea was to put them in the same repo to share some code between the plugins (which I didn't end up doing). I didn't know about git submodules back then.

**Comment by mgunyho** [comment]
Moved them to separate repos. The commit hashes are
https://github.com/mgunyho/Little-Utils/commit/f4ece460f479f3880759430506ed7eddaef8e267
https://github.com/mgunyho/PdArray/commit/430b33d8e062cdf33914c5c84ba532714bac52e0

Sorry about the hassle.

**Comment by cschol** [comment]
PdArray - Mac crosscompile fails: https://github.com/mgunyho/PdArray/issues/1

**Comment by mgunyho** [comment]
The compilation error should be fixed now by
https://github.com/mgunyho/PdArray/commit/bf7d42089c514f601e2a3e15679e3fb2fd3d9266

**Comment by AndrewBelt** [comment]
@cschol I think it's best that we no longer allow lists of plugins in issue threads, because it's not clear which plugins need builds. I've updated the README in this repo and changed this issue title to just PdArray.
@mgunyho Can you open a separate issue for LittleUtils?

**Comment by mgunyho** [comment]
Yeah, sure. I also thought that this could get a bit messy over time. I didn't see anyone else submit two plugins at the same time, but I wanted to try it because it was there in the README.

**Comment by cschol** [comment]
OK. Sounds good.

**Comment by mgunyho** [comment]
Hi, I've updated PdArray to v1.0.2. The commit is
https://github.com/mgunyho/PdArray/commit/d78c5734ceae63a64c08e11cf8609e0cfdef3f72

**Comment by mgunyho** [comment]
Hi, I've released PdArray v1.0.3, commit https://github.com/mgunyho/PdArray/commit/042559b672becdc369722fb465bb0c3fea09516b

**Comment by mgunyho** [comment]
Hi again,

I've updated PdArray to v1.0.4 in commit https://github.com/mgunyho/PdArray/commit/91d1883e79db153e6a93d265f22a03565a02f193

**Comment by mgunyho** [comment]
Hello! I've updated PdArray to v1.0.5 in commit https://github.com/mgunyho/PdArray/commit/da36d4bab7d0027d50890c7fb1a44de47b02d30c

**Comment by mgunyho** [comment]
Hi! PdArray has been updated to v1.0.6, the commit is https://github.com/mgunyho/PdArray/commit/0af99e95cef9674609e8f45c66cff63228212c1a

**Comment by mgunyho** [comment]
Hello,

PdArray has been ported to Rack v2, in version 2.0.6. Commit: https://github.com/mgunyho/PdArray/commit/9075b41435e7020f888cb63c7b136eb6cb365fba

**Comment by mgunyho** [comment]
Hi, I have updated PdArray to version 2.1.0 in https://github.com/mgunyho/PdArray/commit/68795502676e033b67298ba695865a76643e0bb8

**Comment by cschol** [comment]
`plugin.json` needs version update to 2.1.0.

**Comment by mgunyho** [comment]
Woops! I updated it in https://github.com/mgunyho/PdArray/commit/59d4c104b802fc5d6e199b82fc9690ae98078231

**Comment by mgunyho** [comment]
Hi, there is a small bugfix update to PdArray, the commit is 8bd796f40fb77f78c22a8cbbbcf619c389bc9e65

**Comment by cschol** [comment]
Can you please doublecheck that SHA? It doesn't seem to exist in the repo.

**Comment by mgunyho** [comment]
Woops, I forgot to push it, sorry! It should be there now. For convenience, here's a direct link: https://github.com/mgunyho/PdArray/commit/8bd796f40fb77f78c22a8cbbbcf619c389bc9e65
