### ISSUE TITLE
RacketScience

### ISSUE THREAD

**Issue by ContemporaryInsanity** [VCVRack/community#608]
https://github.com/ContemporaryInsanity/RacketScience

**Comment by ContemporaryInsanity** [comment]
1.0.0
0c0bf0c51da85c5fb2a9a249629dce37168e2173

First timer, please be gentle with me, still figuring out github.

**Comment by cschol** [comment]
The binary `plugin.so` is committed to the repository. This needs to be removed from the repository **and the history** (see [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/). Other than that it looks good and builds for all platforms. Thank you.

**Comment by ContemporaryInsanity** [comment]
Ok, thank you, told you I was still figuring out github.  Do you have time to explain to me why it must also be removed from the history and not simply deleted?  If not no worries.

**Comment by AndrewBelt** [comment]
It makes the repo unnecessarily large for everyone, no other reason.

**Comment by ContemporaryInsanity** [comment]
Ok, I followed the BFG instructions to remove all traces of plugin.so (not sure if it worked, not sure how to check), also removed plugin.so from master.  Is that enough?  Sorry I'm so clueless re github.

Fingers crossed.

45ce8f4ff94a646935e8cc79f7af9322649e52cb

**Comment by cschol** [comment]
It is still in the history.

```
git checkout 4b5e69a22da5bcd83574b11bea261efe79e1f100
```

This revision still has the `plugin.so`.

**Comment by ContemporaryInsanity** [comment]
As stated I followed the BFG instructions.  Oh well, I'll zap the entire repo and start again from scratch.

**Comment by ContemporaryInsanity** [comment]
1.0.0
40505bff9fb0631584486e932bf29a152f4098cb

**Comment by cschol** [comment]
Thank you for the update. Not to sound nitpicky, but why is the `boogie.gif` 7MB? Is there any way to reduce that size? It is only used in the `README.md`.

**Comment by ContemporaryInsanity** [comment]
It was what ffmpeg spat out when fed with the mp4 I recorded.  I'll look into it, does it need amendment before my plugin can be included in the library?

**Comment by cschol** [comment]
Here is what I would say: remove the `.gif` like you did with the `plugin.so` until you can find a smaller solution. If this was a component of the plugin it would be different, but it is just eye-candy for the `README.md` and sucks up bandwidth on the build server. I'll add it today if you can make the change.

**Comment by ContemporaryInsanity** [comment]
My attempt to remove plugin.so failed with bfg so I recreated the repository from scratch.  How do I remove the gif to your satisfaction?  Do I just delete it?

**Comment by ContemporaryInsanity** [comment]
Think I've done it, as it was the last to be added.  Once more, apologies for my git cluelessness.

2b3a0508eca0877e72f9d9ddddc229b38fb6c3c4

**Comment by cschol** [comment]
No need to apologize. We have all had our learning curve with git. Thank you for taking care of the requests promptly. Your plugin has now been integrated and will be distributed with the next build update.

**Comment by ContemporaryInsanity** [comment]
Thanks for your assistance.

**Comment by ContemporaryInsanity** [comment]
1.1.0

2bd5e5b98328a3eb913a7bd43008444ca1d26b23

**Comment by ContemporaryInsanity** [comment]
Please put this submission on hold, got an obscure bug somewhere.

**Comment by ContemporaryInsanity** [comment]
Apologies, last minute bug fix.
https://github.com/ContemporaryInsanity/RacketScience
1.1.0
993e567268e8785b059c4a8945776bff23a73e71

Thank you.

**Comment by ContemporaryInsanity** [comment]
FFS I'm an idiot, forgot to remove logging.

04caab44e47d60b3af2a9fae0108e9cc241f31ac

**Comment by ContemporaryInsanity** [comment]
Added Reheat beta

4cde3c55531ed2f64140c640288c98b49d28b43c

**Comment by cschol** [comment]
Compile failure on all platforms: https://github.com/ContemporaryInsanity/RacketScience/issues/1

**Comment by cschol** [comment]
The GitHub URL for this project is invalid and the submodule has been removed from the library repository. Please resubmit a valid URL for this plugin in this thread and we will re-add the plugin. Note, that this does not affect availability of existing binaries of the plugin via the VCV Rack Plugin Manager.
