### ISSUE TITLE
SA-Seasons

### ISSUE THREAD

**Issue by icaroferre** [VCVRack/community#609]
https://github.com/SpektroAudio/Seasons/

**Comment by icaroferre** [comment]
Version: 1.00 
Hash: 2da0ad26e5b9f9bfb996ccbd70eb0ebf41750b1e

**Comment by AndrewBelt** [comment]
`plugin.dylib`, `build`, and `dist` is present in the repo. You probably mistakenly added this. You might want to remove this from git history to save filesize.

Also, do you confirm that your intention is a "source-available" proprietary license? If so, it might be a good idea to put a notice in the README or LICENSE that says "All rights reserved for source code" or something.

**Comment by icaroferre** [comment]
Ah, sorry about that. I've removed the extra files and added the proper License file to the repo as well as the code to the JSON (which should be GNU-GPL-v3).
Here's a new commit: 28f5da5709690401ad08b2457f38594a5423d4c0

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/SpektroAudio/Seasons/issues/2

**Comment by icaroferre** [comment]
Fixed.

Commit hash: 7c412675ae614c128a604ce671466052991120cf
