### ISSUE TITLE
pfzzz

### ISSUE THREAD

**Issue by 0mars** [VCVRack/community#612]
https://github.com/pfzzz/rack-plugin

Hi please add my plugin

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/pfzzz/rack-plugin/issues/2

**Comment by 0mars** [comment]
Issues fixed, v1.0.2, thanks

**Comment by cschol** [comment]
The license ID is invalid (updated same same issue above).

**Comment by 0mars** [comment]
fixed, thanks

**Comment by 0mars** [comment]
Please update to v1.0.4

**Comment by 0mars** [comment]
please update to 1.1.0
