### ISSUE TITLE
NEXSwitches

### ISSUE THREAD

**Issue by lkdjiin** [VCVRack/community#616]
Hello everybody,
Can you please add my plugin to the library?

- Version 1.0.0
- Hash 3490ce11752a2b8ada5fcfe1f8efe0d947dc2bf1

Thanks for all your work on VCV Rack!

**Comment by AndrewBelt** [comment]
What's the source code URL?

**Comment by lkdjiin** [comment]
Sorry for that. The url is https://github.com/lkdjiin/SwitchesModules

**Comment by cschol** [comment]
Your plugin has been integration in the Rack library and will be available in the Plugin Manager for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community!

**Comment by lkdjiin** [comment]
Hello everybody,
A new version is ready:
- version 1.1.1
- https://github.com/lkdjiin/SwitchesModules/commit/6714d7933fc588ae4a395139827b80ed33332f8d

Thank you for all the work!
