### ISSUE TITLE
ReTunesFree

### ISSUE THREAD

**Issue by DominoMarama** [VCVRack/community#618]
Version 1.0.0 of the Retunes Free plugin library submission

source: https://github.com/DominoMarama/ReTunesFree
commit: 66343c5ceaf1fd07b2b06617135f8cdc9c245d87

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next plugin manager update. Please let us know in **this** issue when a new version of the plugin is available. We will reopen it. Thank you for providing your plugin to the Rack community.
