### ISSUE TITLE
AriaSalvatrice

### ISSUE THREAD

**Issue by AriaSalvatrice** [VCVRack/community#619]
Hiya hi, new plugin, only one little module in it, hopefully more soon.

**Source**: https://github.com/AriaSalvatrice/AriaVCVModules
**Commit**: 7687c47e0b3828f9c0ca3c73e63452ddc10818cc

Ok so, fair warning, 24 hours ago I knew nothing about modern C++, using Inkscape, and some aspects of operating git via Github. For my first module, I chose to learn the ropes by doing something both useful and too simple to mess up, and I tried to do everything by the book, so hopefully I haven't overlooked anything, please lemme know if I did anything incorrectly.

**Comment by cschol** [comment]
Compile failure on Mac platform: https://github.com/AriaSalvatrice/AriaVCVModules/issues/1

**Comment by AriaSalvatrice** [comment]
Thanks for letting me know! Have you tried compiling commit 7687c47e0b3828f9c0ca3c73e63452ddc10818cc rather than master? It doesn't use arrays. I haven't really set up branches properly yet (I'm exploring and learning a dozen of things at the same time) and master is super messy currently.

**Comment by cschol** [comment]
Ah, sorry. My bad. That commit you specified above works just fine. Integrating now.

**Comment by cschol** [comment]
Integrated. Please let us know in **this** issue if a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AriaSalvatrice** [comment]
Woof.    
Version 1.1.0 is ready, with a few new modules.    
Commit: 47945750aba97198fbdf66f3bf1cfb605434e499

I have set up git branches now, so it should always be safe to build Master.     
I can't access a mac regularly those days, so unfortunately it has not been tested on OS X for a little while, but I think I fixed the issue preventing it from building.

**Comment by AriaSalvatrice** [comment]
Last minute adjustment made, I suggest building 646dee32bc86336b0ba53730379d152a37236eb4 instead (last current commit).

**Comment by AriaSalvatrice** [comment]
Heyoes.
Version 1.2.0 is ready, with one new module. 
Commit: 5a09d65ef916f7470380b1394ad93011db1a5338

Like before, can't test on OS X, but it's not doing anything unusual.

**Comment by AriaSalvatrice** [comment]
Woof. Hi!
Version 1.3.0 is ready, adding the Arcane series of modules.
Suggested commit to build: 104b5a5ba1a8533b3d1d8f0a2406c48742e8da7a

I will point out a few things about the module's behavior you might prefer to be aware of in advance. I'll try to keep it terse in this issue - see [the docs](https://github.com/AriaSalvatrice/AriaVCVModules#arcane-atout--aleister---todays-fortune-) to understand why the module has good reasons to do what I'm informing you it does. 

- All 3 new modules connect to the internet. They do not connect sneakily, but overtly, as when offline, they do nothing. In general, only one instance will connect per day, and fetch a tiny file from a github repo acting as a server.
- a daily ~500 byte JSON file is downloaded to `RackFolder/AriaSalvatrice/Arcane/YYYY-MM-DD.json` if the modules are used on that day. Those files are never pruned, as advanced users will want to edit them. Even after years of use, the module won't even store a few MB of data.
- You can view all the possible random faceplates in `/res/arcane`.

**Comment by AndrewBelt** [comment]
>All 3 new modules connect to the internet

Yeah, that's fine as long as they don't connect on load (`init()`) but lazily when the user adds a module to the rack.

**Comment by cschol** [comment]
> > All 3 new modules connect to the internet
> 
> Yeah, that's fine as long as they don't connect on load (`init()`) but lazily when the user adds a module to the rack.

Looks like the modules download their resources in the constructor of the module class (`ArcaneBase`). What's the correct facility to load lazily?

**Comment by AriaSalvatrice** [comment]
The connection only happens once added to the rack, in a detached thread to avoid hanging the audio engine

**Comment by cschol** [comment]
OK. Sorry, I misread that. It works as expected.

**Comment by AriaSalvatrice** [comment]
Woof,
Version 1.4.0 is here, one new module, nothing tricky this time. 
Suggested commit: f88c8ebba9e80716bcc5c3e5b4a63fd7b5f78db8
Byes

**Comment by AriaSalvatrice** [comment]
Hello, heyo hi,
~~Version 1.4.1 is here. Big update to Darius, some fixes, no new modules. 
a6f7ac70fb4efba6f101b5dcc5196623f5ba7a37~~
Byes!

**Comment by AriaSalvatrice** [comment]
Hello hi,
Pushed another little update, 1.4.2. Please build this one instead of 1.4.1!
52c7a2e54583d5df5d60ceba3375c524b5b6ee6f
If it gives you trouble for some unexpected reason, please build 1.4.1 instead from the previous post.

**Comment by AriaSalvatrice** [comment]
Woof,
Here's version 1.5.0, with a new series of modules.

With this collection of modules evolving from being a series of quick hacks to something more ambitious, it was relicensed from WTFPL to GPL-3.0-only. The change is reflected in the plugin.json. I assume your library system will pick it up automatically.

Magic glyph: 
5e869b60a8a74d8bccafefdd73fa9d93f9bb5b96

Thanks!

**Comment by cschol** [comment]
Build failure on multiple platforms: https://github.com/AriaSalvatrice/AriaVCVModules/issues/46

**Comment by AriaSalvatrice** [comment]
I know we haven't solved yet the build issues with OsxCross and QuickJs yet, but in the meantime, if you discover an easy fix, here's another stable version:

* 1.5.1
* 90e3e953e8108d04d3b49724dd9bd751df3183e6

**Comment by AriaSalvatrice** [comment]
Hello, still nothing on the OsxCross front, but a new version is ready, with 3 new modules:

- 1.6.0
- 933a1a6efae2ca350c3f7a886b06dc2f711b9373

**Comment by AriaSalvatrice** [comment]
Thanks a lot for figuring out QuickJS integration! Hopefully this will open the door to new useful modules.

Here's a revised version that pulls the proper commit of @JerrySievert's fork of QuickJS, along with a few bugfixes. It builds properly on my machine and Azure cross-platform both.

- 1.6.1
- bd2b32339f01924e22206feb412a227321ca13bf

**Comment by AriaSalvatrice** [comment]
Thanks for the PR - new commit with your makefile changes: 

02741337c9d41ea36a1fded23fc7783918fec7df

**Comment by AriaSalvatrice** [comment]
Hello hi, new version, very simple new modules, but a thing to note:

I tentatively accepted a patch to the Makefile to make it easier to build on the Sonaremin: 
https://github.com/AriaSalvatrice/AriaVCVModules/issues/61

If it breaks the library, then please don't even bother for a second figuring out what's wrong, I'll just revert to the old version that works fine and let the Sonaremin project maintain a compatibility patch against my project. 

* Version 1.7.0
* Cool numbers: f286f3915e374e8445ea7e68e4045c3db31af72d

**Comment by AriaSalvatrice** [comment]
Woof, hi, here's a new version with a bunch of small fixes.

- Version 1.7.1
- Magic word: 22574e96f0fe0065b1f62aa3aef38f770dceae2b

**Comment by AriaSalvatrice** [comment]
Please let me know if there's any issue, I see it's missed a few rounds of builds. I know there's a lot of changes in the diff, but most are extremely trivial - just not letting technical debt accumulate in the code to keep it maintainable, plus bulk changes in a lot svg files for design language consistency.

**Comment by AndrewBelt** [comment]
According to @cschol, building this requires LLVM gold in the Mac cross-compiler because of QuickJS. We've added LLVM gold to the Mac toolchain build in https://github.com/VCVRack/rack-plugin-toolchain, so we are making progress on this build.

**Comment by AriaSalvatrice** [comment]
Heyo hi, here's a new module, hopefully I will manage not to entirely break the build system yet again. Once again there are a lot of trivial bulk change diffs to review, trying to keep the code clean as it grows, thanks for understanding.

- Version: 1.8.0
- Secret glyph: ab0051ebaf631b97f1340c47359cff29c8ad8347

**Comment by AriaSalvatrice** [comment]
Sneaking in a last minute fix if you don't mind! Thanks.

- 1.8.1
- 6db2f4ab46de3efb7b9da1ec1024f01a6d90cd18
