### ISSUE TITLE
AuntyLangtonsFree

### ISSUE THREAD

**Issue by 64MM4-KN1F3** [VCVRack/community#620]
**EDIT 2023**

FYI - Have migrated this to V2. See: https://github.com/VCVRack/library/issues/620

**New repo here:** https://github.com/64MM4-KN1F3/AuntyLangtons-FREE-V2
**Version:** 2.0.0
**Commit Hash:** 41056cc9b3ee5442fc1ed00a0628d68cb7f70add

--------------------------
Source: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE
Version: 1.0.0
Commit Hash: dd2cebadea808b3e6a5d7f2606c9a89b9fce624f

Cheers. (fingers crossed)

**Comment by cschol** [comment]
Invalid license in `plugin.json`: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE/issues/1

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all platforms with the next plugin manager update. Please use **this** issue to let us know about updates to the plugin. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by 64MM4-KN1F3** [comment]
Hi guys. Minor updates. 
Version: 1.0.1
Commit Hash: 4a3c3433e1077b021849aff23f128d3587c00c60

**Comment by 64MM4-KN1F3** [comment]
Hi VCV Rack folks, I finally got around to upgrading this little one to V2.

New repo here: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE-V2
Version: 2.0.0
Commit Hash: 41056cc9b3ee5442fc1ed00a0628d68cb7f70add

Do let me know if there are any issues.

**Comment by cschol** [comment]
Invalid URL in manifest file: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE-V2/issues/2
Error loading fonts: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE-V2/issues/3

**Comment by 64MM4-KN1F3** [comment]
Hi @cschol - Have addressed these issues I think:
Repo: https://github.com/64MM4-KN1F3/AuntyLangtons-FREE-V2
Version: 2.0.1
Commit Hash: e8f4c7a95636fd286e4f3db08d58c3bcb6dfc9f7
