### ISSUE TITLE
Slug

### ISSUE THREAD

**Issue by josbouten** [VCVRack/community#621]
I'm not sure the discussion we had about the slug (have a look at the start of this thread) lead to the result I thought it would have, see issue 515. And I must admit I only just discovered this. I build a vocoder called Vocode-O-Matic and chose as a slug Sculpt-O-Sound. However, in the library I do not find the plugin under Sculpt-O-Sound, but under Vocode-O-Matic. I compares my slug.json with the one from mscHack and I think the slug name and module names are in accordance with what I found with mscHack, however I do not see this reflected in the plugin name in the vcvrack library. Can you please enlighten me? I'm planning on adding more modules, so the name Vocode-O-Matic would not be appropriate for the set as a whole.

**Comment by AndrewBelt** [comment]
Moving discussion to https://github.com/VCVRack/library/issues/515
