### ISSUE TITLE
Kosmodules-Free

### ISSUE THREAD

**Issue by calvinkosmatka** [VCVRack/community#622]
Kosmodules-Free is ready for review

URL:  https://github.com/calvinkosmatka/Kosmodules-Free
Branch: v1.0
Commit: bb01590dfc29f4c80e16c9fbf3cc6af868ddd9e4

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available for all supported platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version of your plugin is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by calvinkosmatka** [comment]
Updated plugin.json

Commit: 909297690addc31692599cd5a02dbb6011d55af6

**Comment by AndrewBelt** [comment]
The version number needs to be bumped to generate a new package.

**Comment by calvinkosmatka** [comment]
Added version bump

Commit: 76ef163882294f2be86c348b0b1c3e4590e8cfe8
