### ISSUE TITLE
Sckitam

### ISSUE THREAD

**Issue by philippesalembier** [VCVRack/community#623]
Hi, 
I have developed a few tools for VCV I would like to share with people. Here is the github
https://github.com/philippesalembier/SckitamVCV

As this is the very first time I am doing this, please let me know if I have overlooked any issue.

Thanks a lot in advance,

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available for all supported platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version of your plugin is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by philippesalembier** [comment]
Hi,
Version 1.0.1 of the plugin is available. 
https://github.com/philippesalembier/SckitamVCV
Let me know if there is any issue. 
Thanks a lot for your work!

**Comment by cschol** [comment]
Please specify the git SHA of the version to be released. Thank you!

**Comment by philippesalembier** [comment]
Sorry for overlooking this point. The commit is the last one: 
0154cc17e7729524afc4db027527c80e5b30e194
Thanks.

**Comment by philippesalembier** [comment]
Hi, 

A new version of the plugin, adding support for polyphony and dark/light panels, is available at
https://github.com/philippesalembier/SckitamVCV
commit: 53a417ac4129c1e0c1e7072bee5870b729f1f555

Thanks in advance,

**Comment by philippesalembier** [comment]
Hello, 

Here is an update improving the aliasing reduction on the Polygonal VCO for high teeth values.
https://github.com/philippesalembier/SckitamVCV
commit: a131d3790e650b03c3159330bc66593475d4c58f

Thanks a lot!

**Comment by philippesalembier** [comment]
Sorry, I forgot to update the version number in the json file. It is done now
commit: 7fc017ef5c3cfb6a4a29d9e9f9bca60dc687b0a3
Thanks

**Comment by philippesalembier** [comment]
Sorry again. I have found an issue in the VCO. I need some time to figure out what is going on. 
Please ignore the whole request to update this version. I will contact you when the issue is solved.

**Comment by philippesalembier** [comment]
Hi, 

I have found the issue. So I think this is ready for inclusion in the library 
https://github.com/philippesalembier/SckitamVCV
commit: 7f62d0bae977d689fd77ae4f700c7e4aedb18145

Thanks a lot!

**Comment by philippesalembier** [comment]
Hi, 

Here is a small update to address some GUI update on the Markov Sequencer and some tags/module descriptions for the new library. 

https://github.com/philippesalembier/SckitamVCV
commit: e7415744eaa20671041a49106f396d3c08ff30dc

Thanks a lot.

**Comment by philippesalembier** [comment]
Hi,

Here is an update to introduce a new module to experiment with digital waveguide & Karplus-Strong synthesis as well as flanger or chorus.

https://github.com/philippesalembier/SckitamVCV
commit: 15f0075418ce90b67a8d758527fab14dce81ca84

Thanks a lot.

**Comment by philippesalembier** [comment]
Hello, 

Here is the update for V2.
https://github.com/philippesalembier/SckitamVCV
commit: c13da8df5153a1b552266db9251137a0a64bc873

Best regards... and congratulations for this achievement!

**Comment by philippesalembier** [comment]
Hi
Here is an update (v2.0.1) corresponding to the implementation of bypass.  
https://github.com/philippesalembier/SckitamVCV
commit: 5bf0ca542be9fe010a53a30a4b6e2e28770d690d

Thanks for the great work!
Best regards
