### ISSUE TITLE
LabSeven VCO3340 is now ported to Rack 1.x

### ISSUE THREAD

**Issue by LabSevenDevVCVRack** [VCVRack/community#625]
Hi VCV Rack team!

Thanks to @netboy3, the LabSeven VCO3340 module is now ported to Rack 1.x.
commit b96fd203fdbe73aa9bd87341f8153ac177ed76c3

I think the procedure was to create an issue here and include the commit id (my apologies if I was supposed to do something else). Thanks!

Cheers,
Gernot

**Comment by cschol** [comment]
Please use #537 for version announcements for this plugin.
