### ISSUE TITLE
AaronStatic

### ISSUE THREAD

**Issue by aaronstatic** [VCVRack/community#627]
AaronStatic is ready for review

URL: https://github.com/aaronstatic/AaronStatic_modules
Branch: v1.0
Commit: b96fad1efa892cbb312fdc2f5913f2a89f2e3a89

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available for all supported platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community!

**Comment by aaronstatic** [comment]
New update:

v1.0.1
commit hash 27d0c9bf62bf2165e238051f8699e1ea0b60f09b

**Comment by aaronstatic** [comment]
v2.0.0

commit hash 4ace0a1789c577ee4eb12dc03da5271f80598d62

**Comment by aaronstatic** [comment]
v2.0.1
commit hash 958b60c6f7f41af4a14a30ce3e93a039bb4d2f2b
