### ISSUE TITLE
Can't git clone / submodule pb

### ISSUE THREAD

**Issue by ycollet** [VCVRack/community#629]
I tried to clone library repo from v1 branch.
When I do the git submodule update, the following error message is printed:
```
error: Le serveur n'autorise pas de requête pour l'objet c8beb50de1bbdd4d8129ad84e6c04ebd856980d2 non annoncé
Chemin de sous-module 'repos/Ahornberg' récupéré, mais il ne contenait pas c8beb50de1bbdd4d8129ad84e6c04ebd856980d2. La récupération directe de ce commit a échoué.
```

**Comment by cschol** [comment]
Is this reproducible? Could it be a network connection error while cloning?

**Comment by cschol** [comment]
Let us know if this is still a problem and we will reopen this issue.

**Comment by ycollet** [comment]
The problem seems to be fixed now.
I think it was a submodule conf problem on the library repo.
