### ISSUE TITLE
ILovePerlin

### ISSUE THREAD

**Issue by digitalhappens** [VCVRack/community#630]
Dear VCV Library maintainers
here is a plugin I developmed for vcv rack and I'd like to share it:

https://github.com/digitalhappens/ILovePerlin/tree/ilp100

Tested on Linux

**Comment by cschol** [comment]
Unable to build: https://github.com/digitalhappens/ILovePerlin/issues/1

**Comment by digitalhappens** [comment]
sorry, I've uploaded the Makefile, now it can go on...

**Comment by cschol** [comment]
Thanks. Your plugin has been integrated in the library repository and will be available with the next Plugin Manager update for all supported platforms. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
