### ISSUE TITLE
Mog

### ISSUE THREAD

**Issue by JustMog** [VCVRack/community#631]
hello there. new plugin - https://github.com/JustMog/Mog-VCV
ver 1.0.0
commit c661895bb9a92a89de991fcc8f0d93b0dabc2825
thanks!

**Comment by cschol** [comment]
Invalid license ID in `plugin.json`: https://github.com/JustMog/Mog-VCV/issues/2

**Comment by fractalgee** [comment]
is this the MOG I met at Superbooth 2019 in Berlin and talked to several
times over the 3 days?

**Comment by cschol** [comment]
@fractalgee Please move private discussions to the author's repository.

**Comment by fractalgee** [comment]
@cschol, okidoki and sorry if any feathers ruffled....

**Comment by cschol** [comment]
@fractalgee no featers ruffled, but I get notifications of updates from Github that I have to check. Thanks.

**Comment by JustMog** [comment]
> 
> 
> Invalid license ID in `plugin.json`: [JustMog/Mog-VCV#2](https://github.com/JustMog/Mog-VCV/issues/2)

seems to just be a capitalisation issue? fixed in commit 49c2a9c2a8fca0af31e9aa828cc1d771cf026cfb

**Comment by cschol** [comment]
Your plugin has been integrated in the library and will be available for all platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version of the plugin is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by JustMog** [comment]
Hello again. Another module:
ver 1.1.0
commit 05e48129140ca22442e78dda3e93b7b92d7dfb0c
thanks again!

**Comment by cschol** [comment]
OK. I think we need to look at something: the `network_demo.gif` in the repo is now ~12MB. If this is updated with every release of another module (or because of some other cosmetic update), the repo will grow in size by that much every time. Can you please try to reduce the size of the `.gif`? The build server does not have unlimited bandwidth and we should try to keep the repository size down. Thanks.

**Comment by AndrewBelt** [comment]
You should also be aware that GIF for animation is possibly the worst/naive format that exists. You take the 8-bit indexed color buffer of each frame, or the diff of the frame from the last frame (which is going to be an entire frame if all pixel values are changed), and then you losslessly compress it with LZW compression. Even for 1985 standards, this is horrible compression for both images and video. State of the art video formats are on the order of 100 times more efficient.

**Comment by JustMog** [comment]
understood. i'll look into alternatives. i suppose theoretically i could even use a separate repo for the documentation? (this is all the .gifs are used for)
i'm new to git, do i understand you correctly that gif files from previous obsolete commits still contribute to the size? I'm not sure how i would go about solving that

**Comment by JustMog** [comment]
okay, i'm now storing the doc images in a separate repo and have removed all traces of them from the main one as best i can. Let me know if this solves the issue. 
commit: 97e21f678c5360797239c6e74b5db6362cd20f38

**Comment by cschol** [comment]
Looks good. Thank you for taking care of that.

**Comment by JustMog** [comment]
just a bugfix. dunno how serious trying to read the param after the last one that actually exists is but it doesn't do that any more. thanks
ver 1.1.1
commit 6f6c6b27f211bc0e09ef6acf32ff3393d28f6dcf
