### ISSUE TITLE
HamptonHarmonics

### ISSUE THREAD

**Issue by shampto3** [VCVRack/community#633]
```
{
  "slug": "HamptonHarmonics",
  "name": "Hampton Harmonics",
  "version": "1.0.0",
  "license": "MIT",
  "brand": "Hampton Harmonics",
  "author": "Scott Hampton",
  "authorEmail": "",
  "authorUrl": "https://gitlab.com/shampton",
  "pluginUrl": "https://gitlab.com/hampton-harmonics/hampton-harmonics-modules",
  "manualUrl": "https://gitlab.com/hampton-harmonics/hampton-harmonics-modules/-/blob/master/README.md",
  "sourceUrl": "https://gitlab.com/hampton-harmonics/hampton-harmonics-modules",
  "donateUrl": "",
  "changelogUrl": "https://gitlab.com/hampton-harmonics/hampton-harmonics-modules/-/commits/master",
  "modules": [
    {
      "slug": "Progress",
      "name": "Progress",
      "description": "Polyphonic Chord Sequencer",
      "tags": [
        "sequencer",
        "poly"
      ]
    }
  ]
}
```

Source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
Commit: fe377c5d2bae414de09e78643a146c312ed14104

Contains my first VCV Rack module. Excited to make more! Thanks for making such an awesome product and community.

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by shampto3** [comment]
I have a fix update:
- Fixes the `plugin.json` file to contain the URLs (I had forgotten to commit the changes I had made)
- Added descriptive tooltips to the knob params.

Version 1.0.1

Source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
Commit: dc1f19792fe62366b3c4a6b3ef48b7d73803d87c

**Comment by shampto3** [comment]
I have a version update:
- Fixes a gate length issue
- Fixes a poly channel issue on the C4 major chord
- General refactoring

Version 1.0.3

Source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
Commit: f106144fa1c4d6faa7778aafb370e511118275d5

**Comment by shampto3** [comment]
Actually, I would like to update to a newer version. I've finished a new module, and would like to include it in this update.

- New Arpeggiator `Arp` module

Version 1.2.0

Source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
Commit: ee4bb11908e70d7dd145d08f094dcd5dca4a8884

**Comment by shampto3** [comment]
I have a version update:

- Adds an EOC output to `Progress` module
- Adjusts the gate length in `Progress` to trigger a new envelope in each step

Version 1.3.0

Source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
Commit: 3a60f2177d5acffe902f3512b28b2cbf8b36e7b0

**Comment by shampto3** [comment]
Update to the ARP module (new CV input and menu setting for poly output)

source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
sha: b9f6d7ef78b67ae627166197df40679cdeef22dd
branch: master
version 1.4.0

**Comment by shampto3** [comment]
Update to v2.0.0

source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
sha: e34d023774f692cd8da156971ce208327d6e7cda
branch: master
version: 2.0.0

**Comment by cschol** [comment]
@shampto3 The `Progress` module caches font references across frames and causes a crash in the VST.

```
src/Progress.cpp

323-    box.pos = pos.minus(size.div(2));
324-    this->_module = module;
325-    this->_index = index;
326:    this->_font = APP->window->loadFont(asset::plugin(pluginInstance, "res/PixelOperator.ttf"));
327-};

```

Can you please take a look at fixing that per the [migration guide](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames)?

**Comment by shampto3** [comment]
Update to v2.0.1

Fixes [the font reference error.](https://github.com/VCVRack/library/issues/633#issuecomment-1030522032)

source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
sha: e5cf81f1c356fdc98fd08584146cda8af7e16b1f
branch: master
version: 2.0.1

**Comment by shampto3** [comment]
Updated to v2.0.2

Fixes some issues regarding how the Arp module was handling the reset and gate inputs.

source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
sha: 7db5ef91d611d3da1e1552ee0d329d803db3b1fe
branch: master
version: 2.0.2

**Comment by shampto3** [comment]
Updated to v2.0.3

Fixes the Progress module having sus2 and sus4 chords swapped. Fixes an issue with polyphonic gates sticking in the Arp module.

source code URL: https://gitlab.com/hampton-harmonics/hampton-harmonics-modules
sha: 608ba60463d9132aab09dc1a681e676e742b4deb
branch: master
version: 2.0.3
