### ISSUE TITLE
ED9M

### ISSUE THREAD

**Issue by ed9m** [VCVRack/community#635]
Plugin for Ableton Push 2

https://github.com/ed9m/ed9m_vcv

**Comment by cschol** [comment]
Invalid tags in `plugin.json`: https://github.com/ed9m/ed9m_vcv/issues/1
Build fails for all platforms: https://github.com/ed9m/ed9m_vcv/issues/2

**Comment by cschol** [comment]
@ed9m I am closing this issue. Let us know in **this** issue when a fixed version of the plugin is available. We will reopen it.
