### ISSUE TITLE
FV-1emu

### ISSUE THREAD

**Issue by eh2k** [VCVRack/community#636]
https://github.com/eh2k/fv1-emu

This is the Port to VCV V.1 from 0.6.
The slug was changes to "FV-1emu" from "EH_modules".

Thank you, for adding to the VCV Library!

**Comment by cschol** [comment]
Unfortunately, we do not allow slug changes to plugins (top-level slug) or modules (individual slug) as it will break backwards compatibility with older patches.

Also, please re-use the older issue for further updates: #533
