### ISSUE TITLE
MrLumps

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/community#637]
Version 1.0.0 release of MrLumps plugin.
Commit 4f7845cf8261a9c98ccd730c65ed5f688369dabb

Thanks very much for your help!

David Peterson
https://github.com/djpeterso23662/MrLumps

**Comment by cschol** [comment]
Invalid license ID in `plugin.json`: https://github.com/VCVRack/library/issues/637

**Comment by djpeterso23662** [comment]
Commit 9dbafd10ee747fe4f0122e8c4835509adb6d5a95

I hope that fixes the problem.  Thanks again!

David Peterson
https://github.com/djpeterso23662/MrLumps

**Comment by djpeterso23662** [comment]
Version 2.0.0 release of MrLumps plugin.
Commit fd8b20a35dff7d855cf55354c0a02c042b7184a5

Thanks very much for your help, @cschol and friends!

David Peterson
https://github.com/djpeterso23662/MrLumps

**Comment by cschol** [comment]
Font references stored across frames: https://github.com/djpeterso23662/MrLumps/issues/15

**Comment by djpeterso23662** [comment]
Commit 479658080d796a48b8993912cf2ed0fc534c3631 removes font references stored across frames.  Could we please have another go at version 2.0.0 release of MrLumps plugin?  Thanks for your help, @cschol and friends!  

David Peterson
https://github.com/djpeterso23662/MrLumps
