### ISSUE TITLE
JLmod

### ISSUE THREAD

**Issue by JoakimLindbom** [VCVRack/community#638]
Source code: https://github.com/JoakimLindbom/JLmod 
Version: 1.0.0
Commit hash: 727f650be0f214f859474d4c36137c325ad9039e

**Comment by cschol** [comment]
You plugin has been integrated in the Rack library repository and will be available with the next plugin manager update for all supported platforms. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community!
