### ISSUE TITLE
Interrobang

### ISSUE THREAD

**Issue by jimallman** [VCVRack/community#639]
Version 1.0.0 release of the **Interrobang (Free)** plugin. This is its initial release.
Latest commit 1dd37d7
https://github.com/jimallman/interrobang-rack-modules

There's just one simple module so far. Please take a look when you have a moment. Thanks!

**Comment by jimallman** [comment]
Hm, after reading [this thread](https://community.vcvrack.com/t/plugin-tags-names-and-brands/4262/14) about making modules easily searchable, I'm wondering if I should change the registered name (and/or slug?) of this module to **SS-3** to match its faceplate, instead of [the current **ScribbleStrip**](https://github.com/jimallman/interrobang-rack-modules/blob/master/plugin.json#L17-L18). The latter is too long to fit in a 3HP module.

Please advise, and thanks.

**Comment by AndrewBelt** [comment]
The slugs are fine. Modules like VCV Sequential Switch 1 often have abbreviations on the panel but their names are the "long form". It's whatever you feel is best. Names can be changed at any time.

**Comment by jimallman** [comment]
Thanks. Based on this and the thread above, I've gone ahead and updated the module name to "Scribble Strip, 3 HP (SS-3)", in [commit f1d9082](https://github.com/jimallman/interrobang-rack-modules/commit/f1d90829f0b5cca99b6c89d18f51b5d28a7f3b4d) (I'm considering making scribble strips in different widths.)

**Comment by cschol** [comment]
Invalid URL in `plugin.json`: https://github.com/jimallman/interrobang-rack-modules/issues/1

**Comment by jimallman** [comment]
New version 1.0.1 with fixes for issues above
Latest commit 853e4ec

**Comment by cschol** [comment]
Build failure on Windows platform: https://github.com/jimallman/interrobang-rack-modules/issues/3

**Comment by jimallman** [comment]
New version 1.0.2 with more compilation fixes
Latest commit 611c4ea2bf8ea27b4426ab55b4cf131ed375876c

**Comment by AndrewBelt** [comment]
Hi @jimallman, I'm inviting you to consider licensing your software under the [GPLv3+](https://www.gnu.org/licenses/quick-guide-gplv3.html) (SPDX identifier `GPL-3.0-or-later`). We have discovered that many plugin developers using BSD, MIT, CC0, etc licenses might not fully be aware of the practical consequences that these extremely permissive licenses have.

Nearly all free/open-source software developers want the [Four Essential Freedoms](https://www.gnu.org/philosophy/free-sw.html) for their users and the rights explained in the [Open Source Definition](https://opensource.org/osd-annotated). However, the act of someone taking your hard work, putting a proprietary license on it, and selling it for personal gain is not one of these desired freedoms, yet BSD and similar licenses explicitly allow this behavior. This is not just a hypothetical scenario! It happens frequently in this $1 billion audio software industry and in my experience is more likely to happen to your own software than not.

Of course, the license you choose is ultimately your decision if you are fine with people using your work in proprietary software, but a safer alternative might be to go ahead and use GPL but include a note saying "Contact example@example.com for a GPL exception" where you can negotiate terms based on the exact scenario.

**Comment by jimallman** [comment]
New version 2.0.0 (for VCV Rack 2.)
Latest commit 44bd402579985addb55fb5e234f29d89132af243
https://github.com/jimallman/interrobang-rack-modules

This is tested and working for me on the Mac, using Studio Edition 2.git.2efb7ff5

**Comment by cschol** [comment]
@jimallman We are not accepting submissions for the `v2` of Rack yet. We will let developers know when to submit their `v2` plugins to the Library. Thanks.

**Comment by jimallman** [comment]
New version 2.0.1 (for VCV Rack 2.)
Latest commit 4a148ffea5ab569f28df876661e0bd529160858e
https://github.com/jimallman/interrobang-rack-modules

This is tested and working for me on the Mac, using VCV Rack Free 2.0.3
