### ISSUE TITLE
Feature Request: Library Filter To Display "On Sale" Plugins (If Any)

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [VCVRack/community#640]
Unless an on-sale plugin was recently updated and at the top of the page, or I already know about a sale from the VCV Rack forum, there doesn't seem to be a quick/easy way to identify which plugins, if any, are currently on sale.

Proposal:
In the "Free/Open Source/Premium" plugin section of the VCV Rack Library, add a "On Sale" option.

This would help further promote on-sale plugins, hopefully generating some additional revenue, while also encouraging developers to put items on sale for the extra visibility (if they so desired of course).

**Comment by AndrewBelt** [comment]
This is the issue tracker for the VCV Library database. Email at https://vcvrack.com/contact.
