### ISSUE TITLE
PolyAudibleInstruments

### ISSUE THREAD

**Issue by Xenakios** [VCVRack/community#641]
Version 1.0.8. commit hash d0d2de7c2aca51e5d61ca1987b4e0e1a7662fa71

https://github.com/Xenakios/Poly_AudibleInstruments

**Comment by AndrewBelt** [comment]
I'm not sure if this should be on the VCV Library. It would confuse a lot of people because the panels are identical. I'd prefer it to be contributed to Audible Instruments since in mono mode, these should theoretically function identically.

**Comment by cschol** [comment]
Was there a decision made on the inclusion of this?

**Comment by AndrewBelt** [comment]
I've added a note on forks here. https://github.com/VCVRack/library#vcv-library-database
I see this as a *feature branch*, or a variant of the same plugin. I think there are two good options. Get the code reviewed and merged into Audible Instruments, or @Xenakios should release binaries (if they want to) outside of the VCV Library. Neither of these options require an issue thread for this repo, so I'm closing.
