### ISSUE TITLE
AuraAudio

### ISSUE THREAD

**Issue by emurray2** [VCVRack/community#642]
Source URL: https://github.com/emurray2/EVMusic-Rack
Version: 1.0.0 
Commit Hash: 737444758681735dc35abfce959fb8685056146b

**Comment by cschol** [comment]
Plugin Manager integration issues: https://github.com/emurray2/EVMusic-Rack/issues/2

**Comment by emurray2** [comment]
New Source URL: https://github.com/emurray2/auraaudio-vcv-rack
New Version With Fixes: 1.0.1
Latest Commit: 64e87b7

**Comment by AndrewBelt** [comment]
Hi @emurray2, I'm inviting you to consider licensing your software under the [GPLv3+](https://www.gnu.org/licenses/quick-guide-gplv3.html) (SPDX identifier `GPL-3.0-or-later`). We have discovered that many plugin developers using BSD, MIT, CC0, etc licenses might not fully be aware of the practical consequences that these extremely permissive licenses have.

Nearly all free/open-source software developers want the [Four Essential Freedoms](https://www.gnu.org/philosophy/free-sw.html) for their users and the rights explained in the [Open Source Definition](https://opensource.org/osd-annotated). However, the act of someone taking your hard work, putting a proprietary license on it, and selling it for personal gain is not one of these desired freedoms, yet BSD and similar licenses explicitly allow this behavior. This is not just a hypothetical scenario! It happens frequently in this $1 billion audio software industry and in my experience is more likely to happen to your own software than not.

Of course, the license you choose is ultimately your decision if you are fine with people using your work in proprietary software, but a safer alternative might be to go ahead and use GPL but include a note saying "Contact example@example.com for a GPL exception" where you can negotiate terms based on the exact scenario.

**Comment by cschol** [comment]
Build failure on Windows platform: https://github.com/emurray2/auraaudio-vcv-rack/issues/1

**Comment by emurray2** [comment]
@AndrewBelt That is great advice! I didn’t even think about that. Yes, I would definitely prefer to use the GPLv3 license because it sounds like it protects me more yet gives other people the freedom to use and make changes to my software with permission. That’s exactly what I want because this plugin is more of a personal project for education rather than proprietary.

**Comment by emurray2** [comment]
@cschol Would I be able to add a premake5.lua to my repository or detect the platform in the Makefile somehow? Compiling Windows  10 with `mingw32` and `mingw64` needs `LDFLAGS += -lopengl32 -lgdi32 ` added in the Makefile. I was able to build it and run in VCV Rack on Windows 10 64 bit with these settings.

**Comment by cschol** [comment]
@emurray2 you can detect the platform with the existing `Makefile` variables. See `arch.mk` in the Rack source code repository for the available options.

**Comment by emurray2** [comment]
Source URL: https://github.com/emurray2/auraaudio-vcv-rack
Latest commit: 75bebfe
Version: 1.0.2

Here's some changes I made since version 1.0.1
     -Fixed some bugs (loading multiple instances of the module ModularForecast was buggy)
     -Changed License to GPLv3
     -Updated Makefile with platform detection capabilities

Tested on VCV Rack v1.1.6 
     - MacOS Catalina 10.15.4 
     - Windows 10 64 Bit
     - Not sure about Linux (I do not have a VM or cross-compiler setup)

**Comment by cschol** [comment]
Module prints to `stdout` for Debug: https://github.com/emurray2/auraaudio-vcv-rack/issues/2

**Comment by emurray2** [comment]
Removed the `std::cout`
Latest commit: 9b1f7e4

**Comment by cschol** [comment]
Your plugin has been integrated in the Library repository. The plugin will be available in the Plugin Manager with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by emurray2** [comment]
Source URL: [https://github.com/emurray2/auraaudio-vcv-rack](https://github.com/emurray2/auraaudio-vcv-rack)
Version: 2.0.0
~~Commit Hash: 96132d74cef05e04e5537a36effb44e74d0def54~~
~~Commit Hash: 4c416fa7608e37d60ea9e040d3b2d7910bdcf19e~~
Commit Hash: 06a4fff774ecf797395e839798e1e141e94feb72
Changes:
* Use VCV Rack 2.0.0 SDK API Calls
* Update `plugin.json` to reflect compatibility with VCV Rack 2
* Refactor Makefile
* Add MIT License

My apologies, I never added a license to the repo. Please use the latest hash not crossed out. Thanks.

**Comment by emurray2** [comment]
Also, if you're looking for people to help with integration/library updates, I'd love to contribute when my schedule is free. Currently, I help out over at [AudioKit](https://github.com/AudioKit) from time to time.

I'd prefer to start with the Library Team or the tasks you outlined in the Integration stage of [VCV Rack Open-source Plugins](https://github.com/VCVRack/library/projects/1). Of course I'm a busy student (currently studying at Georgia Tech), but I'll help out whenever my schedule allows. I'm already starting to look at some of the open issues and familiarize myself with the process.
