### ISSUE TITLE
Mantra

### ISSUE THREAD

**Issue by giogramegna** [VCVRack/community#643]
Source: https://github.com/giogramegna/mantra-master
Version: 1.0.0

**Comment by cschol** [comment]
Plugin integration issues: https://github.com/giogramegna/mantra-master/issues/1

**Comment by giogramegna** [comment]
Should be fixed now.

Source: https://github.com/giogramegna/mantra-master
Version: 1.0.0

**Comment by cschol** [comment]
Plugin compilation fails: https://github.com/giogramegna/mantra-master/issues/1

**Comment by cschol** [comment]
Your plugin has been integrated in the Library repository and will be available in the Plugin Manager with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by giogramegna** [comment]
Source: https://github.com/giogramegna/mantra-master
Version: 1.0.1
Last commit: c5ed11c

Release notes:
 - Fixed some tags
- Added a new panel module
