### ISSUE TITLE
NoraCodes

### ISSUE THREAD

**Issue by NoraCodes** [VCVRack/community#644]
https://github.com/NoraCodes/fives/

1.1.0 169e984629e65ce8024aea3b7319cb962e62ff16

**Comment by NoraCodes** [comment]
FYI, reading some other discussions here, I noticed that you have a preference for GPLv3; I personally would prefer that this module remain licensed ISC. I do understand and agree with your general preference but it doesn't make sense for this code.

**Comment by cschol** [comment]
You can choose whichever license you want. Please be aware of the issues encountered with non-GPL licenses and plugins developed for VCV Rack.

**Comment by cschol** [comment]
Invalid tags in `plugin.json`: https://github.com/NoraCodes/fives/issues/1

**Comment by NoraCodes** [comment]
Mentioned in the other thread as well, but is there an appropriate tag for "this is based on real hardware, but nothing that ever got a Eurorack module"?

**Comment by AndrewBelt** [comment]
If the module "Clones the functionality, panel design, and component layout of a hardware module on the market", then use "Hardware clone". If not, don't use it. https://vcvrack.com/manual/Manifest#hardware-clone

**Comment by NoraCodes** [comment]
Fixed, thanks for letting me know!

**Comment by NoraCodes** [comment]
Updated to 1.2.0 at f9463ea. (I fixed the Astable C not being tuned for 1V/Oct, and moved the pretuning so the Astable and Astable C are more differentiated as an LFO and VCO respectively.)

**Comment by NoraCodes** [comment]
Updated to 1.2.2 at d7c4bf9. I fixed the panels being a little confusing for some users and added unipolar/bipolar switch.
