### ISSUE TITLE
rchoices

### ISSUE THREAD

**Issue by davekch** [VCVRack/community#646]
https://github.com/davekch/rchoices

**Comment by AndrewBelt** [comment]
@cschol will run his validation script later, but the only potential issue I see is that the plugin name is based on the functionality of the modules it contains. Will you perhaps add modules later that don't relate to the title?

**Comment by davekch** [comment]
Thanks for pointing this out. I don't plan on adding modules that are not related to randomness in some way. Should I use  a different plugin name anyway?

**Comment by AndrewBelt** [comment]
Okay, then the slug/name is fine. You can change the name whenever you like, you just can't change the slug after releasing.

**Comment by davekch** [comment]
Ok then I won't change it :)

**Comment by cschol** [comment]
Your plugin has been integrated in the Rack library and will be available for all supported platforms in the Plugin Manager with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community!

**Comment by davekch** [comment]
awesome, thanks a lot :)

**Comment by davekch** [comment]
there is a new version (2.0.0) for Rack version 2. commit hash is `0a84df93acd754c9656f7354`
