### ISSUE TITLE
az

### ISSUE THREAD

**Issue by azrrik** [VCVRack/community#648]
version: 1.0.0
https://github.com/azrrik/az-vcv
64d5d1f64d501d4b896240772e4db944f927ebd9

thanks

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available in the Plugin Manager for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by azrrik** [comment]
I have a new version to release:

version: 1.1.0
338bfe17ec2e8d137d545bdf3bc43b06e02e3ed5

Please and thanks!

**Comment by azrrik** [comment]
I have a new version to release:

version: 1.1.1
439726b02d5211e521be73528c8586047583156b

Please and thanks!

**Comment by azrrik** [comment]
Updates for Rack 2.0:

version: 2.0.0
096865d509b9401906efc8421e1196194c6766ad

Please and thanks!

**Comment by cschol** [comment]
Great job! Your plugin passed all integration tests and builds successfully against the current SDK git.219bbaf1 for all supported platforms using the new v2 toolchain.

However, we are not accepting submissions to the library for v2 of Rack yet.
We will let developers know when to submit their v2 plugins to the library. Thank you.

**Comment by cschol** [comment]
Library submissions are now open. I will move your plugin to the integration queue.

**Comment by azrrik** [comment]
I have a new version to release:

version: 2.0.1
a0509693b1cfd814f9cbde43a0809539685ad839

Please and thanks!
