### ISSUE TITLE
StudioSixPlusOne

### ISSUE THREAD

**Issue by curlymorphic** [VCVRack/community#649]
New plugin
V1.0.0
https://github.com/StudioSixPlusOne/rack-modules

commit : 65c04af0ba44abfe6448cc508a0051022d2c24dc

Thank you.

**Comment by AndrewBelt** [comment]
You might want to include a license in LICENSE.txt or LICENSE.md or README.md or at the top of each source file.

**Comment by curlymorphic** [comment]
Thanks Andrew for your comment, all source code files currently have the license header, GPL3+ for all code I own the copyright,  original author license for any external code.

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available in the Plugin Manager for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by curlymorphic** [comment]
Updated to V1.0.1
https://github.com/StudioSixPlusOne/rack-modules

commit: 9250daad0cae1e577835cb24dbee674d5271bd08

 - Tyrant polyphonic trigger and shuffle probabilities
 - Removed warnings when building tests
 - Wallenda now has saturated outputs

**Comment by curlymorphic** [comment]
Updated to V1.1.0
https://github.com/StudioSixPlusOne/rack-modules

commit: 810239fd741b313df705e91d08f848503c107431

3 new modules,  Lala cascadable two way crossover, Eva 8 in VCA, Zazel a performance controller
1 expander module TE for Tyrant

**Comment by curlymorphic** [comment]
Updated to V1.1.1
https://github.com/StudioSixPlusOne/rack-modules

commit cd15e6e3b0908bcab4c4ea085d01e6d6077df17d 
tag: V1.1.1

Updated UI, Bugfixes

**Comment by curlymorphic** [comment]
Updated to V1.2.0
https://github.com/StudioSixPlusOne/rack-modules

commit 76f31200373500890e6cea2569bdf61807d63456 tag: v1.2.0

Additional modules, Iverson & Iverson Jr

Thank you

**Comment by curlymorphic** [comment]
Updated to V1.2.0
https://github.com/StudioSixPlusOne/rack-modules

commit 5a31abfa71846d9ac83559f643adf4cfa3d7a3dd  tag v1.2.1

new features and presets for v 1.2.1

Thank you for your time.

**Comment by curlymorphic** [comment]
Updated to V1.2.2
https://github.com/StudioSixPlusOne/rack-modules
4a2f29649c7cc05d0b61bf8ea8926ad6d6a5c08a 

May I request an update, fixed the non lnear processing on Maccomo, updated Iverson

**Comment by curlymorphic** [comment]
Update to V1.3
https://github.com/StudioSixPlusOne/rack-modules
93bf73385827c6f406120ecbd87bb9fc625894ae

May I have a new build please, I have added a new module, Zilah

Thank you.

**Comment by curlymorphic** [comment]
Hi Andrew, cschol

Update to V1.4, Two new modules

https://github.com/StudioSixPlusOne/rack-modules
f26d89cb8e0b33fb9c21fb98c9e9a37cd8bae0b5

May I have a new build please.

**Comment by cschol** [comment]
Build error on macOS platform: https://github.com/StudioSixPlusOne/rack-modules/issues/112

**Comment by cschol** [comment]
Closing this until an update is available.

**Comment by curlymorphic** [comment]
Hi Andrew, cschol

I have updated my plugin to be compatible with VCV Rack 2

https://github.com/StudioSixPlusOne/rack-modules
37ecc9d624176e97f584a5d9cbcec90ab53d215c

May I have a new build in the library, please

Dave

**Comment by curlymorphic** [comment]
Hi cschol, Andrew.

May I have a new build please I have added some modules

https://github.com/StudioSixPlusOne/rack-modules
sha: a3df1db7dd23abf93275166e455978842b614bf3

Thank you.
