### ISSUE TITLE
KautenjaDSP-RackNES

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/community#650]
https://github.com/Kautenja/RackNES/tree/master

**Comment by AndrewBelt** [comment]
I was waiting for the day when someone made a video game emulator for Rack! This looks fantastic.
I was actually working with someone on an emulator based on Higan, but for several reasons that project was cancelled so it's nice to see this instead.

**Comment by Kautenja** [comment]
Thanks! :) I actually came across a thread on the forum where you and some other people mentioned the idea and it inspired me. Initially, I thought it would just be a fun novelty, but the CV really adds some potential to make music with the thing. Messing with the clock rate is a lot of fun.

**Comment by cschol** [comment]
Your plugin has been integrated in the Library repository and will be available for all platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Kautenja** [comment]
Awesome!

**Comment by Kautenja** [comment]
The version has been updated to 1.1.4 to address two bugs

**Comment by cschol** [comment]
Invalid tag: https://github.com/Kautenja/RackNES/issues/25

**Comment by Kautenja** [comment]
my bad, should be good to go now.

**Comment by Kautenja** [comment]
updated to 1.1.6 in [715f9ff](https://github.com/Kautenja/RackNES/commit/715f9ff2bfcb0d1a1f5da771692bb2a469c1a619) to fix an issue with the plugin name (now named _KautenjaDSP RackNES_).

another big bug was fixed that was causing the audio to pop and crackle at some emulator clock rates.

**Comment by Kautenja** [comment]
Version has been updated to 1.4.2 in commit d91cc8653eaefbfce656f5800c7c4fcf14712b30. There are a few changes worth noting:
- Mixer: full control over the NES mixer to remix stuff
- NTSC graphics emulation: NTSC filters applied to NES pixels to produce that old school visual effect
- load ROM files with dragon drop
- CPU emulation updated to be more accurate (audibly in some cases)

**Comment by Kautenja** [comment]
Version updated to 2.0.0 in https://github.com/Kautenja/RackNES/commit/f4271500cadbcb1258bd9e47ac2a7a822e0fde90. This updates the module to the v2 ABI and introduces a new CVGenie module!
