### ISSUE TITLE
KautenjaDSP-PotatoChips

### ISSUE THREAD

**Issue by Kautenja** [VCVRack/community#652]
Emulations of retro sound chips as basic oscillator modules:

https://github.com/Kautenja/PotatoChips

currently at version 1.1.2 for commit [565c276](https://github.com/Kautenja/PotatoChips/commit/565c2760165a2d75ba647b864d2b9acb62037b00)

**Comment by cschol** [comment]
Can you please remove (and **purge**!!) the `design.sketch` file from the repository? The repository is too large. The build system is cloning the repository during the build process and this will take too much bandwidth. Thank you.

**Comment by Kautenja** [comment]
This should be fixed now. I went ahead and took care of the same issue for #650 too.

**Comment by cschol** [comment]
The repository is still 49 MB. 

It looks like the `design.sketch` files are still in the repo history:

```
eb3c3f2cd8c7   16MiB design/design.sketch                                                                                                                                                                                                                                                                             
6632ea9ed59b   16MiB design/design.sketch                                                                                                                                                                                                                                                                             
867a0def08c3   16MiB design/design.sketch                                                                                                                                                                                                                                                                             
955f10380d6c   16MiB design/design.sketch
5fc6564394a1   16MiB design/design.sketch
91fb7d2b66dd   16MiB design/design.sketch
21e7e9be19ac   16MiB design/design.sketch
6663e2d8da33   16MiB design/design.sketch
e3989adc6df7   16MiB design/design.sketch
e1a92b5065ed   16MiB design/design.sketch
336828b5e1d6   16MiB design/design.sketch
4e445f4dce9c   16MiB design/design.sketch
a317db5773e3   17MiB design/design.sketch
1efeb85c5d12   17MiB design/design.sketch
512760deaa62   17MiB design/design.sketch
```

**Comment by Kautenja** [comment]
fixed

**Comment by Kautenja** [comment]
@cschol what is the command you're using to generate that output? It will be useful for preventing this in the future.

**Comment by cschol** [comment]
Files are still there.

For command to see large files in history see here: https://stackoverflow.com/a/42544963/2386

For a tool to remove those: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by Kautenja** [comment]
I'm not sure what you mean by files are still there. All files are on the order of KB and the repository is only 9.7MB in total. Output from command (from freshly cloned repository):

```
...
45bf77e6a05d  219KiB img/VRC6.png
0c3eeac02463  235KiB img/2A03.png
050cc0ab288a  278KiB img/VRC6.png
0ee34c0c08ef  483KiB img/Plugin.png
6a30556fc0c7  484KiB img/Plugin.png
446a5ee17b6f  506KiB img/Plugin.png
3d7cf7f4fe3f  506KiB img/Plugin.png
9348c4e32346  542KiB img/Plugin.png
25bf635bf9cb  548KiB img/Plugin.png
```

**Comment by Kautenja** [comment]
I've done some more cleanup where possible. The repository is now a mere 4MB. All large images have been removed and the built PDF LaTeX manuals have been moved to distribute with releases.

```shell
...
4278a4fa8952  106KiB manual/PotatoChips/img/PotatoChips-Plugin.pdf
137f5c159c46  106KiB manual/PotatoChips/img/PotatoChips-Plugin.pdf
7a52d7a109f8  106KiB manual/PotatoChips/img/PotatoChips-Plugin.pdf
8153f11b22aa  106KiB manual/PotatoChips/img/PotatoChips-Plugin.pdf
80519d0d5f6c  107KiB manual/PotatoChips/img/PotatoChips-Plugin.pdf
5759a107d767  279KiB manual/PotatoChips-Plugin.svg
cd2bfdffde34  279KiB manual/PotatoChips/img/PotatoChips-Plugin.svg
```

**Comment by cschol** [comment]
All good. For some reason I expected the repo to update with `git pull` and remove the files from its local history, but it didn't. A fresh clone shows that the files are gone.

**Comment by Kautenja** [comment]
Version has been updated to 1.3.0 in commit 24968a47a3d2b64f686e940ded9eb09721d9a2e2. The change introduces a new module **106** with 8-channels of 15-bit wave-table synthesis and a fun wave-table editor GUI thing.

**Comment by Kautenja** [comment]
please use version 1.3.1 in commit e34f89984bd63e513d453c1d2cb58e6a67303f8c instead. Sorry for the double release spam. I just discovered the clock divider functionality for CV acquisition and LED updates that significantly improves the performance of these modules.

**Comment by Kautenja** [comment]
updated to version 1.3.3 in https://github.com/Kautenja/PotatoChips/commit/6ae989af724fbba4509a9d79a89c762ab33af985 to address issues with 106:
- tuned correctly to C4 as base frequency
- fix issue where increasing sample rate would increase pitch

**Comment by Kautenja** [comment]
Updated to 1.3.4 in https://github.com/Kautenja/PotatoChips/commit/65430cd1f79b35c3095689a61ca57370e94a7f8c.
- fix issue where audible "click"/"pop" would occur every ~1200ms at sample rates of 44.1kHz, 88.2kHz, etc.
- fix issue where 2A03, FME7, VRC6 were detuned at sample rates of 44.1kHz, 88.2kHz, etc.

**Comment by Kautenja** [comment]
Updated to 1.4.0 in https://github.com/Kautenja/PotatoChips/commit/0a5b43b5cc8bf9840cd3662a12b1b356a00941bf with a new module: SN76489 (the sound chip from the Sega Master System)

**Comment by Kautenja** [comment]
updated to 1.4.1 in https://github.com/Kautenja/PotatoChips/commit/590ef4cd276c708236088b0b0662362a02c0dcd9 to resolve some small bugs across all the modules and tweak panels.

**Comment by AndrewBelt** [comment]
I'm getting a build error on the Mac cross-build.
```
x86_64-apple-darwin17-clang++-libc++ -std=c++11 -stdlib=libc++  -DTEST -Wno-unused-local-typedefs -fPIC -I/home/vortico/src/vcv/library/Rack-SDK/include -I/home/vortico/src/vcv/library/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -c -o build/src/AY_3_8910.cpp.o src/AY_3_8910.cpp
In file included from src/106.cpp:21:
In file included from src/dsp/namco_106.hpp:22:
src/dsp/blip_buffer.hpp:469:18: error: cannot assign to non-static data member within const member function 'update'
        last_amp = amplitude;
        ~~~~~~~~ ^
src/dsp/blip_buffer.hpp:467:17: note: member function 'BLIPSynthesizer::update' is declared const here
    inline void update(blip_time_t time, int amplitude) const {
    ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/home/vortico/src/vcv/library/Rack-SDK/compile.mk:69: build/src/106.cpp.o] Error 1
```
Seems like `update()` shouldn't be `const`?

**Comment by Kautenja** [comment]
Weird, I'm not sure how that got past the compiler on my development or build machines as that `const` modifier is very obviously invalid when I look closer. Anyway, fixed here: https://github.com/Kautenja/PotatoChips/commit/e5d00515922adcff235e04cebaedc3840c22ecbd

bumped version to 1.4.2 because I had already pushed the 1.4.1 tag to GitHub

**Comment by Kautenja** [comment]
Oh, I see why it slipped past. The `update` function that was marked as const is not called anywhere in the client code. I guess my compilers are filtering unused symbols before reaching a state where the "constness" of a function matters.

**Comment by cschol** [comment]
@AndrewBelt That is strange. My build system should have caught that. What osxcross version is this?

**Comment by AndrewBelt** [comment]
`clang version 10.0.1` with `MacOSX10.13.sdk.tar.bz2`

**Comment by cschol** [comment]
@Kautenja Can you please check that you pushed the new revision to Github? The above SHA does not exist in the repo.

**Comment by Kautenja** [comment]
Somehow the tag got pushed, but the commit where I bumped the tag didn't. Fixed now.

**Comment by Kautenja** [comment]
Updated to 1.5.1 in https://github.com/Kautenja/PotatoChips/commit/b5fd194e4d0e50e83f69721594322088d3216608
to introduce three modules: GBS, POKEY, and AY-3-8910.

**Comment by Kautenja** [comment]
version updated to 1.6.2 in https://github.com/Kautenja/PotatoChips/commit/8021232100e5d1a27b7d50f0aa4873ef6178e4a2 to bring polyphonic support to all modules and resolve a major edge case bug in 106.

**Comment by Kautenja** [comment]
Updated to 1.7.0 in https://github.com/Kautenja/PotatoChips/commit/27d1b94a1cb3b7924996d12f9e1a0f6d48534661

The version introduces some bug fixes and a new module: 2612. 2612 is a rework of the CV2612 module in the https://github.com/diegodorado/TercerBrazo plugin. The faceplate is entirely different and the model of execution is also different (full support for 16-voice polyphony, 6 inputs for the 6 voices on the chip).

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/Kautenja/PotatoChips/issues/54

**Comment by Kautenja** [comment]
Whoops. 1.7.1 in https://github.com/Kautenja/PotatoChips/commit/45ebe4076c802a644910846fc46cf344fa1d1c67 resolves the invalid tag issue as well as a few other bugs in 2612.

**Comment by Kautenja** [comment]
Updated to 1.7.3 in https://github.com/Kautenja/PotatoChips/commit/79179bcabc46ae49f52973db037f917445544c87 to fix a few bugs.

**Comment by Kautenja** [comment]
Updated to 1.8.2 in https://github.com/Kautenja/PotatoChips/commit/08e950d071de9662db87fa07deabdf971ebe2ed8

**Comment by Kautenja** [comment]
Updated to 1.9.0 in https://github.com/Kautenja/PotatoChips/commit/4a6c45adbbcf658dd5e4b39cc77b87b9008430a3

**Comment by cschol** [comment]
@Kautenja From what I can see you are changing slugs of several already released modules, is that correct?

**Comment by Kautenja** [comment]
cschol no, none of the slugs of released modules have changed. This release just adds three new modules.

**Comment by cschol** [comment]
Ah, you had `disabled` set to `true` for those ones, e.g. "S_SMP_ADSR". Never mind. All good.

**Comment by Kautenja** [comment]
ooo ya those did change. I forgot I had left them in the json in previous releases. Sorry for the confusion.

**Comment by Kautenja** [comment]
Bumped to 1.11.0 to introduce a new module and fix some issues: https://github.com/Kautenja/PotatoChips/commit/fc5eaebf1b8a363abca8019b68f489238026e154

**Comment by Kautenja** [comment]
Updated to support Rack v2 in https://github.com/Kautenja/PotatoChips/commit/8d368a05ae0337d1f8f9decce9e278c7f1190ba4
