### ISSUE TITLE
Truly

### ISSUE THREAD

**Issue by travisat** [VCVRack/community#653]
https://github.com/travisat/Truly
v1.0.0
95d821d3d739d73dc4bad306ffc9979ff7c7dfd2

**Comment by travisat** [comment]
Added two more plugins 
v1.0.1
41ca37c0c0fa41ebb4023e61e8667121d6ce79bc

**Comment by cschol** [comment]
Issue with file names: https://github.com/travisat/Truly/issues/2

**Comment by travisat** [comment]
I think I have fixed the file names
v1.0.2
be301f62dd87aae06471b4949f866c916760957a

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
