### ISSUE TITLE
IggyLabsModules

### ISSUE THREAD

**Issue by isabelgk** [VCVRack/community#654]
https://github.com/IggyLabs/IggyLabsModules

```
Version 1.0.0
commit 7029199b91cc377237cfac97d37c4e2ce901842a
```

**Comment by isabelgk** [comment]
Hi, I would like to update with a bugfix on my first module as well including a second module I've added. 

https://github.com/IggyLabs/IggyLabsModules
```
Version 1.0.1
commit 8d350649815448062e33b8d2386b32ba85b9a928
```

**Comment by isabelgk** [comment]
Hi, I have another quick fix to implement tomorrow. Can you please hold this build until I give a new commit hash for v1.0.1? If not, I can just put the fix into a v1.0.2. I'm not sure what is the usual scenario. I don't want to be a pain asking for new version builds too frequently :)

EDIT: I made the fix, so I would like to use commit `a19658c9d0863b2392193febfef0c534b4c3313e`.

**Comment by cschol** [comment]
It had not been released yet, so I updated with this commit above.

**Comment by isabelgk** [comment]
Hi, I have another update to make, this time for v1.0.2. There are a few bug fixes and features I've implemented from user requests. 

Thank you for helping me make these updates and pushing to the library for me so responsively! I really appreciate it.

v1.0.2 is now at
`commit 2d041382de2626ca6a4622ec3a1f8cbbdbed2c42`

**Comment by isabelgk** [comment]
Hi, I'd like to submit an update to the library.
Thanks in advance!

https://github.com/IggyLabs/IggyLabsModules

```
Version 1.1.0
commit 8893217eade91be21c4bf1375319398032a228be
```

**Comment by isabelgk** [comment]
Hi, I'd like to submit an update to the library. 
Thanks in advance!

https://github.com/IggyLabs/IggyLabsModules

```
Version 1.1.1
commit dab1b7ed8369a443d3ecdd8ae197b274970a8ee3
```

**Comment by isabelgk** [comment]
Hi, I'd like to submit an update to the library.
Thanks in advance!

https://github.com/IggyLabs/IggyLabsModules
```
Version 1.1.2
commit c2d740011a58450a9d6b0d920bc9e8aa44c5bdfb
```

**Comment by isabelgk** [comment]
Hi,

I've updated the plugin to be ready for v2. The relevant commit is at `91e9bcdde24ef6d32a14308ea83da562fb914a1d`. Would you be able to update this in the library?

Thanks.
