### ISSUE TITLE
rackwindows

### ISSUE THREAD

**Issue by n0jo** [VCVRack/community#655]
Hi, new plugin here. A collection of ported Airwindows plugins. Would be nice if it could be added to the library. 

Thanks and cheers, 
Robert

https://github.com/n0jo/rackwindows

new version: 1.1.0
commit hash: 7730fe0451683d2c9c897211619934e24ce12833

**Comment by cschol** [comment]
Your plugin has been integrated and will be available in the Plugin Manager for all available platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by n0jo** [comment]
latest version: 1.1.1
commit hash: cd3f1b5310785a8b7c31ede3e70281eb82f14d66

**Comment by n0jo** [comment]
latest version: 1.1.2
commit hash: 1b639e389aab543a0b1a4eaaee68b3be0f68b5d4
