### ISSUE TITLE
Atelier

### ISSUE THREAD

**Issue by Xenakios** [VCVRack/community#657]
https://github.com/Xenakios/Atelier

Version 1.0.0, commit hash a6741b725a417b8bc3841696ac30cce27274f06c

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with then next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Xenakios** [comment]
Version 1.0.1, commit hash 0deef7a17907916037eb4aba620c52437db43687

**Comment by Xenakios** [comment]
Version 1.0.2, commit hash c5bef088538611cf2c43f6b3404c2455cd824e2c

**Comment by Xenakios** [comment]
Version 1.0.3, commit hash 52ccb2a30e05645bfba9f5ec61a55c82d46db9db

**Comment by Xenakios** [comment]
Version 1.0.4, commit hash 71b323bbde3c16e41a817584aa3c2746b263413e

**Comment by Xenakios** [comment]
Version 1.0.5, commit hash 2d670e2aa66f2d1228fdc180d6ca8b7a23888e9d

**Comment by Xenakios** [comment]
Version 2.0.0, commit hash 7c4c6154a6d15f0e31e44584f6fe0ff9824c9650

**Comment by Xenakios** [comment]
Version 2.0.1, commit hash b84dea414c3a2bac231d1c5b837c3003d60a6446

**Comment by Xenakios** [comment]
Version 2.0.2, commit hash 3409eadde21ba15750a7b5a607f960f892074adc
