### ISSUE TITLE
ChowDSP

### ISSUE THREAD

**Issue by jatinchowdhury18** [VCVRack/community#658]
ChowDSP modules for VCV Rack.

Thanks,
Jatin

- source code: https://github.com/jatinchowdhury18/ChowDSP-VCV
- version: 1.0.0
- commit hash [e78a7d2f09b29f5d0803d40348d0d79b0e7318a7](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/e78a7d2f09b29f5d0803d40348d0d79b0e7318a7)

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AndrewBelt** [comment]
The license property should either be `GPL-3.0-only` or `GPL-3.0-or-later`. It looks like `GPL-3.0` is on the SPDX list, but it is deprecated in favor of the more specific ones. @cschol Could you remove `GPL-3.0` from your list of valid SPDX identifiers?

**Comment by cschol** [comment]
@AndrewBelt will do.

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.1.0
Commit: [f89eb63dc02c0949cc0508e01a5e2943c6ead4d9](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/f89eb63dc02c0949cc0508e01a5e2943c6ead4d9)
Updates: 2 new modules (RNN and modal filter), minor updates to tape model and FDN.

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.2.0
Commit: [c3740d715c99b5a4f94bbe0269f5bb47d8fbd29a](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/c3740d715c99b5a4f94bbe0269f5bb47d8fbd29a)
Updates: New module (analog distortion), and updated GUI designs

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.2.1
Commit: [b8d98737852872f75b47d76e340ff6fabd4a3fed](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/b8d98737852872f75b47d76e340ff6fabd4a3fed)
Updates: Fixed oversampling and tape bugs

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.3.0
Commit: [fc6c189406f9ed07529ad7e4cb27a4ec3baccde1](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/fc6c189406f9ed07529ad7e4cb27a4ec3baccde1)
Updates: Added new modules: Werner Filter, ChowPulse, Credits

**Comment by jatinchowdhury18** [comment]
I was dumb, and forgot to update the version in my plugin.json. Please see commit [4cf35ff9c7c974b889dee55fef8dc9ae6f72ff6d](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/4cf35ff9c7c974b889dee55fef8dc9ae6f72ff6d) instead.

Thanks!

**Comment by cschol** [comment]
@AndrewBelt Can you please look at https://github.com/jatinchowdhury18/ChowDSP-VCV/commit/dd55592553741e4b104a74f0a84370ea036f613a and see if this makes sense. I think they should be using Rack's native OS dialog, right? This does not build currently due to missing dependencies in my build image and I want to make sure that this is the right approach. Thanks.

**Comment by AndrewBelt** [comment]
Correct, they shouldn't build and statically link osdialog into their plugin. It is already included in Rack, so they should simply include the header and call osdialog functions.

**Comment by jatinchowdhury18** [comment]
That makes sense. I've made some changes to set it so that it links to the `osdialog` included in Rack by default, and only uses the local copy if the Rack one is not available (e.g. for CI builds). Let me know if you'd prefer that I avoid using any copy of `osdialog` at all, I could let my CI builds fail until I figure out a better solution.

The new leading commit is: [a7685d095bcc2956506146ec5fad4d874fd29f86](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/a7685d095bcc2956506146ec5fad4d874fd29f86)

Thanks!

**Comment by AndrewBelt** [comment]
Just remove it entirely. There's no point of checking if it exists because it always does.

**Comment by jatinchowdhury18** [comment]
Ah, for some reason I was under the impression that `osdialog` wasn't included with the Rack SKD (which is silly now that I think about it).

Here's the new leading commit: [28387daae1df3884ce90d5711d8ddf919fc237e4](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/28387daae1df3884ce90d5711d8ddf919fc237e4)

Thanks!

**Comment by cschol** [comment]
@AndrewBelt The latest plugin version does not load on Windows 10 platforms (confirmed by myself). The error is "Plugin failed to load" in the log.

**Comment by jatinchowdhury18** [comment]
Interesting... When I build on Windows 10, I haven't had any issues with loading errors. Is there any way I can help figure out what's causing this?

It seems like this issue has affected some users: https://community.vcvrack.com/t/chowdsp-development-thread/10634/26?u=jatinchowdhury18

**Comment by cschol** [comment]
@jatinchowdhury18 Are you cross-compiling or doing a native Windows build?

**Comment by jatinchowdhury18** [comment]
I'm compiling with MINGW-64, using the setup described in the Windows section of the [Build Instructions](https://vcvrack.com/manual/Building#setting-up-your-development-environment).

**Comment by caecos** [comment]
Same for me... I have compiled it with MSYS2 and everything works whitout the repeated updating...

**Comment by Outboarder** [comment]
Same here

**Comment by cschol** [comment]
Thank you everyone. We do not need any more confirmations that this is not an issue when you natively compile.

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.3.1
Commit: [0d55621572212b4b69617157faceb8821ee946cf](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/0d55621572212b4b69617157faceb8821ee946cf)
Updates: Fixed crashes on MacOSX caused by Credit module. Hoping the new update will also fix the auto-updating issues noted above.

Thanks!
-Jatin

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.4.0
Commit: [aaac8a288d4641354ce2ef80fa39cc717fa33265](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/aaac8a288d4641354ce2ef80fa39cc717fa33265)
Updates: New distortion module (Warp), variable oversampling.

Thanks!
-Jatin

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 1.4.1
Commit: [`cd5725`](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/cd57255e108c6ab956814aa5d1d922f89814c504)
Updates: Fixed load/save bug for variable oversampling.

Thanks!
-Jatin

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 2.0.0
Commit: [`d5872a`](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/d5872a27d618da97d9c6650f7fde9ec3ddf8786c)
Updates: Updated to Rack v2, and added some new modules.

Thanks!
-Jatin

**Comment by jatinchowdhury18** [comment]
Update to ChowDSP modules:

Version: 2.0.1
Commit: [`e1a20a`](https://github.com/jatinchowdhury18/ChowDSP-VCV/tree/e1a20acc0fe64ed42d7a91ddcdbdf12daa6ec6d3)
Updates: Fixed `loadFont()` issue in Warp module.

Thanks!
-Jatin
