### ISSUE TITLE
GrandeModular

### ISSUE THREAD

**Issue by dbgrande** [VCVRack/community#659]
url:  https://github.com/dbgrande/GrandeModular
version:  1.0.0
commit:  73f8763e50b42e2f614e712a43ab0b26fd2917fe

**Comment by cschol** [comment]
Your plugin has been integrated in the plugin library and will be available for all supported platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version is available. Thank you for providing your plugin to the Rack community.

**Comment by dbgrande** [comment]
version: 1.1.0
commit:  f28619c9cab82cc1550f3eba55239d8517f60f5a

Update to QuantMT. Thanks.

**Comment by dbgrande** [comment]
version: 1.2.0
commit: fa33bb451f5c6816f3663e7dbde416d7ef5f56e1

Update to QuantIntervals. Thanks.

**Comment by dbgrande** [comment]
version: 1.3.0
commit: 80b4975c54d86be3e0b23b5653ae0e23e2f72cfe

Updates to all the quantizers. Thanks.

**Comment by dbgrande** [comment]
version: 1.4.0
commit: 4f2fbc6f588401bfa93ccfd2b37732b0f855b18c

Added new module: MicrotonalNotes. Thanks.

**Comment by dbgrande** [comment]
Can you please hold off on releasing v1.4.0.

Just today, I thought of another related module, which I'm now prototyping.  It doesn't make sense to release this version if this new one works out.

I'll let you know when I'm ready to release again.  Thanks a bunch.

**Comment by AndrewBelt** [comment]
I'm about to release 1.3.0, so just comment in this thread when you'd like to request the next update.

**Comment by AndrewBelt** [comment]
My mistake, v1.3.0 is already released of course, so nothing will happen here.

**Comment by dbgrande** [comment]
It's now ready for release.

version: 1.4.0
commit: 96b0b6e4b6b4f5296321b6d3a7f01423e281a143

Besides MicrotonalNotes I've also added MicrotonalChords. Thanks.

**Comment by dbgrande** [comment]
version: 1.5.0
commit: 76a3f7f378cd5cacc6f5c557798444be4830f275

Added new module: MergeSplit4
Updated: QuantMT reference lights

Thanks.

**Comment by dbgrande** [comment]
version:  1.6.0
commit:  cf9465d34958d92f75866436e5fd575d923b6d88

Updated:  NoteMT output stage now polyphonic

Thanks

**Comment by dbgrande** [comment]
version: 1.7.0
commit: d9303b0d8d448b9dee4ad10c1461f86f1b08ed0b

Added new module: Tails

Thanks

**Comment by dbgrande** [comment]
version: 1.7.1
commit: 5500cc1e6129dcf17410ea08467db3bba03b9ee1

Updated:  Tails, improved robustness and fixed a couple of minor issues.
Plus minor tweaks to several of the panel designs.

Thanks

**Comment by dbgrande** [comment]
version: 1.7.2
commit: 968023d2046ac5f3e09049182bc54899e2f1725b

Updated quantizers so they don't crash Rack when their inputs receive NaNs or infinities.

Thanks

**Comment by dbgrande** [comment]
version: 1.8.0
commit: 2805b50c4d922cafbf8aa9bd4ae7e07bd5927cbe

Added new module: Clip

Thanks for doing all these updates

**Comment by dbgrande** [comment]
version: 1.9.0
commit: bc83a87d63700c7edbc152899691c673558c2f3c

Added new modules: PolyMergeResplit and VarSampleDelays.
Updated: QuantIntervals, interval lights now indicate sharp or flat.

Thanks.

**Comment by dbgrande** [comment]
version: 1.9.1
commit: b9b3725b743c4315253ab833df646632533a0352

Fixed split light halo bug. (I'm hoping that the fancy new Rack2 lights will still support splitting.)
Got rid of custom SmallPorts and added artwork license—in preparation for porting to Rack2.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.0.0
commit: efdf86ca6f47562bde164d145884de92e5ce5fc8

**Comment by dbgrande** [comment]
branch: v2
version: 2.1.0
commit: 4d5e99f4adece7c5f15c7bfd7989bd1556cd95a7

Added new modules: Merge8 and Split8.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.1.1
commit: 63acf65cf2fc9e7d8fb0e638cceceb8d73f91acc

Added new module: PolySplit.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: v2.2.0
commit: 478e86dafc1e429c5ea8785f429d695bb9c25e60

Added two new modules: LFO3 and VCA3.

Thanks.

**Comment by dbgrande** [comment]
Hey! I just realized that I forgot to add bypass to my new VCA3 module, so I've just checked in a new version. Would it be possible for you to pull this one, instead of the previous one?

branch: v2
version: 2.2.0
commit: 40a197698496030a30ead69658b1484eca2ae299

Thanks a lot.

**Comment by dbgrande** [comment]
branch: v2
version: 2.3.0
commit: 33f445d1e3f78aa1f62c8995010303bdb42e0163

Added two more modules: Logic and Peak.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.4.0
commit: b0d8a6fcdb28d2e56d6b024326a7378a2c8ee45d

Added two more modules: LFO4 and Push.
Updated QuantMT to dim inactive note buttons.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.5.0
commit: 3d6524320ce33569e3553a53571c45425ba5d078

Added one more module: VCA4
Updated LFO4 to add the -verter part of an attenuverter.
Minor fix to Push.
Cosmetic updates to the quantizers.

**Comment by dbgrande** [comment]
branch: v2
version: 2.6.0
commit: 6719971ebe92e0b73f87e12817e81a636e39c84a

Added new module: Compare3

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.6.1
commit: 6ce57bfcc43c26cf2c8dc22a4ec4f252c2c13adb

Updates to Tails module.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.6.2
commit: 718a4ff208e4ac114a1efb7123b6e84ca3f9ba6a

Clip: Added logic monitoring mode.
QuantIntervals: Updated panel to highlight standard 12-tone note ratios for reference.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.7.0
commit: b62ed4a52480be7d749318e3a15e9257ad1b2ada

Added new module: Tails4

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.7.1
commit: ada31a17ff1580b4ba541e86e32f3609b34baff0

Minor update to Logic.
Updated modes for Tails and Tails4.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.7.2
commit: bc7ef8157f6ad1284d7c4706eb89132f59555ca1

VCA4 bug fix.

Thanks.

**Comment by dbgrande** [comment]
branch: v2
version: 2.8.0
commit: 2f5f9d84a3c1c9500c0bbd4bcc284dfe0d15209d

Added dark panels for all modules.
Update to Push, triangle buttons now require long press.

I created the dark panels late last year, but didn't want to deal with the code to change them out.  Now it's trivial.
