### ISSUE TITLE
MpSeries 

### ISSUE THREAD

**Issue by libermanomer** [VCVRack/community#660]
version 1.0.0
https://github.com/libermnnn/MpSeries

**Comment by cschol** [comment]
Integration issues: https://github.com/libermnnn/MpSeries/issues/1

**Comment by libermanomer** [comment]
i fixed the issues,
thanks.
https://github.com/libermnnn/MpSeries/tree/MpSeries-1.0.0

**Comment by cschol** [comment]
Thank you. One more thing: please update the version in the `plugin.json` file to be "1.0.0" instead of "1.0".

**Comment by libermanomer** [comment]
@cschol  👍🏼

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by libermanomer** [comment]
MpSeries 1.0.1 - a new module added CV-09 
and bugfix for MpMapper
https://github.com/libermnnn/MpSeries

Thanks!

**Comment by libermanomer** [comment]
latest commit : 18da21a13a5558efb53ed2aad38dd7fd03bba218

**Comment by libermanomer** [comment]
Hey,
 Latest version is 1.0.2 
https://github.com/OmerOki/MpSeries
 included a CHANGELOG.md 

thanks
