### ISSUE TITLE
ZetaCarinae

### ISSUE THREAD

**Issue by mhampton** [VCVRack/community#661]
https://github.com/mhampton/ZetaCarinaeModules

Hi,

After a number of changes addressing suggestions from the community, I think these two simple modules are ready for release.  I am happy to address any issues I have missed.  Thanks!

**Comment by cschol** [comment]
Your plugin has been integrated in the library repository and will be available for all platforms with the next update of the Plugin Manager. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by mhampton** [comment]
Just made a new version, I had some bugs in my svg file that wasn't showing all of the control labels.

https://github.com/mhampton/ZetaCarinaeModules/releases/tag/1.0

**Comment by cschol** [comment]
Version needs update in `plugin.json`: https://github.com/mhampton/ZetaCarinaeModules/issues/2

**Comment by mhampton** [comment]
Right, sorry about that.  I have bumped the version number in the `plugin.json` file.

**Comment by mhampton** [comment]
Added a new module, new version is 1.1.8

commit hash is: 87b222a8f0be51b853bbb4cf1f1f8297e6b68c93

**Comment by mhampton** [comment]
Added a new module (The Weeble Warbler oscillator); new version number is 1.1.11

commit hash is: ce40a8460566af0c2022873bf9455f40331c6a20

Some people have already tested it a bit (see https://community.vcvrack.com/t/first-steps-on-modules-brownian-bridge-ornstein-uhlenbeck-langevin-and-the-weeble-warbler thread) so as far as I know its in pretty decent shape.

**Comment by mhampton** [comment]
Thanks for the very quick processing of my modules!

I would like to request another update, to add a new module (Rosenchance, a 2-state 2-emission Hidden Markov Model). 

The new version number is 1.1.12.

commit hash is: 12b6cce8a099718bcc76b69c63791049ddc33af9

I have not had as much community feedback as before but the new module is pretty simple and performs as I expect in my tests.

**Comment by mhampton** [comment]
This release: 1.1.15
commit hash: b58a04fd0c59fdb7e4130b4007174f5ac4674b49

This contains two new modules:

1) Guilden's Turn, a 4-in 1-out 4-state Markovian router
2) Rossler Rustler, an oscillator/effect based on a chaotic strange attractor (the Rossler attractor).

There are also quite a few minor graphical improvements.

**Comment by mhampton** [comment]
New release: 1.1.18
commit hash: b49d704ccf8a447e313fead81dd43eee51ad6de9

This has a new module, Firefly, an oscillator based on the Kuramoto coupled oscillator model of synchronization.

It also contains some bugfixes/improvements supplied by Xenakios to the RosslerRustler module.

**Comment by mhampton** [comment]
New release: 2.0.4
Commit hash: 54dbe9b22fbc956cbc7b00426e3fce3c757c236c

Migration to Rack 2, seemed like no changes were necessary.
