### ISSUE TITLE
Sha-Bang-Modules

### ISSUE THREAD

**Issue by jeremymuller** [VCVRack/community#662]
Hi,
I'd like to add my modules to the VCV Library.

source code: https://github.com/jeremymuller/Sha-Bang-Modules
latest commit hash: ee805fe
branch: master

Thank you!

**Comment by AndrewBelt** [comment]
Hi @jeremymuller, I'm inviting you to consider licensing your software under the [GPLv3+](https://www.gnu.org/licenses/quick-guide-gplv3.html) (SPDX identifier `GPL-3.0-or-later`). We have discovered that many plugin developers using BSD, MIT, CC0, etc licenses might not fully be aware of the practical consequences that these extremely permissive licenses have.

Nearly all free/open-source software developers want the [Four Essential Freedoms](https://www.gnu.org/philosophy/free-sw.html) for their users and the rights explained in the [Open Source Definition](https://opensource.org/osd-annotated). However, the act of someone taking your hard work, putting a proprietary license on it, and selling it for personal gain is not one of these desired freedoms, yet BSD and similar licenses explicitly allow this behavior. This is not just a hypothetical scenario! It happens frequently in this $1 billion audio software industry and in my experience is more likely to happen to your own software than not.

Of course, the license you choose is ultimately your decision if you are fine with people using your work in proprietary software, but a safer alternative might be to go ahead and use GPL but include a note saying "Contact example@example.com for a GPL exception" where you can negotiate terms based on the exact scenario.

**Comment by jeremymuller** [comment]
@AndrewBelt thanks for the suggestion, I'll update it and send the new commit hash once I get back to my computer. The links are really helpful because I actually spent a while trying to decide on the license, so I appreciate the help.

**Comment by jeremymuller** [comment]
Ok, updated license to GPLv3.0 and here's the new commit hash: 7cffe38

**Comment by AndrewBelt** [comment]
Looks good, but `plugin.json` isn't updated yet.

**Comment by jeremymuller** [comment]
Forgot that. Ok fixed now: f18c8f6

**Comment by jeremymuller** [comment]
@AndrewBelt not sure if i should post this on forums or not, but I've had a strange issue with one of my modules working fine with the polyphony menu, and then later just not working at all. 

It's the Neutrinode module that if you right-click and try to change the number of channels for polyphony it doesn't work. I've hard coded in 16 channels so it functions fine, it's just that the menu does nothing. If you `git checkout dev` and compile from that branch it works fine. I've tried side-by-side comparisons, rebuilding from scratch, etc. and can't figure out what the issue is. Any thoughts?

**Comment by cschol** [comment]
@jeremymuller Did you fix this issue? Is the plugin ready to build?

**Comment by jeremymuller** [comment]
No, but I removed the polyphony menu for now. The plugin is ready to build, I'll work on the menu issue for a later update. Here is the new hash: 4dc4289

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by jeremymuller** [comment]
Please update to the newest version:
- v1.0.1
- commit hash: 02c8ac8

Thank you

**Comment by jeremymuller** [comment]
Please update to latest version. I fixed some bugs and added requested features:
- v1.0.2
- commit hash: 1e33084

**Comment by jeremymuller** [comment]
Please update to latest version. I added some new modules and fixed bugs.
- v1.1.0
- commit hash: c0ff6a1

**Comment by jeremymuller** [comment]
Please update, had to fix a CPU usage bug. 
- v1.1.1
- hash: fe29d42

**Comment by jeremymuller** [comment]
Please update:
- v1.1.2
- hash: dadd3cf

**Comment by jeremymuller** [comment]
Please update to latest version. Happy belated Thanksgiving!
- v1.2.0
- hash: 6a607f4

**Comment by cschol** [comment]
Talea module not defined: https://github.com/jeremymuller/Sha-Bang-Modules/issues/16

**Comment by jeremymuller** [comment]
Ok fixed:
- v1.2.0
- new hash: b2b49c8

**Comment by jeremymuller** [comment]
Some bug/issue fixes and added features, please update to latest version:
- v1.2.1
- commit hash: 7c4fac6

**Comment by jeremymuller** [comment]
Please update to latest version. Happy New Year 🎉 

- v1.2.2
- commit hash: dca064a

**Comment by jeremymuller** [comment]
Hello, please update to latest version. Just some bug fixes:
- v1.2.3
- commit hash: 49f76a0

**Comment by jeremymuller** [comment]
Another bug fix:
- v1.2.4
- commit hash: a473d20

**Comment by jeremymuller** [comment]
Added two new modules and bug fixes. Please update to latest version:
- v1.3.1
- commit hash: 95547ed

**Comment by jeremymuller** [comment]
Please update again:
- v1.3.2
- commit hash: 098a3ac

**Comment by jeremymuller** [comment]
Please update to latest version:
- v1.3.3
- commit hash: b85a975

**Comment by jeremymuller** [comment]
Hey, it's been a while. Please update to the latest:
- v1.3.4
- commit hash: 427b948

**Comment by cschol** [comment]
Build error on Windows platform: https://github.com/jeremymuller/Sha-Bang-Modules/issues/31

**Comment by jeremymuller** [comment]
New commit to fix the build error: 262c393
Still v1.3.4

**Comment by jeremymuller** [comment]
Hello, please update to latest version. This is my final update for Rack v1, I'll start migrating to v2 after this:
- v1.3.5
- commit hash: 241b752

**Comment by jeremymuller** [comment]
Ok sorry, one more update before migrating. Had to fix some minor bugs:
- v1.3.6
- commit hash: 56c3300

**Comment by jeremymuller** [comment]
Please update to my v2 for Rack2:
- v2.0.0
- commit hash: 45ffe02

**Comment by cschol** [comment]
`make dist` fails: https://github.com/jeremymuller/Sha-Bang-Modules/issues/40

**Comment by jeremymuller** [comment]
Ok hopefully this fixes it:
- v2.0.0
- new hash:  6f5acc9

**Comment by jeremymuller** [comment]
New update please:
- v2.0.1
- commit hash: 82c8978

**Comment by cschol** [comment]
Failed to load SVG: https://github.com/jeremymuller/Sha-Bang-Modules/issues/44

**Comment by jeremymuller** [comment]
Sorry, I always forget to add new files. Fixed now:
- v2.0.1
- hash: b94c226

**Comment by jeremymuller** [comment]
Please update to:
- v2.0.2
- hash: 1007c70

**Comment by jeremymuller** [comment]
Please update to latest version:
- v2.1.0
- commit hash: 8eab63d

**Comment by cschol** [comment]
Failed to load SVGs: https://github.com/jeremymuller/Sha-Bang-Modules/issues/57

**Comment by jeremymuller** [comment]
Hopefully this fixes it:
- v2.1.0
- new commit: d75e215

**Comment by jeremymuller** [comment]
Wait, somehow that is the wrong commit hash. A branch got merged mistakenly...don't use that one

**Comment by jeremymuller** [comment]
Ok sorry, here is the correct hash and version:
- v2.1.0
- new (correct) commit: 1bc4f26

**Comment by jeremymuller** [comment]
Just wanted to confirm, did you get the new commit hash?

**Comment by cschol** [comment]
Doing integration with the correct SHA now.

**Comment by jeremymuller** [comment]
Please update to latest version: 
- v2.1.1
- commit hash: [a410298](https://github.com/jeremymuller/Sha-Bang-Modules/commit/a410298b5ebc856dd60e1acb6f6e3613233bf8d2)

**Comment by jeremymuller** [comment]
Please update to the latest version:
- v2.2.1
- commit hash: [f2cea41](https://github.com/jeremymuller/Sha-Bang-Modules/commit/f2cea419bb299fedc4683b7195027e5749006f6b)

**Comment by jeremymuller** [comment]
Please update to latest version:
- v2.2.2
- commit hash: [bb65e3b](https://github.com/jeremymuller/Sha-Bang-Modules/commit/bb65e3b40880317e61ca1d9c62af33566ab9a1b6)
