### ISSUE TITLE
WeldSplatter

### ISSUE THREAD

**Issue by pknodle** [VCVRack/community#663]
Hi, 
I've started work on a new plugin.  Below are the URL and commit hash for the initial release. 
Let me know if there is anything that you need from me to add this to the library. 

Thanks so much for all the work put in to the Rack library, this is a really amazing resource.

https://github.com/pknodle/WeldSplatter

a39cf9d8403520943f9f0d06ea83b8dece2432a3

**Comment by cschol** [comment]
Update URL to proper format in `plugin.json`: https://github.com/pknodle/WeldSplatter/issues/1

**Comment by pknodle** [comment]
Awesome.

I updated the URL in plugin.json and bumped the version number to 1.0.1.
It's at commit
0224e0440d208d471803818d33cf166cec072091

**Comment by AndrewBelt** [comment]
Hi @pknodle, I'm inviting you to consider licensing your software under the [GPLv3+](https://www.gnu.org/licenses/quick-guide-gplv3.html) (SPDX identifier `GPL-3.0-or-later`). Creative Commons licenses are not designed to be used for software and not recommended by the Creative Commons Corporation. https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Nearly all free/open-source software developers want the [Four Essential Freedoms](https://www.gnu.org/philosophy/free-sw.html) for their users and the rights explained in the [Open Source Definition](https://opensource.org/osd-annotated). However, the act of someone taking your hard work, putting a proprietary license on it, and selling it for personal gain is not one of these desired freedoms, yet BSD and similar licenses explicitly allow this behavior. This is not just a hypothetical scenario! It happens frequently in this $1 billion audio software industry and in my experience is more likely to happen to your own software than not.

Of course, the license you choose is ultimately your decision if you are fine with people using your work in proprietary software, but a safer alternative might be to go ahead and use GPL but include a note saying "Contact example@example.com for a GPL exception" where you can negotiate terms based on the exact scenario.

**Comment by pknodle** [comment]
Ah fair point about the license.  I've changed the license to GPL3+ and bumped to version 1.0.2
The git hash is: 98a9448e9872f51b984c690387dbcfc1c15b8553

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
