### ISSUE TITLE
LilacLoop

### ISSUE THREAD

**Issue by grough** [VCVRack/community#664]
Source: https://github.com/grough/lilac-loop-vcv
Version: 1.0.0
Commit: 49a9d724550561d3ec315d7000aee1a17d436947

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. Thank you for providing your plugin to the Rack community.

**Comment by grough** [comment]
LilacLoop update:

Version: 1.0.1
Commit: faa7103a60537b9bca30a136d65425867a822192

**Comment by grough** [comment]
Version: 1.0.2
Commit: 089307bcb8748c31745f7bc67545cae9ef4c8e0f

**Comment by grough** [comment]
~Version: 1.0.3~
~Commit: 9723983dc7d5e62f7af2d03c3cf81011ceec7c7f~

**Comment by cschol** [comment]
@grough Looks like this code has been updated to `v2`? Can you doublecheck the SHA you want to submit?

**Comment by grough** [comment]
@cschol My mistake, thanks. ~Corrected below:~

~Version: 1.0.3
Commit: 2e4a1b8c62972bec12bea478d3b3d5895a89a164~

**Comment by grough** [comment]
@cschol If possible, could you cancel my request for this 1.0.3 release? I have found a bug and would prefer to fix it before releasing this version.

**Comment by cschol** [comment]
OK. How long will you need? At this point, we can probably hold all updates until you re-submit.

**Comment by grough** [comment]
A few hours at most. I'll post a new SHA shortly. Just wanted to catch you in case the next release was imminent.

**Comment by grough** [comment]
@cschol updated

Version: 1.0.3
Commit: 7cbb78c9ba4daa235c729adfeec0fb55f82d2353

**Comment by grough** [comment]
Version: 2.0.0
Commit: 7e7bc2445590216c5f4730fdf73a25a7a796286f

**Comment by grough** [comment]
Version: 2.0.0
Commit: 8393ab950e4e85523ce41c166bf533747d6dc2d4

**Comment by grough** [comment]
Version: 2.0.1
Commit: ac2fe00e36fb0b0deada886c69b7799d1c4812b2

**Comment by grough** [comment]
Version 2.1.0
Commit: a532bef58d770880e5d69ea063c0a6092f29015a

**Comment by grough** [comment]
Version: 2.1.1
Commit: b55e05559479152e370adb71109c3b0918593e55

**Comment by grough** [comment]
Version: 2.1.2
Commit: c4ed4dba732fb5f69ac5bb6c74843a65eab86442

**Comment by grough** [comment]
Version 2.1.3
Commit: 48e2a78b4896ab3951a3291922ec05d77f3473a7

**Comment by grough** [comment]
Version: 2.1.4
Commit: f52edbcc7c9b1c0f14eabdf964387fb975807c18

**Comment by grough** [comment]
Version: 2.1.5
Commit: 2d6220346f31a28888c889a6f6d98fcc7d5c4180

**Comment by grough** [comment]
Version: 2.1.6
Commit: 04411186ac4682bda86a36a42f940a8243b12bc2

@cschol @AndrewBelt I would appreciate anything you can do to expedite the release of this update. I accidentally unhid some unfinished modules in my previous update v2.1.5. This update v2.1.6 hides them again.

**Comment by AndrewBelt** [comment]
Apologies about the delay!
