### ISSUE TITLE
Stalys

### ISSUE THREAD

**Issue by denischevalier** [VCVRack/community#667]
- Source: [https://github.com/denischevalier/StalysVCVPlugin/tree/1.0.0](https://github.com/denischevalier/StalysVCVPlugin/tree/1.0.0)
- Version: 1.0.0
- Commit: a9706075384650a426c0f88198c90cefe7e9de1c

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in the **this** issue when a new version is available and we will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by denischevalier** [comment]
Some visual bug fixes (aligment of elements) + minor changes to the manifest and documentation
URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.0.1
Version: 1.0.1
Commit: 47aa0ce78545f579bd162906be423739e41e5167

**Comment by cschol** [comment]
Version number needs update: https://github.com/denischevalier/StalysVCVPlugin/issues/5

**Comment by denischevalier** [comment]
Fixed, b4873e415510b18c0f69d0e308bf089b6cc2e21d

**Comment by denischevalier** [comment]
Add 8 Comparator module
URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.1.1
Version: 1.1.1
Commit: fc0a69bb1bccd7242caef1b9380e2c69f7007cf0

**Comment by denischevalier** [comment]
Hello!

Release of version [1.2.0](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.2.0) of Stalys plugin with 6 new modules:

- URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.2.0
- Tag: 1.2.0
- Commit: [fb93b0112cd8eed09bdd4247d19cd0ebcec4e161](https://github.com/denischevalier/StalysVCVPlugin/commit/fb93b0112cd8eed09bdd4247d19cd0ebcec4e161)

**Comment by denischevalier** [comment]
Hello!

Release of version [1.2.1](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.2.1) of Stalys plugin with performance improvements:

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.2.1
* Tag: 1.2.1
* Commit: [eaea966a74d921cf728de27e2ad551a0b11e8b4f](https://github.com/denischevalier/StalysVCVPlugin/commit/eaea966a74d921cf728de27e2ad551a0b11e8b4f)

**Comment by denischevalier** [comment]
Good morning!

Release of version[1.3.0](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.3.0) of Stalys plugin, with 12 new modules.

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.3.0
* Tag: [1.3.0](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.3.0)
* Commit: [03c2749c2963cee5e05d86207b106ede35ecda40](https://github.com/denischevalier/StalysVCVPlugin/commit/03c2749c2963cee5e05d86207b106ede35ecda40)

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/denischevalier/StalysVCVPlugin/issues/59

**Comment by denischevalier** [comment]
Hello!

Issue fixed, sorry about that. New version is [1.3.1](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.3.1).

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.3.1
* Tag: [1.3.1](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.3.1)
* Commit: [e33777805c6d999d510de2fce1946034513ebba8](https://github.com/denischevalier/StalysVCVPlugin/commit/e33777805c6d999d510de2fce1946034513ebba8)

**Comment by denischevalier** [comment]
Hello!

New version is out: [1.4.0](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.0), with new panel design and new blank panel.

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.4.0
* Tag:  [1.4.0](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.0)
* Commit: [c20528a6abf4da775751102e44879809ce6360a3](https://github.com/denischevalier/StalysVCVPlugin/commit/c20528a6abf4da775751102e44879809ce6360a3)

**Comment by AndrewBelt** [comment]
https://github.com/denischevalier/StalysVCVPlugin/blob/main/Makefile#L7 breaks a lot of stuff like `std::isfinite()`. I'm not sure why it's needed since `-funsafe-math-optimizations` should cover most reasonable floating point optimization. If it's needed in DSP code, you could add the optimization on a per-function basis with `__attribute__((optimize("-ffast-math")))`. But I can't think of a reason why that would improve your code's speed that much.

**Comment by denischevalier** [comment]
ok, I'll revert this commit

**Comment by denischevalier** [comment]
Here is the new version without the use of `-ffast-math`: [1.4.1](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.1).

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.4.1
* Tag:  [1.4.1](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.1)
* Commit: [f01bd7ec81aff712f18cefd6cbc4eb7ccf2dd190](https://github.com/denischevalier/StalysVCVPlugin/commit/f01bd7ec81aff712f18cefd6cbc4eb7ccf2dd190)

**Comment by cschol** [comment]
Compilation fails for Windows platform: https://github.com/denischevalier/StalysVCVPlugin/issues/78

**Comment by denischevalier** [comment]
Ok, I originally planned to add CI in the next version, but I guess I'll add it now :) I'll hopefully come back in a few days with it. Thanks for the review @cschol !

**Comment by denischevalier** [comment]
Hello, CI added, and windows build fixed: [1.4.2](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.2)

* URL: https://github.com/denischevalier/StalysVCVPlugin/tree/1.4.2
* Tag: [1.4.2](https://github.com/denischevalier/StalysVCVPlugin/releases/tag/1.4.2)
* Commit: [https://github.com/denischevalier/StalysVCVPlugin/commit/0d2a2f64c7fd53c8685f3a87c2fb9048e3551aee](https://github.com/denischevalier/StalysVCVPlugin/commit/0d2a2f64c7fd53c8685f3a87c2fb9048e3551aee)
