### ISSUE TITLE
AlgoritmArte

### ISSUE THREAD

**Issue by algoritmarte** [VCVRack/community#668]
Hi,
I would like to add my modules to the VCV Library.

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: ecf1103
branch: master

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in the **this** issue when a new version is available and we will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by algoritmarte** [comment]
Hi,
I released the v1.1.0 of the plugin that contains another new module "Planetz"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: 1f4ec86
branch: master

**Comment by algoritmarte** [comment]
Hi,
I released the v1.2.0 of the plugin that contains another new module "MusiFrog"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: 83e51a2
branch: master

Thanks!!!

**Comment by algoritmarte** [comment]
Hi,
I released the v1.3.0 of the plugin that contains another new module "Zefiro"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: a0bfe70
branch: master

Thanks!!!

**Comment by algoritmarte** [comment]
Hi,
I released the v1.4.0 of the plugin that contains another new module "HoldMeTight"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: ec6cb20
branch: master

Let me know if the frequency of updates/new releases is too high (I suspect that it's not easy for you to follow hundreds of plugins)
Thanks!!!

**Comment by cschol** [comment]
You're good. No worries.

**Comment by algoritmarte** [comment]
Hi,
I released the v1.5.0 of the plugin that contains another new module "CyclicCA"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: 74d138c
branch: master

**Comment by algoritmarte** [comment]
Hi,
I released the v1.6.0 of the plugin that contains another new module "MusiMath"

source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: d083612
branch: master

**Comment by algoritmarte** [comment]
Hi,
I made a new release v1.6.1 with some bug fixes:
source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: f5a1bf2
branch: master
Best regards, M.

**Comment by algoritmarte** [comment]
Hi,
I made a new release v1.6.2 with some changes to musimath:
source code: https://github.com/algoritmarte/AlgoritmarteVCVPlugin
latest commit hash: b590e84
branch: master
Best regards, M.

**Comment by algoritmarte** [comment]
Hi,
I already created a new v2 branch that compiles/works correctly on VCV v2 (and I find it in the "Review" column)

https://github.com/algoritmarte/AlgoritmarteVCVPlugin/tree/v2

It's not clear to me if it's enough ?!?
I'm not a Git expert, so what are the other (mandatory/suggested) steps to do?
If I merge the branch to main the v1 will not compile on the old SDK anymore ?!? 

Let me know, best regards, M.

**Comment by algoritmarte** [comment]
Hi,
VCV 2 is out, but I don't know how to "publish" the v2 version of my plugins (see previous comment) which is also published on:

https://github.com/algoritmarte/AlgoritmarteVCVPlugin/tree/v2
