### ISSUE TITLE
Agave

### ISSUE THREAD

**Issue by jatinchowdhury18** [VCVRack/community#670]
Agave modules. Originally by Fabian Esqueda. Updated for version 1.0 and published with permission by Jatin Chowdhury.

source code: https://github.com/jatinchowdhury18/Agave
version: 1.0.0
commit hash [13756854dcdd644e0515f114bef286c6045f0653](https://github.com/jatinchowdhury18/Agave/tree/13756854dcdd644e0515f114bef286c6045f0653)

**Comment by cschol** [comment]
The Github project does not allow to file Issues. Please enable Issues.

There is a problem with one of the panels.

```
[1.277 warn src/window.cpp:75] Failed to load SVG /home/cschol/src/Rack-1.0-Home/plugins-v1/Agave/res/FXLD.svg
```
On a Linux system, the file name is `Fxld.svg`. 

However, the code requests the panel to be:
```
101:    setPanel(APP->window->loadSvg(asset::plugin(pluginInstance, "res/FXLD.svg")));
```

**Comment by jatinchowdhury18** [comment]
Ah thanks for catching that! It should be fixed now, with this commit: [`f7cec6`](https://github.com/jatinchowdhury18/Agave/tree/f7cec64c67ffb29381221c0c1c2e32d56f22aef2). I've enabled GitHub Issues in the repo now as well.

Thanks,
Jatin

**Comment by cschol** [comment]
Thank you for updating that and adding the issues.

Plugin will be integrated with the next Plugin Manager update for all platforms.
