### ISSUE TITLE
RareBreeds_Orbits

### ISSUE THREAD

**Issue by RareBreeds** [VCVRack/community#671]
Hello,

I would like to add my plugin to the VCV Library.

source code: https://github.com/RareBreeds/Orbits
version: v1.1.0
commit hash: 1ec545d

**Comment by cschol** [comment]
Your plugin has been integrated and will be available in the Plugin Manager for all supported platforms with the next build update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by RareBreeds** [comment]
Hello again,

I have an update for my plugin.

source code: https://github.com/RareBreeds/Orbits
version: v1.1.1
commit hash: 35a5bb1

**Comment by RareBreeds** [comment]
Hello, I have an update for my plugin.

source code: https://github.com/RareBreeds/Orbits
version: v1.2.0
commit hash: b14a55e

**Comment by RareBreeds** [comment]
Update for Rack v2.

Source: https://github.com/RareBreeds/Orbits
Branch: v2
SHA: 27efa0f644ff6598be82aba7dbc94ff6645e26de
Version: 2.0.0

**Comment by RareBreeds** [comment]
Bug fix from v2 update and new factory presets.

Source: https://github.com/RareBreeds/Orbits
Branch: v2
SHA: ab940b03c841b192c28802c9fb985958fa381fb4
Version: 2.0.1

**Comment by RareBreeds** [comment]
Minor update, fixes crash when controlled by 8face.

Source: https://github.com/RareBreeds/Orbits
Branch: v2
SHA: 09fe99895dd7924a842c6e70088eee00a0509c31
Version: 2.0.2

**Comment by RareBreeds** [comment]
Unfortunately someone found another bug with non-ascii character paths on Windows, so I've made another build for that.

Source: https://github.com/RareBreeds/Orbits
Branch: v2
SHA: a3bca69358ed844c3ef6831d6a39c1a4f3284ec9
Version: 2.0.3

**Comment by RareBreeds** [comment]
Some new features

Source: https://github.com/RareBreeds/Orbits
Branch: v2
SHA: 71660d98df1435d3548563e3865bcf93eb1ac467
Version: 2.0.4
