### ISSUE TITLE
Comfortzone

### ISSUE THREAD

**Issue by hampa** [VCVRack/community#672]
I would like to add my plugin to the VCV Library.

source code: https://github.com/hampa/comfortzone/
version: v1.0.0
branch: main

**Comment by cschol** [comment]
Invalid entries in manifest `plugin.json`: https://github.com/hampa/comfortzone/issues/1

**Comment by hampa** [comment]
I've pushed an updated version with valid entries in the manifest.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by cschol** [comment]
Plugin update requested by @hampa for `v2.0.0`.

@hampa One recommendation I have is that you add the complete `GPLv3` license text to the `LICENSE` file and update the copyright year. Also, you should provide attribution in the `README` for the VCV Ripples code that is used in the plugin.

**Comment by hampa** [comment]
I've updated for 2.0 and added full GPL-3 license file and attribution to VCV Ripples Filter code.

Branch: main

**Comment by cschol** [comment]
Thank you for the update.

**Comment by hampa** [comment]
New module TZFMLead

source: https://github.com/hampa/comfortzone
branch: main
HEAD: faad00d551bfecd83b9b7363795aadbcd8483059
version: 2.1.0
