### ISSUE TITLE
"Charred Desert" not listed in plugin author menu

### ISSUE THREAD

**Issue by jamshark70** [VCVRack/community#673]
See screenshot. CharredDesert exists (else it wouldn't display at left) but according to the dropdown, it simultaneously doesn't exist :laughing:

![charred-desert](https://user-images.githubusercontent.com/318301/103279896-e90c7180-4a09-11eb-8d03-50b8a096c835.png)

**Comment by Ahornberg** [comment]
the brand's name defined in the plugin.json is 'SV Modular'

**Comment by jamshark70** [comment]
Ok, distinction between brand and package I guess. Seemed odd at first anyway.
