### ISSUE TITLE
captvolt

### ISSUE THREAD

**Issue by cnvogelg** [VCVRack/community#674]
Hi,
I would like to add my modules to the VCV Library.

source code: https://github.com/cnvogelg/captvolt-vcv
latest commit hash: 1a322f
branch: master
release tag: v1.0.0

**Comment by cschol** [comment]
Your plugin has been integrated and will be available with the next Plugin Manager update for all supported platforms. Let us know in **this** issue when a new version is available and we will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by cnvogelg** [comment]
A new release is available. Please update the library.

release tag: v1.0.1
branch: master
commit:  ac320d9a

**Comment by cschol** [comment]
That revision `ac320d9a` does not exist in the repository. Can you please check that?

**Comment by cnvogelg** [comment]
hmm... here is the linked commit
https://github.com/cnvogelg/captvolt-vcv/commit/ac320d9a07a55c6a1a08c147ace0ed741c66300e

**Comment by cschol** [comment]
OK. I see the commit now.

**Comment by cnvogelg** [comment]
Ah I found my error: ac320d9 is the correct short commit id. My number above had one more digit... :(

**Comment by cnvogelg** [comment]
A release is available for V2. Please update the library.

release tag: v2.0.1
branch: master
commit: 67cf46f
link: https://github.com/cnvogelg/captvolt-vcv/tree/v2.0.1

**Comment by cschol** [comment]
Something is wrong with this last commit. 

GitHub shows this error message:"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

The commit referenced is not available in the repository when I pull it. Can you please check. Thanks.

**Comment by cnvogelg** [comment]
Sorry, I forgot to push the changes to master. Now done.
Could you give it a try again?

https://github.com/cnvogelg/captvolt-vcv/commit/67cf46f4e61a32433ef737ce1a2122a5b1643527

**Comment by cnvogelg** [comment]
A new release is available. Please update the library.

release tag: v2.1.0
branch: master
commit: f50cb1b58272b4c843de4db4c427e86d0829a683
