### ISSUE TITLE
Axioma

### ISSUE THREAD

**Issue by kauewerner** [VCVRack/community#675]
Hello,

I would like to add my modules to the VCV Library.

source code: [https://github.com/kauewerner/Axioma](https://github.com/kauewerner/Axioma)
version: v1.0.0
branch: main
commit hash: e3cf9eb

**Comment by cschol** [comment]
Invalid tags in `plugin.json`: https://github.com/kauewerner/Axioma/issues/1

**Comment by kauewerner** [comment]
I am sorry about wrong tags :( 

Here is the updated and corrected last version:

source code: https://github.com/kauewerner/Axioma
version: v1.0.0
branch: main
commit hash: 00c6f6c

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by kauewerner** [comment]
Hello,

I have a new update for the VCV Library.

source code: https://github.com/kauewerner/Axioma
version: v1.1.0
branch: main
commit hash: 31b67e4

**Comment by kauewerner** [comment]
Please ignore the hash I wrote in the last comment, this is the correct one:

commit hash: 632f416

**Comment by kauewerner** [comment]
Hello,

I updated the Axioma plugin to v2.

source code: https://github.com/kauewerner/Axioma
version: v2.0.0
branch: main
commit hash: 3e7e01e[https://github.com/kauewerner/Axioma/commit/3e7e01e6a449dc1e6c523bd4487c0a3200b322cb](url)
