### ISSUE TITLE
ODDSound_MTS_ESP

### ISSUE THREAD

**Issue by olicash** [VCVRack/community#678]
Hi,

apologies for new Issue, but I don't have privileges to re-open the previous one.  Hopefully panels sufficiently different now?

Thanks, Oli.

---

source code: https://github.com/ODDSound/MTS-ESP-VCVRack
version: v1.0.0
branch: main
commit hash: eda6117

**Comment by cschol** [comment]
Just post your details in the old issue and we will reopen it as part of our integration workflow. It helps us with our tracking of integration builds. Thank you.

**Comment by olicash** [comment]
Ah ok I see, done.  Thanks!
