### ISSUE TITLE
Plurm

### ISSUE THREAD

**Issue by terrytheplatypus** [VCVRack/community#679]
I would like to add this plugin to the VCV library.
https://github.com/terrytheplatypus/Plurm
v 1.0.0
commit: 0c06e0488405df378bc3f2bf89eaa3e75cb8f3ab  (on master branch, not main)

**Comment by cschol** [comment]
Panel issue: https://github.com/terrytheplatypus/Plurm/issues/1

**Comment by terrytheplatypus** [comment]
as i said in the issue on my repo, i intended for it to be transparent, but if it needs to be opaque i can change it to be opaque. The important UI components are all opaque so i don't see the transparency causing any difficulty for the user.

**Comment by cschol** [comment]
Responded to the issue in your repo.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available with the next Plugin Manager update for all supported platforms. Please let us know in **this** issue when a new version is available and we will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by terrytheplatypus** [comment]
Hello, i would like to release a 1.1.0 version of this plugin, the commit hash is a279cde9450cfbc7f651e783c978f6132d8dcbf6

**Comment by terrytheplatypus** [comment]
Hello, sorry for asking this again so soon after the last change, but i would like to publish a 1.1.1 version of this plugin, the commit hash is cfe918ce6edecc456bc14f916785a04ca92cdc53

**Comment by terrytheplatypus** [comment]
Hello i would like to update both the v1 and v2 versions of this plugin (or just the v2 version if only that is updated going forward). master branch is for v2 and v1 branch is for v1. on the v1 branch the commit is cd1d9c298804c9475406ab62fd4f97d09f5b2aca and on the master branch it's the same.

**Comment by cschol** [comment]
Hey, I don't see any of the `v2` code on GitHub. Can you please check if you pushed all of your changes?

**Comment by terrytheplatypus** [comment]
i tested it, just forgot to push the version change. ad370c85fb6d32c73b1e81724c43ea6155cd25d4 is the commit with the version change.

**Comment by AndrewBelt** [comment]
Reopening for v2

**Comment by terrytheplatypus** [comment]
Hi, I would like to add my recent changes on the master branch to the library, commit 44d1920ce3fa0862653ad5b4ce179aba44b1c3aa
