### ISSUE TITLE
Extratone

### ISSUE THREAD

**Issue by EaterOfSheep** [VCVRack/community#680]
https://github.com/EaterOfSheep/sheepextratone

Very basic but useful modules for testing. Seeing how this works, never used git or github before! Do let me know if I've done anything wrong <3
Version 1.0.0
commit d68e634dca60566ce26b2b9a8658412e2f2253bf

**Comment by EaterOfSheep** [comment]
Commit 70bc7c9cf9659a3f8e1f3df6c88e820d59702f9f
I have reverted the slug to "Extratone".

**Comment by EaterOfSheep** [comment]
New commit, I forgot to revert the module slugs too. Should be fixed now:
be6ab554282dc8d60191d96ffa943f7f45c07c44

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available and we will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AndrewBelt** [comment]
I'll go ahead and make a build of this version, but I'll highly encourage you to add a copy of the [GPLv3 license](https://www.gnu.org/licenses/gpl-3.0.txt) to `LICENSE.txt` of your repository if you wish to release free/open-source software. The `plugin.json` isn't really a declaration of license, just metadata about the plugin.

**Comment by EaterOfSheep** [comment]
New version!
commit: 85a1dac2b63b506a577cd4ccc340bd32bf223d55

**Comment by EaterOfSheep** [comment]
Extended further: 968f204d7b8355f81e6d61c06210c2429cef3683
I have kept the version at 1.1.0 as the previous submission has not been released yet. Apologies for firing these submissions off, I'm finding this far too exciting!

**Comment by EaterOfSheep** [comment]
Update: 649ecaef0aa556ea8b8eae0a6be309d6dd3d20ec
Again, keeping version as 1.1.0 as previous update isn't out yet. Sorry again for spamming updates, I'll slow wayy down after this one. Thanks VCV team <3

**Comment by EaterOfSheep** [comment]
New update version 1.1.1
d99de40179628004df220ca090a60ff36b1967f2

**Comment by EaterOfSheep** [comment]
update:
f7b179068b5f397b83a9c9537c1a10404086fc56

**Comment by EaterOfSheep** [comment]
new update v1.1.2:
c71bc1b2adf490730d6bae32071f98a62b735df0

**Comment by EaterOfSheep** [comment]
oopsie, I forgot something! new update:
434e0bcea4841fb72feff9a07af739c040e0b039

**Comment by EaterOfSheep** [comment]
Hiya, new update:
631f8a198f071c621e2f35e8be570994262c580a

**Comment by EaterOfSheep** [comment]
Apologies, I forgot to update version number on previous update! New update:
86b4ab2b02911abe809d6442e3230ec81041d44a

**Comment by EaterOfSheep** [comment]
New update
05d9fb54c4b4ce546f83638a5a887532dfa585dc

**Comment by EaterOfSheep** [comment]
New update:
b98b0f993beacdf05d812c940134f6f405ed4bab

**Comment by EaterOfSheep** [comment]
New update:
b989d833599997aac5caa4bdb2a1cb89bd086a3a

**Comment by EaterOfSheep** [comment]
New update. Sorry for any confusion, deleted earlier comment as I found an error (I was rushing - always a mistake!)
8f6324cd48097a66d9a2998c39f61e0b4f3ccc05

**Comment by EaterOfSheep** [comment]
New update:
270e32e4a2226b6c327f9ff5f0f81b24b5725304

**Comment by EaterOfSheep** [comment]
New update: 03fcf9d700502899d5382886eefbf6f50958bee4

**Comment by EaterOfSheep** [comment]
new update, corrected author email:
22d6101aef0cc5217cff45689b4f7449570e9f97

**Comment by EaterOfSheep** [comment]
new update
623e25da7f64c7228f03387c31fde2a5fcc7abb5

**Comment by EaterOfSheep** [comment]
Update for Rack 2:
3d327f6bacf41eb18bec7e63c61531685ee799de
