### ISSUE TITLE
RPJ

### ISSUE THREAD

**Issue by kockie69** [VCVRack/community#682]
https://github.com/kockie69/RPJ

**Comment by cschol** [comment]
Build error on macOS platform: https://github.com/kockie69/RPJ/issues/1

**Comment by kockie69** [comment]
Fixed the issue

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by kockie69** [comment]
latest version: 1.0.1
commit hash: abed64d422827d85b319ff0a1641ff005f7e0633

**Comment by kockie69** [comment]
latest version: 1.0.2
commit hash: 936f5cbe220a07c63cb8d193377c099deb538747

**Comment by kockie69** [comment]
latest version: 1.0.3
commit hash: 6eca3645706249bd397d2478f68b53cd8ee33359

**Comment by AndrewBelt** [comment]
@cschol Looks like the git submodule is still 1.0.2.

**Comment by kockie69** [comment]
It looks like my mistake. I think I have given the wrong commit hash.

latest version: 1.0.3
commit hash: a610ae5136469701bbd01049c61703e2790b2b56

**Comment by cschol** [comment]
Weird. I need to look into why my version detection code didnt pick up that the version number didn't change.

**Comment by cschol** [comment]
Remove `dist` directory from repo: https://github.com/kockie69/RPJ/issues/5

I just noticed this. Please fix this before integration of this version. Thank you.

**Comment by kockie69** [comment]
Removed the dist (and also vscode). All done with BFG. Hope all is okay now.

latest version: 1.0.3
commit hash:2f69262444f19bbea3cf6af9290b6b161f62ae4f

**Comment by kockie69** [comment]
Latest version: 1.0.4
commit hash: 254e6ed46dd615078c701b00aa0804af33b47684

**Comment by kockie69** [comment]
RPJ VCV Modules
Please add these modules to the VCV Library
-- These modules are for VCV v2 

Latest Version: 2.1.0
commit hash: c8ab0363c0174ac05f4411370bd7cd2d2c5ac95d

**Comment by cschol** [comment]
Buttons fail to load on Linux platform: https://github.com/kockie69/RPJ/issues/21

**Comment by kockie69** [comment]
Changed Foldername and includes. I have not changed the version.

Commit hash: aac0da35f5650ba3794887999c42a3b231a12a2d

**Comment by kockie69** [comment]
-- These modules are for VCV v2

Latest Version: 2.0.5
Commit Hash: 5fccf724c15e3d45f09bed92be821540e8647cde

**Comment by kockie69** [comment]
Latest Version: 2.0.6
Hash: 737bfe3a367d7126648e0bdec7f4117e002cf060

**Comment by kockie69** [comment]
Latest Version: 2.1.0
Hash: 870c2d3cc16808fd1dd6b886bb02e4bb518e42b2

**Comment by kockie69** [comment]
Some Linux distros could not check config file correctly, so a hotfix

Latest Version: 2.1.1
Hash: 42adaee63ceadb406c565f360cfe361cbad67758

**Comment by kockie69** [comment]
Latest Version: 2.2.1
Hash: dceb89fa16fb2005b48f0b5d7c7eaccab138e4b0

**Comment by kockie69** [comment]
Latest Version: 2.2.2
Hash: f4a3a079a53aea813457f3aafeaca7bc5ec8cf1f

**Comment by kockie69** [comment]
Latest Version: 2.2.3
Hash: 363e3b4ec5af9a51d6d8d4e253cef6e3879638bd

**Comment by cschol** [comment]
Compilation fails for `arm` platform: https://github.com/kockie69/RPJ/issues/76

**Comment by kockie69** [comment]
Issue with arm build fixed:

Latest version: 2.2.3
Commit Hash: 0f5e1e3c724f3d887a2a368355243a0afdf83d1f

**Comment by kockie69** [comment]
Latest version: 2.2.4
Commit Hash: a8304468347219fed855ad418a196f7ad9ee6d16
