### ISSUE TITLE
mmmodules

### ISSUE THREAD

**Issue by Myst-Mach** [VCVRack/community#683]
https://github.com/Myst-Mach/mmmodules/tree/main

Hey VCV crew, This is my first time uploading a module so I'm not sure if I've done everything right, if I've missed anything please let me know
-Cheers, mm :)

**Comment by cschol** [comment]
Invalid tags and license in `plugin.json`: https://github.com/Myst-Mach/mmmodules/issues/1
Remove debug printf from code: https://github.com/Myst-Mach/mmmodules/issues/2

**Comment by AndrewBelt** [comment]
In addition to @cschol's suggestions, `settings.json` is not needed in the repo.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Myst-Mach** [comment]
hey, completely forgot to send this, here's the commit hash for 3mountains v2: c9b5c7f91b573ddb4caa21bd0026f2cb96970951

**Comment by cschol** [comment]
Issues in `plugin.json`: https://github.com/Myst-Mach/mmmodules/issues/3
