### ISSUE TITLE
SunsetSignals

### ISSUE THREAD

**Issue by ghost** [VCVRack/community#685]
https://gitlab.com/jeremy_mitchell/sunsetsignals

Hi,
This is my first plugin for vcv-rack and I read and tried to follow the publishing guide,
so just let me know if there is anything else I need todo to have this plugin (SignalBooster) published.

Thanks!
Jeremy

**Comment by ghost** [comment]
35cee6e7576175802fd07c948fdbc3f22615fe71 - version 1.0.0

**Comment by cschol** [comment]
Invalid tags in `plugin.json`:

```
sunsetsignals] Validating plugin.json...FAILED    
[sunsetsignals] Issues found in `plugin.json`:                                                                                                                                                                                                                                                                        
                                                                             
SignalBooster: invalid module tags: booster, db, signal-booster                                                                                                                                                                                                                                                       
-- Valid tags are defined in https://raw.githubusercontent.com/VCVRack/Rack/v1/src/tag.cpp                                                                 
```

**Comment by ghost** [comment]
Ah thanks, I updated the plugins.json with the Utility tag.
2f3a99155f3832464c17106e75c605a910608680

**Comment by cschol** [comment]
Looks good. One recommendation: with your next update, add an explicit copy of the license to the repository in a file called `LICENSE`, rather than just linking to the external license text. That way, the license file can also be included in the plugin distribution.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available with the next Plugin Manager update for all supported platforms. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
