### ISSUE TITLE
KRTPluginA

### ISSUE THREAD

**Issue by jackokring** [VCVRack/community#686]
https://github.com/jackokring/VCV the filter is done.

https://github.com/jackokring/VCV/commit/1a3dc44095273a3477e9d9197a03b611303d5763 as commit for final filter adjustment excluding perhaps bugs.

**Comment by cschol** [comment]
Build fails: https://github.com/jackokring/VCV/issues/1
Invalid entries in `plugin.json`: https://github.com/jackokring/VCV/issues/2

**Comment by jackokring** [comment]
I think it's now poly and uses simd.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA renamed as it's more logical.

**Comment by jackokring** [comment]
Repo name changed to match slug. Code build ok. Now for .svg.

**Comment by cschol** [comment]
Code builds on the build system now. The panel looks transparent, not sure if that's intended that way:

![image](https://user-images.githubusercontent.com/624427/126172734-5be9a15f-7716-4f83-8468-c044bfe68032.png)

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/17f3f73b597dd03fb3b24ef74e252fb1311a0e98 commit has 51% transparent and some labels (visible). I think v1.0.0 is a go.

**Comment by cschol** [comment]
Binaries committed to repository: https://github.com/jackokring/KRTPluginA/issues/3

**Comment by cschol** [comment]
@jackokring Please provide a SHA to release for this initial version.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/8f4ca93ab0c0ba03ec205cb19c86af013dcf1010 has the mu module working too. The bit clipping crush effect on Gibbs phenomenon is purposeful in the design,

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/3be398c4a9cfa37f3ff6e6ebabe909a1386e318a minor changes v1.1.1 any bugs in the Mu algorithm accepted (in some ways it's about the perfection truncated), and the .1 fix is the time projection of a control signal. The commits past this will likely not always compile until another module is created ... now for an exciting idea?

**Comment by jackokring** [comment]
Tag v1.2.3 is latest https://github.com/jackokring/KRTPluginA/commit/629de26c81b0725e5210b3066e533f741fcc5709 and today is just some documentation commits with some looking over examples of text drawing code programatically.

**Comment by jackokring** [comment]
Added some
`configParam(G1, -6.f, 6.f, 0.f, "Gain", " Center dB (rel 6)");` *3 beauty ...

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/65f8094e12e3ca916189e06ef85f0506968c652f is v1.2.4 (2 machines working, 4 fixes to errors in function)

**Comment by jackokring** [comment]
Just pushed a test of a delay effect. What's the library push limit as I could hold off a bit while the next few modules are done, as they have an easy construction time scale. I haven't bumped the version yet as tests need doing.

* 1 pre-trigger delay for time sync externals to a later bar.
* Some twist on sample future prediction

**Comment by cschol** [comment]
If you anticipate heavy development I recommend you hold off for a while until you have a stable, tested version to release. I don't mind integrating a bugfix after initial integration of a version and before that version is released, but please don't submit development updates daily.

**Comment by AndrewBelt** [comment]
Yes, it's good that your plugin is in such active development, but we can only handle plugin updates weekly or as-needed (in case of an important bug fix). If there are more version updates than VCV Library releases, that means we have to arbitrarily pick versions to release, which might not be optimal since you're likely the expert on which versions are the most stable.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/4bbb4adb7f4177c0e6f6e2e72c7079936455a396 covers some useful control range issues and adds better documentation. README includes links to very simple patches demonstrating modules, and some notes.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/43052cce4e30bd562aa107ef7698ba4f304386a8 bug fix. on buffer modulo in delay effects T and L.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/1d48b00cebf6c292458d9eedbc33a11a34f4db02 long delays fix, Mu limiting fix sounds better.

**Comment by jackokring** [comment]
Done some documentation updates but no extra functionality.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/0ba0f074fe3b21a04d0b1f65dc75b95f8299b357 two more modules complete.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/47eb2f92ea8c613faa65e67899d091bfa79f2334 minor bug fixes for the whole sweet of 8 modules. Ready to publish.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/23923ba72d9ba35b5c8bb8872291665ba0ed8421 slightly better spectra in Mu. Fix via LPF

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/33003e13037797d6fceec784798b89ea6eca412e 1.8.13 tweeks on Mu.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/1fbbcb950c9098dc0a9997559334b08b6933d1e4 v1.9.14 added a morphing filter and small change to D.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/7839dbc04e324bbd971aac9cd074689dc50c80dd minor freq tracking HP version on control.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/f8eb0d9c6af032eb8c13898755bb2e34bef40fb6 fix colors of inputs (graphical correction).

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/1744fd24d7c384013090febf8b2ee2d186647e74 added a simple gate to cv summator machine

**Comment by cschol** [comment]
@jackokring I just want to clarify something: these Github threads are for release announcements, not a general development blog. I get notifications, which help me to know when a new version is available to review and integrate the module. Please collect your changes into a stable, tested version and let us know when it is ready for release by posting a) the version number and b) the SHA in this thread. Having said that, I cannot keep up with multiple new versions per day.

**Comment by jackokring** [comment]
jackokring/KRTPluginA@1744fd2 v1.10.15 it's a few weeks of planning for the next module idea.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/5a98acd5d05cf5a0f18a8779d2c2228d56af4218

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/74e58887194f3a1738d4f41e0b0dada051fe9561 3 extra machines, using bi-colour LEDs, some oversampling ...

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/f62bddf04ff2f4c62721c03c665bda2d85a8c03b 1.18.20

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/7596923be5f88dbef8d5a8d35989ea23626bfa11 a click fix.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/fddd0b04933fcacdbd014d3687993201025463e4

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/55afcbf85aac5a84929fcd1e2507878c1e34bbe1 v1.22.22

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/f39d19ddc63cb0becfc52d3279f31a7dc7e12501 v1.23.23

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/fd8d367374cd915320a0ed66f1149dfe4030383b v1.23.24 filter initialization fix.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/b6cbdf7589a0c5d2edf2f7181b3f17d378e6c7e2 essential bug fix

**Comment by cschol** [comment]
@jackokring Just FYI, your `plugin.json` still states `1.25.24` as the version, but your tag in the repo is `1.25.25`. Do you want to update that?

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/0e4a68627c57b108023b8ea4cb82d40adc393d01 fixed, just adding docs (but external)

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/f8e23f5bc834e864b36212764bf2a5ea34527545 Rack SDK 2.0.5

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/14728515c64027a7613c0bb4951212967abf2465 some SDK 2 migration.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/61db59a02231ce77892bddd9834324b03ae64268 SDK 2 migration should be complete.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/e44cf0c2302580343ed9876e398a418f1b953931 new build. Some fixes.

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/6bddf9dccc9dc0b5ccd57d7f7e4975f9e15b1a42 I hear 2.3.0 might fail so ...

**Comment by cschol** [comment]
Build failure on macOS platform: https://github.com/jackokring/KRTPluginA/issues/6

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/d9d9817afc6fc44ddb43b3ba2d2410b4ab791bbf

**Comment by jackokring** [comment]
https://github.com/jackokring/KRTPluginA/commit/ff45222c863c2ce3ed13cf03b9c9f9c0a5148a41 minor control hard right select window.
