### ISSUE TITLE
cvly

### ISSUE THREAD

**Issue by Lyqst** [VCVRack/community#688]
New plugin

v1.0.1

commit 447fda7c64cae1a29db1def3b7f46c7ae2c23f01

**Comment by cschol** [comment]
Can you please provide a link to the repository? Thanks.

**Comment by Lyqst** [comment]
Ah, sorry. [Here it is](https://github.com/Lyqst/cvly-modules)

**Comment by cschol** [comment]
Binaries committed to repository: https://github.com/Lyqst/cvly-modules/issues/3

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Lyqst** [comment]
New version, 1.0.2
https://github.com/Lyqst/cvly-modules
Commit 7444ff172a47b42ee06047a690fd58d4213182fd

**Comment by Lyqst** [comment]
New version, 1.0.3
https://github.com/Lyqst/cvly-modules
5da86dce3326ed33d8365f77125f485c59f57089

**Comment by Lyqst** [comment]
UI issue fix, commit 75992bbe811d57964fef25b7737d89675ca9debf

**Comment by Lyqst** [comment]
New version 1.0.4
https://github.com/Lyqst/cvly-modules
581d4b3cd618a7334e285e99ccdab8bfa96678ae

**Comment by Lyqst** [comment]
Any update on this?

**Comment by Lyqst** [comment]
Update for v2
https://github.com/Lyqst/cvly-modules
commit 6716cd7a2140828010912fb24e18b9f59702f648

**Comment by cschol** [comment]
Font references stored across frames: https://github.com/Lyqst/cvly-modules/issues/9

**Comment by Lyqst** [comment]
Fixed in version 2.0.1, commit 6be025ebb57c0211a475d22ca06b7fa5ff4982fa
