### ISSUE TITLE
OSCelot

### ISSUE THREAD

**Issue by The-Modular-Mind** [VCVRack/community#689]
OSCelot
v1.0.1
c29aa8f485baca4d55a73b1e915a7fe7135169ed

https://github.com/The-Modular-Mind/oscelot

**Comment by cschol** [comment]
Invalid tags in `plugin.json`: https://github.com/The-Modular-Mind/oscelot/issues/1

**Comment by The-Modular-Mind** [comment]
Fixed in 74b53d0766e3df289f6abac4d846814167aeb109

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by The-Modular-Mind** [comment]
New version:
OSCelot
v1.0.2
37a81a76f8602bdadde4ee873b7d24bffeb6cf38

https://github.com/The-Modular-Mind/oscelot

**Comment by The-Modular-Mind** [comment]
New version:
OSCelot
v2.0.0
81c5b530bb39a9405714a974ac5d07241e303d18

https://github.com/The-Modular-Mind/oscelot
