### ISSUE TITLE
LyraeModules

### ISSUE THREAD

**Issue by VegaDeftwing** [VCVRack/community#690]
Source code: https://github.com/VegaDeftwing/LyraeModules
Commit: b2aee9283f3304fd72c7b2e642ef8b943f3a30f0
Version: 1.0.0

(sneakily edited the commit as I accidentally had left a hard coded path in, thankfully squinky labs caught it!)

**Comment by cschol** [comment]
Invalid URL in `plugin.json`: https://github.com/VegaDeftwing/LyraeModules/issues/3

**Comment by VegaDeftwing** [comment]
fixed in commit: c61c44d176c6f4f3812b1127ab54a958ebcf01a6

**Comment by VegaDeftwing** [comment]
Source code: https://github.com/VegaDeftwing/LyraeModules
Version: 1.0.1
Commit: af0d5b2c58da972c598fd13bf4500398b0bd2880

Changed calls to simd so that performance isn't trash for some users, no need to publish 1.0.0, can just jump straight to this if that's alright

**Comment by VegaDeftwing** [comment]
Version: 1.0.2
Commit: 29086f37cee1d24cae3574bc9e7df2434025b881

This would be patch breaking change, otherwise I'd wait to version bump until I have my next module done, sorry about that!

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.﻿

**Comment by VegaDeftwing** [comment]
Version: 2.0.2
Commit: 69fa9a43705bad3332d3d41f7733879849f81e55

I will probably have to make patch breaking changes later, but I'd rather just get these out there so people can start using them and I can get real feedback

**Comment by VegaDeftwing** [comment]
Source Code: https://github.com/VegaDeftwing/LyraeModules
Version: 2.0.3
Commit: a239b823cea2bbde28ae2a9299f51f01c95b7b93

**Comment by VegaDeftwing** [comment]
Source Code: https://github.com/VegaDeftwing/LyraeModules
Version: 2.0.5
Commit: b6dde88e4d780de0207ece26c5b7de23d61c84e6
