### ISSUE TITLE
AlliewayAudio_Freebies

### ISSUE THREAD

**Issue by AlliewayAudio** [VCVRack/community#691]
Source Code: https://github.com/AlliewayAudio/AlliewayAudio_Freebies
Version: 1.0.1
Commit hash: 876efe0e337afe04a04486f55c8417245452bdcd

**Comment by AlliewayAudio** [comment]
LAST SECOND UPDATE
Version: 1.0.2
Commit hash: 6d3057c905e1459facde515ba8a291702beb6715

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.﻿

**Comment by AlliewayAudio** [comment]
V2 Update is now up on same repository! (https://github.com/AlliewayAudio/AlliewayAudio_Freebies)
Version 2.0.5
Commit hash: c4c206fb3e8475179e8fac14e2648130cae40016

**Comment by AlliewayAudio** [comment]
Another Hotfix Update, just a small frontpanel tweak.
Version 2.0.6
Commit hash: 4147bd25de5946af8f6300d975ed5b79202e06fa

**Comment by AlliewayAudio** [comment]
Hey, just FYI this plugin is not up to date on the official library - there is another update I posted (2.0.6) in my previous post, with the hash 4147bd25de5946af8f6300d975ed5b79202e06fa, which made corrections to the front panel. 

Just thought I would mention, thanks so much ^_^
~Allie

**Comment by AndrewBelt** [comment]
It looks like chilly cheese is a clone of https://www.controlvoltage.net/mannequins-cold-mac.html
Do you have permission from Mannequins to make this port?

**Comment by AlliewayAudio** [comment]
@AndrewBelt Yes, Trent of Mannequins has given his blessing for this port, as well as providing valuable feedback to make the port more accurate to the physical module. Not sure if you'd like proof of some kind - I have emails with him I could share with you privately, and you can certainly reach out to Mannequins to verify this is the case if you'd prefer.

**Comment by AndrewBelt** [comment]
Okay, cool. You might have mentioned this and I've forgotten, but it's good for the record.

**Comment by AlliewayAudio** [comment]
@AndrewBelt Agreed 👍

**Comment by AlliewayAudio** [comment]
Updated build to newest VCV version + for ARM64 Mac support. 

Version 2.0.7
Commit Hash: cff07c47c23e843df4963303696cffdde9823838
