### ISSUE TITLE
Tonecarver

### ISSUE THREAD

**Issue by Tonecarver** [VCVRack/community#693]
Tonecarver VCV Modules 
Please add these modules to the VCV Library
-- These modules are for VCV v1.1.6. Migration to v2 is in progress.

**Source URL:** https://github.com/Tonecarver/tcRackModules

**Commit Hash:** 3589565ed0dce0efd8ed088f9075e1fd3a55bd00

$ git log
commit 3589565ed0dce0efd8ed088f9075e1fd3a55bd00 (HEAD -> main, origin/main, origin/HEAD)
Author: Bill Davies <bdavies00@yahoo.com>
Date:   Sun Oct 3 09:26:48 2021 -0700

    Release v1.0.1

**Comment by Tonecarver** [comment]
Tonecarver Modules v2.0.0
for VCV Rack2

**Source URL**: https://github.com/Tonecarver/tcRackModules     (v2 branch)

**Commit Hash**: 2800f70c0a9f86aba3a781410d1fab6c3ffc6104

commit 2800f70c0a9f86aba3a781410d1fab6c3ffc6104 (HEAD -> v2, origin/v2)
Author: Bill Davies <bdavies00@yahoo.com>
Date:   Sun Oct 3 10:52:02 2021 -0700

**Comment by cschol** [comment]
@Tonecarver Thanks for the submission. Please don't post any updates for `v2`yet, only for `v1` releases. I don't want to confuse both of them in these threads. We will announce when we accept submissions for the `v2` library.

**Comment by cschol** [comment]
Issues in `plugin.json`: https://github.com/Tonecarver/tcRackModules/issues/2

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Tonecarver** [comment]
New version of Tonecarver plugin is available: v1.0.3

Source URL: https://github.com/Tonecarver/tcRackModules   (v1 branch) 

commit **8d87fec0f1b85861412be4f52a4c49303d7d5b22** (HEAD -> v1, origin/v1)
Author: Bill Davies <bdavies00@yahoo.com>
Date:   Sat Nov 13 07:48:55 2021 -0700

    Version bump

**Comment by cschol** [comment]
Build error on macOS platform: https://github.com/Tonecarver/tcRackModules/issues/5

**Comment by Tonecarver** [comment]
Removed 'const' qualifier from lock_guards in ThreadSafeList.hppto resolve Mac compilation error (see https://github.com/Tonecarver/tcRackModules/issues/5)

pushed v1.0.4

commit 6bcf9e00637ba26e7db3de22a9ec51294973c8d8 (HEAD -> v1, origin/v1)
Author: Bill Davies <bdavies00@yahoo.com>
Date:   Sat Nov 13 10:01:09 2021 -0700

**Comment by cschol** [comment]
Still does not compile. Issue updated with suggestion on how to fix.

**Comment by Tonecarver** [comment]
Tonecarver modules, version 2.0.0, are ready for the v2 library

Source URL:  https://github.com/Tonecarver/tcRackModules/tree/v2

commit **0bc4bd1eb78fc47a5c8c49cadeb985b2ac738197** (HEAD -> v2, origin/v2)
Author: Bill Davies <bdavies00@yahoo.com>
Date:   Wed Nov 17 07:31:28 2021 -0700
