### ISSUE TITLE
DelexanderVol1

### ISSUE THREAD

**Issue by xandramax** [VCVRack/community#694]
Hello, I'd like to add my plugin to the VCV library.

Brand: Delexander
Plugin: Delexander Volume 1
Slug: DelexanderVol1
Source: https://github.com/Delexander/Volume1

First release: 287ebec

https://github.com/Delexander/Volume1/commit/287ebecec7e4918f4817e3d3b702ebfe58c2c86d

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by xandramax** [comment]
I found a cosmetic bug. It's been fixed in this release:

https://github.com/Delexander/Volume1/commit/c9ffacdd2ea69f3c32f30cac3e65885653044329

**Comment by xandramax** [comment]
> 
> 
> I found a cosmetic bug. It's been fixed in this release:
> 
> [Delexander/Volume1@c9ffacd](https://github.com/Delexander/Volume1/commit/c9ffacdd2ea69f3c32f30cac3e65885653044329)

This commit includes the above fix and a bumped version number to 1.0.1:

https://github.com/Delexander/Volume1/commit/b8ea573e71531a28f8bf27b296af9b2d46893563

**Comment by xandramax** [comment]
> This commit includes the above fix and a bumped version number:
> 
> [Delexander/Volume1@b8ea573](https://github.com/Delexander/Volume1/commit/b8ea573e71531a28f8bf27b296af9b2d46893563)

This commit fixes a second display issue, and bumps the version number to 1.0.2:

https://github.com/Delexander/Volume1/commit/5c578de54a8073778db299200a0d6745fd3b6c7a

**Comment by xandramax** [comment]
Final update for VCV Library v1: adds a feature and updates license & contact information

https://github.com/Delexander/Volume1/commit/da4c3891dc4d04326bf93321717ee6598c8f48cb
