### ISSUE TITLE
VO

### ISSUE THREAD

**Issue by evgazloy** [VCVRack/community#695]
https://github.com/evgazloy/VO
v 1.0.0
2d479786cf4ccb8e2b39bd264efa2e8054b669d1

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by evgazloy** [comment]
Awesome, thanks.
