### ISSUE TITLE
tbd4vcv

### ISSUE THREAD

**Issue by ctag-fh-kiel** [VCVRack/community#696]
Hi, 

I have been porting the HW version of my open source Eurorack module [CTAG TBD](https://github.com/ctag-fh-kiel/ctag-tbd) to Rack.

The source code URL currently is https://github.com/ctag-fh-kiel/ctag-tbd/tree/vcv/tbd4vcv

It is a subdirectory of the hardware module source, as the SW Rack plugin is compiled using the same source files as the hardware counterpart. I use CMake to generate the build scripts and have tested the plugin for VCV on Mac.

Running the plugin involves running a web-server to control parameters of the plugin (just like with the hardware module).

Can you help me to publish the plugin for Rack? 

Thanks much, Robert

**Comment by cschol** [comment]
Hi Robert, unfortunately, your plugin will require changes to be built by the Rack build system.

There are a few considerations that apply here: 
1. You **must use** the build interface for Rack plugins, i.e. the plugin `Makefile`. This is what the build system expects and executes. The build system does not know anything about `Cmake` and cannot run custom build steps per plugin before executing the build process.
2. The `Makefile` must be available in the root of the repository, i.e. not in a sub-directory. The build process uses the to-level of the repository as its root. The `Makefile` can obviously navigate the directory structure as appropriate.
3. The plugin **must provide** all of its dependencies to the build process. For example, if you require `boost` for your plugin, you must provide it in some form as part of the repository. You cannot require the build process to install any libraries. There are a few ways to accomplish this: you can use a `git submodule` to acquire a library and (if applicable), build library binaries as part of the build process' `make dep` steps, which gets executed before building the plugin. I recommend you look at the [Fundamental](https://github.com/VCVRack/Fundamental) plugin as an example. It builds `libsamplerate` as a dependency for the plugin.

Let me know if you have any questions.

**Comment by ctag-fh-kiel** [comment]
Hi cschol, 

Thanks for getting back!

That means some homework for me. Would it be possible to provide the .zips with the platform specific binaries instead. I have my own CI already up and running and could get them build.

Thx, Robert

**Comment by AndrewBelt** [comment]
@ctag-fh-kiel You can normally send binaries to support@vcvrack.com if you are willing to provide government-issued identification, but due to time constraints we are not accepting new applications for binary submissions for v1 plugins, so you will need to wait until we begin accepting v2 plugins.

**Comment by ctag-fh-kiel** [comment]
Sounds good, I think I will wait for v2 then and submit binaries, makes sense anyways.
Thx, Robert
