### ISSUE TITLE
FreeSurface

### ISSUE THREAD

**Issue by freesurfacemodules** [VCVRack/community#697]
Hello, I have my first module ready for release.
Brand: Free Surface
Slug: FreeSurface
Source: [https://github.com/freesurfacemodules/FreeSurface](https://github.com/freesurfacemodules/FreeSurface)
Hash: 180578a423cf1dacd106c126d38ef88d0ff5eef8

**Comment by cschol** [comment]
Header is removed during build process: https://github.com/freesurfacemodules/FreeSurface/issues/1

**Comment by freesurfacemodules** [comment]
Thank you, I think this resolves the issue:
Hash: ef47dea3081adacc390f491ba5d3b2914c2b932e

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by freesurfacemodules** [comment]
Updated for Rack 2.beta.1
Version: 2.0.4
Branch: rack2
Hash: ba3d647b7833bc22e222b5c81f0318480cf67c06
Source: https://github.com/freesurfacemodules/FreeSurface/tree/rack2

**Comment by freesurfacemodules** [comment]
Fixed broken font rendering when run as VST
Version: 2.0.5
Branch: rack2
Hash: ebe26a567ae5fd23aa63dbd64ef4b0c49599be9f
Source: https://github.com/freesurfacemodules/FreeSurface/tree/rack2

**Comment by AndrewBelt** [comment]
I'm unable to build this for Mac ARM64 because the libsamplerate dependency fails to build. An easy fix is to remove the libsamplerate dependency since the Rack SDK already includes libsamplerate and exposes its API to plugins.

**Comment by cschol** [comment]
Build failure on arm64 platform: https://github.com/freesurfacemodules/FreeSurface/issues/2

**Comment by freesurfacemodules** [comment]
Apologies for taking so long to address this, I have updated the module for the newest SDK version and to build for Mac ARM.
Version: 2.1.1
Branch: main
Hash: 6380be7b20c80c4361d0615d405ead6df743cb67
Source: https://github.com/freesurfacemodules/FreeSurface/tree/main/

**Comment by freesurfacemodules** [comment]
Fixed initialization bug
Version: 2.1.4
Branch: main
Hash: 69231f36033a72878c4c3bd13f22d26272811397
Source: [https://github.com/freesurfacemodules/FreeSurface/tree/main/](https://github.com/freesurfacemodules/FreeSurface/tree/main/)
