### ISSUE TITLE
Kilpatrick-Toolbox

### ISSUE THREAD

**Issue by hires** [VCVRack/community#698]
A set of useful modules.

- source code: https://github.com/kilpatrickaudio/Kilpatrick-Toolbox
- version: 2.0.0
- commit hash: c2a1975

Thanks!

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/kilpatrickaudio/Kilpatrick-Toolbox/issues/1

**Comment by hires** [comment]
Fixed.
version: 2.0.1
commit hash: b39a56d

Thanks!

**Comment by kilpatrickaudio** [comment]
Fixed a small MIDI bug.
version: 2.0.2
commit hash: b8dc1f5

Thanks!

**Comment by kilpatrickaudio** [comment]
Fixed a lot of library code used by the plugin.
version: 2.0.3
hash: 96f186f
