### ISSUE TITLE
Mojo 

### ISSUE THREAD

**Issue by tomdasilva** [VCVRack/community#702]
Hi ! I wish to submit my plugin to the V2 Library ! Thanks a lot ! Have a nice day 
https://github.com/tomdasilva/Mojo

**Comment by tomdasilva** [comment]
Note : this is a migration, the plugin was already available on V1 :)

**Comment by cschol** [comment]
Thanks. I will integrate this new version for `v2`.

Please re-use the existing issue for future updates: https://github.com/VCVRack/library/issues/687
