### ISSUE TITLE
htLocal

### ISSUE THREAD

**Issue by HTlocal** [VCVRack/community#704]
Hi,

I'd like to add some modules.

Git-URL: https://github.com/HTlocal/VCV-Modules-HTLocal
Branch: main
Commit: 65466d4 (latest)

VCV2 Yaaaay :)

**Comment by cschol** [comment]
https://github.com/HTlocal/VCV-Modules-HTLocal/issues/7

**Comment by HTlocal** [comment]
my bad.

merged: 9e4257b

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
