### ISSUE TITLE
Bastl

### ISSUE THREAD

**Issue by hemmer** [VCVRack/community#708]
**repo**: https://github.com/hemmer/bastl-vcv
**hash**: 68d874522c58608650c223c02c10d54a2c8fa205 (branch v2)
**plugin version**: 2.0.0 (first release)
**license**: GPL-3 only

Permission has been sought from from Bastl, and they have approved this release (@AndrewBelt has been cc'd in email thread). First release is only one module.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
