### ISSUE TITLE
3HR

### ISSUE THREAD

**Issue by Geekachuqt** [VCVRack/community#711]
Source: https://github.com/Geekachuqt/3HR
Version: 2.0.0
Commit: 712260226c0d5d82d6629cc8416917664447d2c0

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/Geekachuqt/3HR/issues/1

**Comment by Geekachuqt** [comment]
Fixed `plugin.json` issue.

**Comment by Geekachuqt** [comment]
Added another module, improved Repeat3hr, changed aesthetics.

Source: https://github.com/Geekachuqt/3HR
Version: 1.0.0
Commit: 233a7032170389e3e8fb78b13b3dee921f691da7

**Comment by cschol** [comment]
Please update version to 2.0.0 to match Rack ABI version. Thanks.

**Comment by Geekachuqt** [comment]
Fixed. Sorry, I thought "version" referred to the version of my plugin. My bad!

Commit: b9330cd52a286e9d7b1241d63a817e945594e465

**Comment by cschol** [comment]
It does, but the Major version of the plugin has to follow the ABI version of Rack.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Geekachuqt** [comment]
Source: https://github.com/Geekachuqt/3HR
Version: 2.1.0
Commit: 6432d86c8b794e7621f527b1ae877a3e04d8f5d1

**Comment by Geekachuqt** [comment]
Source: https://github.com/Geekachuqt/3HR
Version: 2.2.0
Commit: 4eb5fc12765b87dc605a8e6c1b2c03dffcecdb62
