### ISSUE TITLE
PathSet

### ISSUE THREAD

**Issue by patheros** [VCVRack/community#712]
Source: [https://github.com/patheros/PathSetModules](https://github.com/patheros/PathSetModules)
Version 2.0.0
Commit: 68c9782207c4afd179a6c832748ea5d4e7be4484

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by patheros** [comment]
Note I updated the Brand inside plugin.json to be "Path Set" (was "Patheros") before. (The slug is unchanged.) This matches what is on the panel. I hope this won't cause any issues,

Source: https://github.com/patheros/PathSetModules
Version 2.1.0
Commit: 2274b6ce06eab05c4712e0856934a6d91fa1a340

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version 2.1.1
Commit: 5b0a48b99496ffa91012d78811a48580ae512eea

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version 2.2.0
Commit: 101e0c0f61b0a734f793ebfb6437b98ecd656ebd

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version 2.3.0
Commit: 5fcc3d3afe23f93337545342827bc3aad793f6dd

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version: 2.3.1
Commit: 6dacfec31c1c4cfdd192681d6c920e6e9a4b8276

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version: 2.4.0
Commit: 3d90ac2ebc257920047fd6ee2ff8695164bcf912

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version: 2.4.1
Commit: ec3c8c24f4ae291e31fe7bcd0514e7a203d94d26

**Comment by patheros** [comment]
Source: https://github.com/patheros/PathSetModules
Version: 2.5.0
Commit: bc99d82ee1a305679690f5d8002c90b5e340276f

**Comment by cschol** [comment]
Please check SHA. The provided one points to a version 2.4.1. Also, please update the Author URL to "https://www.patheros.com". Without the "www" there is a validation error. Thanks.

**Comment by patheros** [comment]
Ops. Thanks.

URL is updated.

Source: https://github.com/patheros/PathSetModules
Version: 2.5.0
new SHA: 2f55b4b115e76623ef54e24c30daad4d576a4446
