### ISSUE TITLE
MicMusic

### ISSUE THREAD

**Issue by very-cool-name** [VCVRack/community#714]
https://github.com/very-cool-name/MicMusic-VCV

**Comment by very-cool-name** [comment]
1.0.0
b7dbc69e047346c1d8d286c77313f2f894bd6480

**Comment by cschol** [comment]
Is your plugin intended to be released for Rack `v2.0x`?

**Comment by very-cool-name** [comment]
Yes

**Comment by cschol** [comment]
For deployment to 2.0, the plugin version must match the AB version, i.e. the plugin version should start with 2.

**Comment by very-cool-name** [comment]
Okay, bumped it!
2.0.0
fcd92f3cd05354f4375ff3954fead967d6db795d

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
