### ISSUE TITLE
Skylander

### ISSUE THREAD

**Issue by theskylander** [VCVRack/community#716]
https://github.com/theskylander/Skylander-plugins

**Comment by cschol** [comment]
Integration issues: https://github.com/theskylander/Skylander-plugins/issues/1

**Comment by cschol** [comment]
Fonts stored across frames: https://github.com/theskylander/Skylander-plugins/issues/2

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
