### ISSUE TITLE
DivergentWaves

### ISSUE THREAD

**Issue by tpcarlson** [VCVRack/community#717]
Hello, please could you add this repository/plugin to VCV Rack's library?

Source: https://github.com/tpcarlson/DivergentWavesVCVRack/
Branch: master
Hash: 350a579f54fcc046a55bf6e14d64db5e352d2b86
Tag: 1.0.1

**Comment by tpcarlson** [comment]
New version, with the proper version# in the manifest (Fixed https://github.com/tpcarlson/DivergentWavesVCVRack/issues/1)

Source: https://github.com/tpcarlson/DivergentWavesVCVRack/
Branch: master
Hash: 7ba7aa94ca81b1533a45d1a57310f67754c8dc13
Tag: 2.0.0

**Comment by cschol** [comment]
One question: are you the owner of the hardware module you are referencing? We generally ask for hardware modules owners to provide permission for VCV Rack versions of their modules. Thanks!

**Comment by tpcarlson** [comment]
Yup, I'm the owner of the hardware module 👍 

The source for the hardware is here: https://github.com/tpcarlson/synth-diy/tree/main/logic (Although it may move to a new repo in the future)
Thonk's listing: https://www.thonk.co.uk/shop/divergent-waves-logic/
Very minimal website: https://www.divergentwaves.co.uk/module/logic/

**Comment by cschol** [comment]
Excellent. Thank you!

**Comment by cschol** [comment]
Invalid license ID: https://github.com/tpcarlson/DivergentWavesVCVRack/issues/2

**Comment by tpcarlson** [comment]
Fixed up the license in the manifest

Source: https://github.com/tpcarlson/DivergentWavesVCVRack/
Branch: master
Hash: 3fbe771440ef4ab822cc6c78bdc883ca7f783d98
Tag: 2.0.1

**Comment by tpcarlson** [comment]
(I do need to swap out the LICENSE file still though)

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
