### ISSUE TITLE
dbRackFormulaOne

### ISSUE THREAD

**Issue by docb** [VCVRack/community#718]
url: https://github.com/docb/dbRackFormulaOne
version: 2.0.0
tag v2.0.0

NB: With the rack-toolchain it costs over 30 minutes to build the windows binary on my linux machine. 
this plugin includes the exptrk library header which has over 40000 LOC and must compiled with the  -Wa,-mbig-obj  option.

**Comment by cschol** [comment]
Confirmed the long build time. On my machine it takes about 28 minutes to build the full plugin.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by docb** [comment]
url: https://github.com/docb/dbRackFormulaOne
version: 2.0.2
tag v2.0.2
