### ISSUE TITLE
changing Library folder to a custom address!

### ISSUE THREAD

**Issue by parsivan** [VCVRack/community#720]
I really wanted to change the location for the library on v1 because a lot of apps save their stuff in documents and it would be nicer if I had them in another place. Also, My device is being controlled by my school IT department and most things are not the way they should be. so the app downloads the libraries but then can't open them when restarted. I have tried changing settings in properties of vcv folder in documents I have tried running the app as administrator. But I think this would help!?
<img width="676" alt="Skärmbild 2022-04-07 151202" src="https://user-images.githubusercontent.com/21005543/162207926-b5fda5a0-378f-46fe-9fac-6a16e72ccc3f.png">

**Comment by VegaDeftwing** [comment]
See https://vcvrack.com/manual/Installing - you can use the `-u` flag when starting Rack to point to a different library location.

**Comment by AndrewBelt** [comment]
@VegaDeftwing is correct and the only thing I have to add is that you can use an environment variable as well, documented in the manual.

However, this is the issue tracker for the VCV Library collection, not Rack itself. Contact [VCV Support](https://vcvrack.com/support) for support with Rack.
