### ISSUE TITLE
PinkTrombone

### ISSUE THREAD

**Issue by VegaDeftwing** [VCVRack/community#722]
Source: https://github.com/VegaDeftwing/PinkTromboneVCV
Version: 2.0.0
Commit: 529be538f61da533bf55b6462ca058173069efcf

**Comment by cschol** [comment]
Can I ask you to please clarify the license for the Pink Trombone code. Where did the code originate from?

**Comment by VegaDeftwing** [comment]
My repo is GPL. I yoinked the Pink Trombone code from https://github.com/cutelabnyc/pink-trombone-cpp which is MIT and is in turn is from https://dood.al/pinktrombone/ which is MIT'd if you check in the HTML. GPL is more restrictive than MIT, but that should be okay in this case. I'll add a blurb to the licence, sorry, I must've forgot to!

**Comment by cschol** [comment]
Ah, got it. I was looking at the wrong repo. I didn't see the `pink-trombone-cpp` one.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by VegaDeftwing** [comment]
Source: https://github.com/VegaDeftwing/PinkTromboneVCV
Version: 2.0.1
Commit: d0a6e206c92b93ffeaa933fc98c0dfd9e78771da

Very minor update, just fixes some misspellings and tool-tip issues

**Comment by VegaDeftwing** [comment]
Source: https://github.com/VegaDeftwing/PinkTromboneVCV
Version: 2.0.2
Commit: 0292a60f427e00bd07f98fab160fbc51c62f8575
