### ISSUE TITLE
RebelTech

### ISSUE THREAD

**Issue by hemmer** [VCVRack/community#723]
**repo**: https://github.com/hemmer/rebel-tech-vcv
**version**: 2.0.0
**license**: GPL-v2-or-later
**commit hash**: b648ebb5febb56bc7ae4a908cfc9c7d1686ba007

for context, thread where Martin (copyright holder and collaborator) confirms he is happy for the port: https://github.com/hemmer/rebel-tech-vcv/issues/2

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by hemmer** [comment]
repo: https://github.com/hemmer/rebel-tech-vcv
version: 2.0.1
license: GPL-v2-or-later
commit hash: 2c2691f261916e2e749750fb0838fc13d4d0784b

Minor Update 
## v2.0.1
  * Added Dark Mode to all modules
  * minor tweak to reduce CPU usage of Logoi
