### ISSUE TITLE
LoudNumbers

### ISSUE THREAD

**Issue by duncangeere** [VCVRack/community#724]
https://github.com/loudnumbers/loudnumbers_vcv

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by duncangeere** [comment]
Bug fixes and some small UI improvements
Version: 2.0.1
Commit: 037cd86cb40e96654fe1305c10b60579facbfc06
URL: https://github.com/loudnumbers/loudnumbers_vcv/commit/037cd86cb40e96654fe1305c10b60579facbfc06

**Comment by duncangeere** [comment]
Fixing a windows build failure
Commit: 07fe8f29688b3077b8f4c21726ee610885ccd0bc
URL: https://github.com/loudnumbers/loudnumbers_vcv/commit/07fe8f29688b3077b8f4c21726ee610885ccd0bc

**Comment by duncangeere** [comment]
Discovered a small bug in the latest release, fixed by:
Commit: 99ea3c3cd059cf2d980292fe4e9d977e85d30d0d
URL: https://github.com/loudnumbers/loudnumbers_vcv/commit/99ea3c3cd059cf2d980292fe4e9d977e85d30d0d

**Comment by duncangeere** [comment]
New features and bug fixes:
Version 2.0.3
Commit: e71389c74b1d76ba9273825a6d9092028c0d8cde
URL: https://github.com/loudnumbers/loudnumbers_vcv/commit/e71389c74b1d76ba9273825a6d9092028c0d8cde

**Comment by duncangeere** [comment]
Version 2.0.4
Discovered a small bug in the latest release, fixed by:
Commit: 351d3714d82d1b12d40ca443115b7598450cb853
URL: https://github.com/loudnumbers/loudnumbers_vcv/commit/351d3714d82d1b12d40ca443115b7598450cb853

**Comment by duncangeere** [comment]
Version 2.1.0
Feature release: click a datapoint on the display to cue it, selectable CSV delimiters with auto-detect (.tsv/.txt supported), data embedded in patches so they survive a missing CSV, gapless END→RESET looping, and CSV loading crash fixes.
Commit: 291430e122cb1f1818951bce022be12ae137889a
URL: loudnumbers/loudnumbers_vcv@291430e
