### ISSUE TITLE
fruitsofkarma

### ISSUE THREAD

**Issue by alexey-komarov** [VCVRack/community#725]
https://github.com/alexey-komarov/fruitsofkarma-vcvrack

There are two branches, main is for vcvrack2 and v1 for vcvrack1.

Thanks!

**Comment by alexey-komarov** [comment]
Minor changes in reset button of ColoredGlass to reduce CPU usage:

2.0.3: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/50def34a4800528ec703ee86e36f62f02f65fe46
1.0.3: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/05f4f19192c575d0f6b84f07bf8f5adf9ce72f0d

**Comment by alexey-komarov** [comment]
Fixed UB
2.0.4: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/be84db530f306944a07d216b2087a9f28938b4bd
1.0.4: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/40c205d230cbd05a20d957f549898fa2103fe7f2

**Comment by alexey-komarov** [comment]
New plugin has been added + one minor fix in a svg

2.0.5: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/64f5af2e7e46045b90475090bd7735531d183c34
1.0.5: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/e3b628820760e137d60e068621e9c57fdc1ef155

**Comment by alexey-komarov** [comment]
Couple of minor fixes:
v1: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/da4bb476ca0862a12450da2db401ed749e16a109
v2: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/b57b9e21d731f6ced97de6459066fb7180549661

Thanks.

**Comment by cschol** [comment]
Font references cached across frames: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/issues/10

**Comment by alexey-komarov** [comment]
@cschol Please find the latest fixed version here: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/646696bd511ffee22d66292cd342023eb3bac5d8

**Comment by alexey-komarov** [comment]
I found a minor bug, could you please rebuild the plugin, the latest commit for v2 is here: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/083f6a12d09e6b3764c83f2b62fcfa3379460475

cschol also mentioned you don't build v1 anymore, but does it mean you also don't build plugins for v1, too? I.E. does it make sense to provide a link to the fixed version of my plugin for VCVRack v1?

**Comment by alexey-komarov** [comment]
Hi VCVRack maintainers, I've got a couple of free evenings and implemented one more module, it's a really long sequencer 64x256, it can be configured to be of any lesser size using zoom controls. Also it has cellular automaton algorithm to generate initial patterns. The revision is here: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/8dd02f8b87000cd12861f609c1581e2f87231ba1

Also, I had to fix loading font in ScaleMerger, without this fix it was not shown on my Linux.

**Comment by cschol** [comment]
Failure to load SVG: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/issues/12

**Comment by alexey-komarov** [comment]
@cschol looks I simply forgot to add svg file. fixed in revision: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/8cd4e3a33d42d76ffbff23622ad8c2d3940036cc

**Comment by alexey-komarov** [comment]
Could you please rebuild a new version  2.0.10: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/c271274606f3fec79612aa825061e8c323af76e4 (One minor bug has been fixed in the Math module).
Thanks!
