### ISSUE TITLE
Coffee

### ISSUE THREAD

**Issue by CoffeeVCV** [VCVRack/community#726]
Source : https://github.com/CoffeeVCV/CoffeeVCV
Version : v2.0.0
Commit : 3289926e97070863eca9deebdf92ff477a4bb145

**Comment by CoffeeVCV** [comment]
This commit please : 7c263e67e7ff1460a6e98877d338221a893c18f9

**Comment by cschol** [comment]
Invalid URL in manifest: https://github.com/CoffeeVCV/CoffeeVCV/issues/2

**Comment by CoffeeVCV** [comment]
URL resolved in : fa1191e2c9b43e2860897e4114b66617b59cb1fc

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by CoffeeVCV** [comment]
New Module
Version : 2.1.0
Commit : e731e1fd74d0ae74ac4b777fa3810d94be43adc3

**Comment by cschol** [comment]
Plugin manifest issues: https://github.com/CoffeeVCV/CoffeeVCV/issues/4

**Comment by CoffeeVCV** [comment]
Manifest typos fixed.
Commit : d2057606470755f99a05f32661ff889efa9d8945
https://github.com/CoffeeVCV/CoffeeVCV/commit/d2057606470755f99a05f32661ff889efa9d8945

**Comment by CoffeeVCV** [comment]
New modules, bug fixes, cosmetic changes
Versions : v2.2.0
Commit : bcb25a5526d17d65445e16db8d70877ba11edaf4
URL : https://github.com/CoffeeVCV/CoffeeVCV/commit/bcb25a5526d17d65445e16db8d70877ba11edaf4

**Comment by cschol** [comment]
Fails to load some SVG components: https://github.com/CoffeeVCV/CoffeeVCV/issues/13

**Comment by CoffeeVCV** [comment]
Issue with svg path name case resolved with this commit : 1e46e0052cdf5c989d976458109a1c188a981511
https://github.com/CoffeeVCV/CoffeeVCV/commit/1e46e0052cdf5c989d976458109a1c188a981511

**Comment by CoffeeVCV** [comment]
Apologies, @cschol there's a breaking typo in one module.
Fixed in this commit
https://github.com/CoffeeVCV/CoffeeVCV/commit/2c44c81d82310101146ad97f3fbbb60b56c5e779
Commit : 2c44c81d82310101146ad97f3fbbb60b56c5e779

**Comment by CoffeeVCV** [comment]
Versions : 2.3.0
Commit : cd9ff4abf7592cca96ec176ecb9b02eeae31c46a
URL : https://github.com/CoffeeVCV/CoffeeVCV/commit/cd9ff4abf7592cca96ec176ecb9b02eeae31c46a

**Comment by cschol** [comment]
Build failure on Windows platform: https://github.com/CoffeeVCV/CoffeeVCV/issues/15

**Comment by CoffeeVCV** [comment]
Switched u_int64_t for uint64_t
Version : 2.3.0
Commit : 29e31453737db472b76d12bf70a4dd9e72ace582
URL : https://github.com/CoffeeVCV/CoffeeVCV/commit/29e31453737db472b76d12bf70a4dd9e72ace582

**Comment by CoffeeVCV** [comment]
Version : 2.4.0
Commit : f5b3a1846cf9f4069224c1778e944a337de06b23
URL : https://github.com/CoffeeVCV/CoffeeVCV/commit/f5b3a1846cf9f4069224c1778e944a337de06b23

**Comment by CoffeeVCV** [comment]
Version : 2.4.1
Commit : dfb2174d7f8cd4b035abd1aac2555f941a517854
URL : https://github.com/CoffeeVCV/CoffeeVCV/commit/dfb2174d7f8cd4b035abd1aac2555f941a517854
