### ISSUE TITLE
h4n4-modules

### ISSUE THREAD

**Issue by hannakoppelaar** [VCVRack/community#727]
https://github.com/hannakoppelaar/h4n4-modules

**Comment by hannakoppelaar** [comment]
version: 2.1.0
commit: 3497a26f7023378be59b75e9d7ebc154e7b1509c

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by hannakoppelaar** [comment]
Version: 2.1.1
Commit: 6588b673fdaf1514d8d6bfbc1a20d05d2fa37e13

**Comment by hannakoppelaar** [comment]
Version: 2.2.0
Commit: 02fd2818745b04264353fc64e2a0eff376359f4e

**Comment by cschol** [comment]
Integration issues - static analysis: https://github.com/hannakoppelaar/h4n4-modules/issues/6

**Comment by hannakoppelaar** [comment]
New release containing the fix for https://github.com/hannakoppelaar/h4n4-modules/issues/6:

Version: 2.2.1
Commit: d68c2f9c95fe2781920c39557888616dcad6d007

**Comment by hannakoppelaar** [comment]
Version: 2.3.0
Commit: 17ed896a425c56f8e7a95f20d7a747a5e5723ced
