### ISSUE TITLE
AetrionModular

### ISSUE THREAD

**Issue by patheros** [VCVRack/community#736]
Source: https://github.com/aetrion-music/aetrion-modular
Version 2.0.0
Commit: f31aa021ed71663b0b130af30761851f0e30e4c1

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by patheros** [comment]
Source: https://github.com/aetrion-music/aetrion-modular
Version 2.1.0
Commit: b57a8fba6d091bdc6ffc78dc54e92ebeaed07a53
