### ISSUE TITLE
BlushAudio

### ISSUE THREAD

**Issue by BlushAudioLab** [VCVRack/community#737]
https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.0.0

1dd10a9f95136631d8b5b23ea3ab8a0cf41271d4

**Comment by cschol** [comment]
Invalid URL in `plugin.json`: https://github.com/BlushAudioLab/BlushAudioVCVFreeModules/issues/1

**Comment by BlushAudioLab** [comment]
Updated and fixed URL in JSON:

https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.1.0

SHA: 39e6c646d8a18d6f3319c04179958e7080ffd20f

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by BlushAudioLab** [comment]
Updated to version 2.1.1:

Repo: https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.1.1

SHA: 598a350296f780f6beda03f4d8ea13aa59448ee2

**Comment by BlushAudioLab** [comment]
Forgot to update the JSON:

Repo: https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.1.1

SHA: 44ffebb04367619a41d43073cd6348f01d682a8a

**Comment by BlushAudioLab** [comment]
Updated to version 2.1.2:

Repo: https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.1.2

SHA: 93ad6c5a2c385e88e4cc8e40a90a1ca623287470

**Comment by BlushAudioLab** [comment]
Updated to Version 2.2.0:

Repo: https://github.com/BlushAudioLab/BlushAudioVCVFreeModules

V2.2.0

SHA: e5f0e3d6cc6b13ffc0bd9dc1e712b2a338eda3f8
