### ISSUE TITLE
Sparkette

### ISSUE THREAD

**Issue by flarn2006** [VCVRack/community#738]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.0.0
Commit: 3d525bb1047ac20f92f2e9d332c2a97ab7c2c746

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.1.0
Commit: 1a021692853bfb2bb0fa2a578ade57220f211fc8

**Comment by AndrewBelt** [comment]
QAEngineer generates non-finite values which are reset to 0V by Rack, so I'd recommend removing this module from the plugin.

**Comment by flarn2006** [comment]
> QAEngineer generates non-finite values which are reset to 0V by Rack, so I'd recommend removing this module from the plugin.

That's a known issue. The non-finite values are intentional (it's there specifically for the purpose of experimentation, to see how other modules react) but that part isn't really functional yet because of the behavior you describe. (See issue 1 in my repository.) One way I've thought about working around the 0V reset would be by getting a reference to whatever input the wire is connected to, and directly calling `setVoltage` on that, but I'm not sure if it will work, and I'm also unsure how to get a reference to the connected input. What would be the best way to work around that issue?

**Comment by flarn2006** [comment]
I ended up removing QAEngineer. It's still in the `develop` branch in case I decide to add to it later, but now I'm finding there's other plugins for multiplying values beyond ±10V. Since its other functionality isn't even working yet, I see no reason to include it in the plugin.

That means there's only two modules now, or three if you include the blank. But hey, it's a start. I do have ideas for others, some of which I've already started developing.

----

Source: https://github.com/flarn2006/SparketteVCV
Version: 2.1.1
Commit: 4f8fb23cfaeb67e3b41b012ec2c7eaf41b2f8e09

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.1.2
Commit: 3f0e5b2ea952552f9a2e6c1ae92b1aa11f5b9358

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.2.0
Commit: 71ee81a994b469904d0943433a2ddbc85ae35c0a

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.3.0
Commit: 42a9401396f5f341550a73db71d56b4540db1f6d

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.3.1
Commit: fd59184e650fd5dba7ec52e94a75732a8d85e6c4

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.4.0
Commit: 92c427d58e50f26ebe3c9c10c41b409eaf80648b

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.5.0
Commit: 3f12c70741e7ae1108d1746a64386d0ad77b282d

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.6.0
Commit: dbd8aa6393e1ae5e7faa043cc7be29c4c96cbd88

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.7.0
Commit: e7f01a1a7bdc84bebd011f18f6e95d92f3293eae

**Comment by cschol** [comment]
Build failure on macOS platform: https://github.com/flarn2006/SparketteVCV/issues/3

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.7.1
Commit: c925a149881120204da2cf6d625f1367377f8339

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.8.0
Commit: 35bf7a47bb4c05215b003931081ca12ddc2a55f4

**Comment by flarn2006** [comment]
Source: https://github.com/flarn2006/SparketteVCV
Version: 2.8.1
Commit: b90cd69589ac77f41f626ea4ecb3a49d57780239
