### ISSUE TITLE
SeasideModular

### ISSUE THREAD

**Issue by abluenautilus** [VCVRack/community#739]
Source: https://github.com/abluenautilus/SeasideModularVCV
Version: 2.0.1
Commit: 20d062bdcd9fe232da4d98683eebab6cdb547d65

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by abluenautilus** [comment]
New version: 2.1.0
commit: 584e9c4142bca0a1299a569c79d9896762260144

**Comment by abluenautilus** [comment]
New version with feature upgrades
Version: 2.2.0
Commit: 4982098894aaadb0f9e08122d2008bead8856658

**Comment by abluenautilus** [comment]
Fixes a bug that caused VCVRack to crash!
Version: 2.2.1
Commit: 00ba7dc711474bca47bef17c2db196cff1705681

**Comment by abluenautilus** [comment]
Version 2.4

Notes: adds two new modules: pX (Proteus expander) and Jawari

Source: https://github.com/abluenautilus/SeasideModularVCV/tree/7973f4be989d83675f8a73e3d0fba0f9fe37343c

Commit: 7973f4be989d83675f8a73e3d0fba0f9fe37343c

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/abluenautilus/SeasideModularVCV/issues/10

**Comment by abluenautilus** [comment]
Fixed tags

commit: c90c9506e98f922b28c1776a70b433d26768e014

**Comment by cschol** [comment]
One more thing: please remove the `dist` directory (and its binary content) from the source repository. It is unnecessarily increasing the repository size. You should add it to a `.gitignore` file to prevent accidental commits. 

Note, that it is not enough to just delete via commit. You should use [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove the binaries from the history as well. Thank you.

**Comment by abluenautilus** [comment]
Done! Thank you. 

https://github.com/abluenautilus/SeasideModularVCV/tree/bdcb14c93b39ae0ea9587280c23b50d0f4c6211f

**Comment by abluenautilus** [comment]
Bug fixes and feature updates
Version: 2.4.2
Commit: aaabaefb51124542ff3089914d8301cc81f3f314
https://github.com/abluenautilus/SeasideModularVCV/tree/aaabaefb51124542ff3089914d8301cc81f3f314

Thank you!

**Comment by cschol** [comment]
Array access out of bounds: https://github.com/abluenautilus/SeasideModularVCV/issues/17

**Comment by abluenautilus** [comment]
Fixed.  

New commit: 4dc1722aad609f704ad9e86d44d29e5858db4151

**Comment by abluenautilus** [comment]
New version: 2.5.1
Adds new module: Tala, a sample-based tabla machine

Commit: 56f6bd5cdb29145110a1dd0e79087c673c9cb51c
https://github.com/abluenautilus/SeasideModularVCV/tree/56f6bd5cdb29145110a1dd0e79087c673c9cb51c

Thanks!

**Comment by abluenautilus** [comment]
New version 2.5.2
Adds Raga module and Seaside Blank, other minor fixes. 

Commit bf3ea150ffa2f3a753ef60bc27a4d7db8707561b
https://github.com/abluenautilus/SeasideModularVCV/tree/bf3ea150ffa2f3a753ef60bc27a4d7db8707561b

Thanks!
