### ISSUE TITLE
amenland

### ISSUE THREAD

**Issue by Genoil** [VCVRack/community#740]
src: https://github.com/Genoil/amenland
commit: bdcf45979f70d2aef4be61dfeb1543cc6dc6c01a
version: 1.0.0

**Comment by AndrewBelt** [comment]
This plugin contains two audio recordings in https://github.com/Genoil/amenland/tree/master/res/samples which we are unable to distribute without permission from the copyright holder(s).
Comment on this thread if the samples are removed, or if if you obtain permission to distribute.

**Comment by Genoil** [comment]
I have permission

**Comment by AndrewBelt** [comment]
Can I see it?

**Comment by Genoil** [comment]
Apologies, I accidentally posted what was intended to be a more detailed reply. Anyway, it turns out that for one of the samples (zwijn.wav) of which I thought I had/could get permission, I actually can not, so I’ll replace that with something I will  have permission for.

As for the other one (amen.wav), things are a little bit more complicated. Being the most sampled and redistributed drum loop in music history, I kind of assumed it belonged in the public domain. However, things are are little bit different. See https://en.m.wikipedia.org/wiki/Amen_break section Royalties for more information on the copyright matter of the Amen break. So not only is it almost impossible for me to locate the current copyright holders, but thousands before me also haven’t (been able) and have never faced any issues regarding copyright claims.

I simply cannot remove the amen break from the plug-in as it is what the module is about and it would render the entire Amenator module completely useless. If that means it cannot be included in VCV Rack library, so be it.

On the other hand, if we take a look at what the Amenator module is about, namely chopping it up and re-arranging it in numerous ways instead of redistributing the original, combined with a 0% chance of facing copyright claims, I think it would be fair to assume clearance and leave the sample in. 

If needed, I could remove the WAV file and embed the sample (optionally encrypted)  through a header file. This way there would be no way of redistributing the file through the library except by resampling (!) it.

Last option for me would to find a drummer to record it for me. I’d rather not go down that route as it would detract from the purpose of the module, namely to honour a great piece of modern music history.

Please let me know what you think!

Best,
Jan Willem

**Comment by Genoil** [comment]
Oh and by the way, I am actually not 100% certain that the amen sample  I am using is a sample of the original. There have been countless re-recordings by session drummers to circumvent this complex issue. I got mine from SampleFocus where it is listed as Royalty Free:

https://samplefocus.com/samples/amen-break-original-g

It says “original” but that doesn’t proof anything.

**Comment by ginger-OS** [comment]
@AndrewBelt hi could you advise me how to proceed? Thanks

**Comment by Genoil** [comment]
Hi @AndrewBelt could you advise me on how to proceed?
