### ISSUE TITLE
EnigmaCurry

### ISSUE THREAD

**Issue by EnigmaCurry** [VCVRack/community#741]
Plugin submission: EnigmaCurry
source code: https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack
license: GPLv3+
branch: v2
current SHA (v2.0.2): [ccac267f16881ccdaeaa672ff70291086eb2fa42](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/commit/ccac267f16881ccdaeaa672ff70291086eb2fa42)

Modules:
 * [Transport](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack#Transport)
 * [Latch](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack#Latch)

**Comment by EnigmaCurry** [comment]
Updated SHA (v2.0.3): [e7b6515ac35eeef12633b84f9e3317ec97d7fe44](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/commit/e7b6515ac35eeef12633b84f9e3317ec97d7fe44)

Changelog: 

2.0.3

 * Fix license name in plugin manifest: "GPL-3.0-or-later"
 * Load fonts in the drawText call, rather than in the constructor.

**Comment by AndrewBelt** [comment]
Looks good, but I'd suggest changing the slug to simply `EnigmaCurry`. Including "VCV" might confuse people that this is a VCV product, and "vcv-pack" is a redundant suffix.

**Comment by EnigmaCurry** [comment]
Thanks, updated!

Updated SHA (v2.0.4): [3da1837dab91146f4a99e411be8fd8f9aecf0fad](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/commit/3da1837dab91146f4a99e411be8fd8f9aecf0fad)

Changelog:

2.0.4

 * Transport:
   * Added external reset (stop) input.
   * Added internal clock divider.
   * Added play button selectable to be a toggle or idempotent.
   * Tested working with MIDI-CV CLK and CLK/N for use in a DAW.
   * Added configurable RESET for start and/or stop in menu.

**Comment by EnigmaCurry** [comment]
Updated SHA (v2.0.5): [6288edfd0d526aaf5a7a162cdbbb1f47e1ea2953](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/commit/6288edfd0d526aaf5a7a162cdbbb1f47e1ea2953)

Changelog: 

2.0.5

 * Transport:
   * Added LOOP trigger output, pulsed at the start of every record length loop.
   * playCount display is modulo 1000 so that it loops back to 0 after 999.

**Comment by EnigmaCurry** [comment]
Updated SHA (v2.0.6): [cd4c939da503a381ee84f59711a16ca8334a3b0b](https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/commit/cd4c939da503a381ee84f59711a16ca8334a3b0b)

Changelog:

2.0.6

 * Updated copyright headers across all cpp and hpp files to reflect dual license.
 * Transport:
   * Added labels to all inputs and outputs.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
