### ISSUE TITLE
InfrasonicAudio

### ISSUE THREAD

**Issue by ndonald2** [VCVRack/community#743]
https://github.com/infrasonicaudio/Infrasonic-VCV
Version: 2.0.0
SHA: 367dc3f973ba34e3d594ecda479d884b9655bda0

**Comment by AndrewBelt** [comment]
Ah, did you decide to release this as open-source, or is this a different module that you showed me in your email?

**Comment by ndonald2** [comment]
@AndrewBelt I decided to go open source. Apologies, I meant to reply to the email but it slipped my mind.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by ndonald2** [comment]
https://github.com/infrasonicaudio/Infrasonic-VCV
Version: 2.0.1
SHA: 1b0b2a81ffa2bf27b91c3e6763c599b5827c7c17

[Release Notes](https://github.com/infrasonicaudio/Infrasonic-VCV/releases/tag/2.0.1)
