### ISSUE TITLE
AaronKarp-EarthTones

### ISSUE THREAD

**Issue by aaronkarp123** [VCVRack/community#746]
Hello,

My first plug-in, PolarCV, is ready to be submitted to the library.

Code: https://github.com/aaronkarp123/EarthTones/tree/main/PolarCV
Version: 2.0.0
Git hash: 69811962cc133d61cba949b555ee76c9450dfa07

This is my first time producing a module, so please let me know if you need more info or if there's anything further I need to do at this time, either code-wise, structurally, or in my documentation. Thanks so much for your help!

**Comment by cosinekitty** [comment]
Hi. I'm not part of the VCV Rack team, just a lurker here. Your module looks  interesting, but I don't see any documentation that explains how to use it. If you have a web page (or just a README.md on your GitHub repo) that explains what it does, gives screenshots/videos, and so on, it would be helpful to link to it from your plugin.json file. People aren't likely to try out your module if they can't understand what it does or how to use it.

**Comment by aaronkarp123** [comment]
Hi cosinekitty, thank you for the suggestion! I saw a couple of issues for modules that didn't have much documentation, but I see now that those were both physical module copies so probably didn't need as much explanation. For now I have added a [readme in the repo](https://github.com/aaronkarp123/EarthTones/tree/main/PolarCV) that should explain things. I'll work on getting a video up showing it in action, but wanted to wait until I started this process in case I needed to make any unexpected significant changes.

**Comment by cosinekitty** [comment]
That's really cool! I like the visual display a LOT. You should put the link to your repo in plugin.json for "manualUrl" and "sourceUrl", so people can find this from vcvrack.com and inside the VCV Rack module browser, once your module gets published.

**Comment by aaronkarp123** [comment]
Thanks for the suggestion! I've made that update.

For the VCV Rack team, my new Git hash with the updated json is: 09d265d4e68af05d57e02e1c37c43a642599d01e

**Comment by cosinekitty** [comment]
Oh, one other thing is, VCV Rack requires you to [clarify licensing of your plugin](https://vcvrack.com/manual/PluginLicensing). As mentioned [here](https://vcvrack.com/manual/PluginDevelopmentTutorial#Releasing), you should put a LICENSE file (.md or .txt) in your repo with the full text of the license you are using. You also need to put the exactly-spelled license tag in your plugin.json. Right now have you have "proprietary" in there, which I doubt is what you intended, since the source is visible to the public.  I hope this feedback is helpful.  Good luck with your submission!

**Comment by aaronkarp123** [comment]
Ah you're right, I totally missed that. Updated it to reflect GPL-3.0-or-later in the json and added in the LICENSE file. Thanks for all of your pointers/suggestions!

New git hash for the team: 4628a85fadcd84eadad7614983ca8082ec000492

**Comment by cschol** [comment]
Thank you for submitting your module.

There are a few issues with your repository layout:
1. The plugin code and the `plugin.json` should be in the **top-level** of the repository. Basically the content of the `PolarCV` folder should be the repository, nothing else. The build process is cloning your repository and we don't want to clone any of the other unrelated files. See an example of a proper layout here: https://github.com/cosinekitty/sapphire
2. You should not include binaries in the repository. For example `plugin.dylib` or the `dist` folder. Use a proper `.gitignore` file to prevent accidentally committing binary files. It is **not enough** to just remove the binaries from the repository. Once they are committed you must remove them from the history as well. Use [BFG Repocleaner](https://rtyley.github.io/bfg-repo-cleaner/) to accomplish this, or, in your case, you should create a new repository with just your plugin code and no binaries.

**Comment by aaronkarp123** [comment]
Hi cschol, thank you for the information! I believe I have fixed both issues, though please let me know if I'm missing something. Also, wanted to note that I've changed the slug, since I realized the outer slug in the json file should be the repo/organization (AaronKarp-EarthTones) instead of the module's slug (Polar).

The new repository is: https://github.com/aaronkarp123/EarthTones
Version: 2.0.0
Git hash: 22f82e941f1ef6918ab569b2ef52eb1796b704a3

**Comment by aaronkarp123** [comment]
Hi @cschol - is there anything else I should do to fix up my repo? I don't mean to rush you through this process, just want to make sure things are all set on my end. Thanks!

**Comment by cschol** [comment]
Slug mismatch: https://github.com/aaronkarp123/EarthTones/issues/1

**Comment by aaronkarp123** [comment]
Thanks, fixed!

New hash: 6896dddc106155d8c7c19655f0348b1be8b7ab41

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by aaronkarp123** [comment]
Hello- I have a day one bug fix update. Thanks!

Code: https://github.com/aaronkarp123/EarthTones
Version: 2.0.1
Git hash: 6b34e199d95417527671755e02af5dbe3b226333
