### ISSUE TITLE
Digital-Apothecary

### ISSUE THREAD

**Issue by ghost** [VCVRack/community#748]
https://github.com/evanedwardsgit/Digital-Apothecary

**Comment by cschol** [comment]
Integration issues: https://github.com/evanedwardsgit/Digital-Apothecary/issues/1

**Comment by ghost** [comment]
> Integration issues: [evanedwardsgit/Digital-Apothecary#1](https://github.com/evanedwardsgit/Digital-Apothecary/issues/1)

The integration issues should be resolved. Created a new repo and committed the appropriate files.

https://github.com/evanedwardsgit/Digital-Apothecary

**Comment by cschol** [comment]
Thank you.

One more issue with SVG failing to load at runtime: https://github.com/evanedwardsgit/Digital-Apothecary/issues/1

**Comment by ghost** [comment]
Just pushed 2.0.2, after resolving the SVG issue

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by ghost** [comment]
Updated to version 2.0.4

**Comment by ghost** [comment]
Updated to 2.0.5
Primarily fixed optimization issues
