### ISSUE TITLE
TyrannosaurusRu

### ISSUE THREAD

**Issue by fairplay** [VCVRack/community#750]
Hi

sourceUrl: https://github.com/fairplay/vcv-rack-plugins
HEAD: 57c166ad5e808f11ac34145348d34fcd7e508ce6

Please add the suite to the library?

**Comment by cschol** [comment]
Build failure on macOS platform: https://github.com/fairplay/vcv-rack-plugins/issues/1

**Comment by cschol** [comment]
Also, I recommend adding a `README.md` file explaining what your plugin suite does.

**Comment by fairplay** [comment]
Thanks! I hope it was a clang related issue and I managed to fix it using mingw clang.
Also documentation is added.

hash
1c610105ec8797c910d642c94dffaa2a73d75138

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AndrewBelt** [comment]
I recommend removing "VCV Rack Plugins" from the plugin name, since all Rack plugins are these, so it's redundant.

**Comment by fairplay** [comment]
2.1.0
e9322eef29dd1ade1fdb05272e2a536093d7f4fa

- New look and rehaul of the former modules
- New modules added: Pluck (Karplus-Strong implementation), Droplets (hydrodynamic sequencer), Chaos Maps (pretty standard sequencer based on chaotic maps behavior).

**Comment by cschol** [comment]
Unfortunately, slug changes (for example: MicroLooper to muLooper) are not allowed once a module has been published. It would break existing patches for users.I recommend you change the slug to MicroLooper and change only the module name.

**Comment by fairplay** [comment]
I thought it's more convenient to rename, since the modules' interfaces were changed (number of inputs/outputs, knobs etc), so these modules will be treated as a new ones while previous versions will be obsoleted.
If I was wrong I'll rename the new modules back ofc

**Comment by cschol** [comment]
Oh I see. The old modules are deprecated. I think that's OK then. Just be advised that patches will break obviously. Sometimes people will provide a "mk II" version of their plugin and then deprecate the old version after a while. I'll leave that up to you.

**Comment by fairplay** [comment]
So the old modules will be removed on update from the "plugins/" folder automatically, right? I was under impression that they are remains there till manual removal. If so I will rather go with the proper deprecation.

**Comment by cschol** [comment]
Your new version of the plugin replaces the old version if a user updates.

**Comment by fairplay** [comment]
I've deprecated the old modules (marked them as deprecated in JSON, keeping the old slugs and new slugs, e.g. LFSR8 -> LFSR8Poly simultaneously)
I hope it's the best way to manage the issue.

rev: 9d187365bd0ad8870de8da1f8c08a11cb5f013e9

**Comment by cschol** [comment]
Looks good.

One more issue: https://github.com/fairplay/vcv-rack-plugins/issues/2

**Comment by fairplay** [comment]
Thanks, such a useful guide on migrating. Never ported anything or used non-free version, so was not aware of it.
Here is the fixed head
b560c3f442e99c25e238dfa09e30b025089ed885
