### ISSUE TITLE
RPJVisualizer

### ISSUE THREAD

**Issue by kockie69** [VCVRack/community#753]
Url: https://github.com/kockie69/Visualizer
Version: 2.1.11
hash: a31ec22b345d107650c682fbb6abeac83841f2ce

I have been able to make some changes so the LFM modules now can be build using the VCV toolchain. For Max-x64, Mac-arm and windows this is all possible with the current toolchain.
But......
For Linux I had to add 2 folders, X11 and KHR. I copied them from my linux usr/include folder into the linux SDK dep/include folder. It also worked copying them into the linux sysroot folder of the toolchain

**Comment by cschol** [comment]
The plugin builds successfully with the Rack Plugin Toolchain with those changes. I will push them to the toolchain repository after review is complete. Thanks.

**Comment by cschol** [comment]
Remove plugin binaries from repository: https://github.com/kockie69/Visualizer/issues/47

**Comment by kockie69** [comment]
Version: 2.1.11
New hash: ddeecee10d5ba8bbe356bd7ab6d4e5d7d729b1c6

**Comment by kockie69** [comment]
Anything wrong with this as it still hasn't been picked up?

**Comment by cschol** [comment]
We are aligning on the timing of the official build server's toolchain rebuild to support building this one correctly.

**Comment by cschol** [comment]
Update: there is an issue with building the plugin out of the library source tree. I am looking into why this is a problem. The toolchain is able to build the plugin correctly in a normal checkout, but if the plugin itself is a submodule of a git repo, like it is in the library repo, the build fails during the `make dep` step.

**Comment by cschol** [comment]
Remove git operations from Makefile: https://github.com/kockie69/Visualizer/issues/48

**Comment by kockie69** [comment]
Version: 2.1.12
New hash: 46cf238a2e77a8341a6068822ee9133e1d1b62d1

All Git removed and all tested in the toolchain for all architectures. Fingers crossed.

**Comment by kockie69** [comment]
Version: 2.1.15
New hash: c372f06a37d51b84cad011a50557d9e1502fcfc4
