### ISSUE TITLE
Noise86

### ISSUE THREAD

**Issue by spacejoey86** [VCVRack/community#755]
Repository: https://github.com/spacejoey86/Noise86
Version: 2.0.0
Commit hash: 882d32b1cb87d1a03f14cf610f15adb00421a400

**Comment by cschol** [comment]
Failure to load panel: https://github.com/spacejoey86/Noise86/issues/1

**Comment by spacejoey86** [comment]
Fixed with commit hash 20f5579b3e5123f646295f97a4c3d8419a7ee1a7

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by spacejoey86** [comment]
New plugin version.
Version: 2.1.0
Commit hash: db673232944eea1d08f062990456c7b1697b370c
