### ISSUE TITLE
Is it possible to offer VCV Prototype as part of the library?

### ISSUE THREAD

**Issue by porres** [VCVRack/community#756]
Is it possible to offer VCV Prototype ( https://vcvrack.com/Prototype ) as a download in https://library.vcvrack.com/ for VCV 2.0?

If I remember correctly, I could easily install it via https://vcvrack.com/Prototype but it is not possible anymore. A prior discussion in https://github.com/VCVRack/VCV-Prototype/issues/64 pointed to the fact that this shouldn't be discussed in the VCV prototype repository, see https://github.com/VCVRack/VCV-Prototype/issues/64#issuecomment-1428769707

I would really like to stress that this should be made available once a crowd funding was made to add Pure Data support for this module. Hence, in respect of those who funded it, like me, it'd be nice to not see this go to waste.

thanks

**Comment by AndrewBelt** [comment]
It is possible, but VCV Prototype can't be built with https://github.com/VCVRack/rack-plugin-toolchain which is used to build open-source modules submitted to this repo, so I am closing this. Instead, contact https://vcvrack.com/support for feature requests.

**Comment by porres** [comment]
thanks

**Comment by porres** [comment]
thanks, just asked for it in the support email and I'm waiting now... I can write here for feedback
