### ISSUE TITLE
SIM

### ISSUE THREAD

**Issue by imDanSable** [VCVRack/community#759]
Hi.

This is my first plugin ever.
I hope everything is in order.
If not, please let me know.

code: https://github.com/imDanSable/SIM
version: 2.0.0
~~commit: d94b76db6a4da609f4d34e68e3fdb79ee33cfe95~~ <-- (wrong License ID)
~~commit: c098ad19bfb0dc6e4315fd9748326b6f8bf5419b~~ <-- (font caching)
commit: 7a840a7ace852edb07188b8e2f840e4b9f1643a4

modules:
 Blank
 Coerce
 Coerce6

**Comment by cschol** [comment]
Array access out of bounds: https://github.com/imDanSable/SIM/issues/1

**Comment by imDanSable** [comment]
Fixed in

6b99c32aa530013cf91275c3ca889955db678907

https://github.com/imDanSable/SIM/commit/6b99c32aa530013cf91275c3ca889955db678907

**Comment by imDanSable** [comment]
And from peeking at other 'issues' I removed empty keys in plugin.json.

New hash:

873bd7f5cdec102d01f9dad06e5fc926158f678e

https://github.com/imDanSable/SIM/commit/873bd7f5cdec102d01f9dad06e5fc926158f678e

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by imDanSable** [comment]
A bug fix.

New version: v2.0.1
Hash: 204316955de302f43db3c3eba09708a076b71c21

Thank you.

**Comment by cschol** [comment]
Invalid URL in manifest: https://github.com/imDanSable/SIM/issues/3

**Comment by imDanSable** [comment]
Fixed.
New hash: 979b1241fc20525170fcbfd699358b73ea251590

**Comment by imDanSable** [comment]
Sometimes crashes on exit. Please hold.

~~An update is ready to ship:~~

~~Version: 2.1.0~~
~~Hash: eaf01d2c8efc6350d9f005c2b52ed25ce5ea55a3~~
~~Hash: 47a3c5965314decdf3d5ab721d14d8beedc0920c~~

**Comment by imDanSable** [comment]
Fixed:

Version: 2.1.0
~~Hash: 5e15594f0c17122d6c7db5478b8b1277dfc24bb7~~
~~Hash: 0fab2449be563cbeb538917a38700646d5c21bb7~~ (more better)
Hash: 19eb35d2d103643e0cfcff7c9d7ab8f7c7cb9c79 (more beauty)

Plugin url: https://github.com/imDanSable/SIM

Hope all is well.

**Comment by imDanSable** [comment]
Some bugs fixed:

Version: 2.1.1
Hash: 1186b7401cc9e6f647bf8dcf2c95d5f30e826016

Plugin url: https://github.com/imDanSable/SIM

**Comment by imDanSable** [comment]
Some fixed bugs:

Version: 2.1.2
Hash: 4658ae2c9a7a86fc9190a6a20cae28fc8af41206

Plugin url: https://github.com/imDanSable/SIM
