### ISSUE TITLE
PhoturiElectronics

### ISSUE THREAD

**Issue by BooleanMuse** [VCVRack/community#760]
Hello VCV Rack,
I finish my modules inspired on insects behaivor and would like to be added to the library.

Repo: https://github.com/BooleanMuse/Photuri-Electronics
Version: 2.1.0
Git Hash: 89838021d9f79d57cb7edceafe101e84e52dab59

I will like to know if everything is correct, I will promote the modules on my website.
I wait for your response.

**Comment by cschol** [comment]
Integration issues: https://github.com/BooleanMuse/Photuri-Electronics/issues/1

**Comment by BooleanMuse** [comment]
Fixed the integration issues.

Repo: https://github.com/BooleanMuse/Photuri-Electronics
Version: 2.1.0
Git Hash: 4b939879adfa022eec4cc95bdaba4b09783b86f1

Any other issues notify me.
I wait for your response.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
