### ISSUE TITLE
Yokai_Holiday

### ISSUE THREAD

**Issue by demcanulty** [VCVRack/community#762]
Hello, I have a first module to submit.  

url: https://github.com/demcanulty/Yokai_Holiday/
version: 2.0.0.7
hash:  4d5cf1e118b3ad6672228fca3b2b4853144065d0

I've never contributed to an open source project before, so if I have any glaring omissions or need to read any manuals, please do point me in the right direction.  

I've had people actively testing on this forum thread, and I believe it's ready to release.  
https://community.vcvrack.com/t/reverse-delay-first-module-prototype

There was an initial prototype that I made called Taps_Proto, that I've added the quality of hidden=true to in the plugin.json, so I haven't cleaned up the code for it and it's just there since I know a handful of people installed it and put it into patches while I was testing the initial development.  

I believe this module fills a hole in the delay module options in vcv for a clickless reverse delay and is open source so others can reuse the concepts.  The code is very C looking and not very C++, so it's not pretty, but the CPU usage on my system is on par with other simple delay modules, so I haven't attempted to optimize.  

Please let me know any next steps or fixes I might need to make!  Thanks for looking at this when you find time  :)

**Comment by cschol** [comment]
Binary files in repository: https://github.com/demcanulty/Yokai_Holiday/issues/1

**Comment by demcanulty** [comment]
Thanks cschol,

I moved the old repo, and created a new clean one in the same place.  

url: https://github.com/demcanulty/Yokai_Holiday/
version: 2.0.0.7
hash:96d5433eade1221f9acf0c3b8b8598675dfdbb38

**Comment by cschol** [comment]
Invalid tags and licence in `plugin.json`: https://github.com/demcanulty/Yokai_Holiday/issues/1
Makefile missing from repository: https://github.com/demcanulty/Yokai_Holiday/issues/2

**Comment by demcanulty** [comment]
Thanks cshol, all three issues now addressed

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by demcanulty** [comment]
Yay, thanks!

**Comment by demcanulty** [comment]
Hello, found a potentially uninitialized pointer in my last release that could cause segfault, felt like it merited a quick fix:  

new release:

url: https://github.com/demcanulty/Yokai_Holiday/
version: 2.0.0.8
hash:  0698fa221e4061e2be55f3fe1e76eeb2dd232fd7
