### ISSUE TITLE
dawnbree

### ISSUE THREAD

**Issue by jonesnxt** [VCVRack/community#767]
url: https://github.com/jonesnxt/dawnbree
version: 2.0.0
commit: [b1bbefce8accfeffb8e22d158fc4a3d79084b544](https://github.com/jonesnxt/dawnbree/commit/b1bbefce8accfeffb8e22d158fc4a3d79084b544)

vcv is a fantastic project and im really happy to finally be putting out these modules and contributing in some way :)

**Comment by cschol** [comment]
Compile error on macOS platform: https://github.com/jonesnxt/dawnbree/issues/1

**Comment by jonesnxt** [comment]
> Compile error on macOS platform: [jonesnxt/dawnbree#1](https://github.com/jonesnxt/dawnbree/issues/1)

what a weird error, doesn't even seem like it is ambiguous.
anyways i added an explicit cast and it should hopefully be fixed at afdb178ec7938e22e39f06f4fbdb1e7267870c2c https://github.com/jonesnxt/dawnbree/commit/afdb178ec7938e22e39f06f4fbdb1e7267870c2c

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
