### ISSUE TITLE
monome

### ISSUE THREAD

**Issue by Dewb** [VCVRack/community#768]
URL: https://github.com/Dewb/monome-rack

Version: 2.1.0
Commit: [e3b515fb039e5ed3834a4344a1a759273ab3e0e3](https://github.com/Dewb/monome-rack/commit/e3b515fb039e5ed3834a4344a1a759273ab3e0e3)

This has been a long time coming!

**Comment by cschol** [comment]
Build issue: https://github.com/Dewb/monome-rack/issues/158

**Comment by Dewb** [comment]
Version 2.1.1
Commit: [41bb4b349b16abd6f11e1d439c7ba7ebd698e879](https://github.com/Dewb/monome-rack/commit/41bb4b349b16abd6f11e1d439c7ba7ebd698e879)

**Comment by Dewb** [comment]
Version 2.1.2
Commit: [6f3ee23f8adfd0dc93450f585078189e7c2a5690](https://github.com/Dewb/monome-rack/commit/6f3ee23f8adfd0dc93450f585078189e7c2a5690)

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AndrewBelt** [comment]
I built this, but it has a few bugs that create issues with Rack, so I'd rather not release it before they are fixed.
- Without instantiating any modules from this plugin, Rack prints "Binding to port 13000." to the terminal. Plugins shouldn't initialize things like this without first instantiating a module. Consider lazy initialization when a module requires it, rather than when the plugin is loaded. This looks to be the culprit: https://github.com/Dewb/monome-rack/blob/main/src/plugin.cpp#L51-L57
- The modules grid64, grid128, and grid256 override key commands such as Delete/Backspace to delete and Ctrl-E to bypass. Modules shouldn't override these keys since users should assume that they work with all modules. I don't see a valid reason that these modules should override them.

**Comment by Dewb** [comment]
* Agreed, lazy init was already implemented for that subsystem, looks like I stuck a temporary line of code to force loading in plugin init a while back and forgot to take it out.
* This is indeed a bug, looks like I forgot to call the parent handler when overriding ctrl-click handling, inadvertently breaking all standard shortcuts.

Should be pretty quick to fix these, thanks!

**Comment by Dewb** [comment]
Version: 2.1.3
Commit: [1bb0b6460ad76fd2402cdc34bf4b61864feb95ab](https://github.com/Dewb/monome-rack/commit/1bb0b6460ad76fd2402cdc34bf4b61864feb95ab)

**Comment by AndrewBelt** [comment]
I found another high-priority bug that should be fixed in the plugin's next version.
- When launching the module browser, the terminal says `Binding to port 13000.` Your plugin should NOT initialize when only a `ModuleWidget` is created, but when a `Module` is created.

**Comment by Dewb** [comment]
Version: 2.1.4
Commit: [435b94022a36702e3199512fcde0584bdc47c709](https://github.com/Dewb/monome-rack/commit/435b94022a36702e3199512fcde0584bdc47c709)

Changelog:
* Update to Rack SDK 2.4.0
* Make sure firmware binaries are cleaned from `res/` in between platform builds
* Move serialosc lazy initialization out of `ModuleWidget` into `Module` constructor

**Comment by Dewb** [comment]
Version: 2.1.5
Commit: [2147c80d246de8161c7f945d36ce9beb3bd16083](https://github.com/Dewb/monome-rack/commit/2147c80d246de8161c7f945d36ce9beb3bd16083)

Changelog:
* Support new dark panel preference

**Comment by Dewb** [comment]
Version: 2.2.0
Commit: [b478dbe2b84401c4d384e76a28c89ff6aa38df9c](https://github.com/Dewb/monome-rack/commit/b478dbe2b84401c4d384e76a28c89ff6aa38df9c)

Changelog highlights: alt-firmware support, teletype 5.0beta4 firmware added, grid mirror mode, new module “faderbank”, new preset “MINIM”, bug fix to Unicode path handling, [details](https://github.com/Dewb/monome-rack/releases/tag/v2.2.0)

**Comment by Dewb** [comment]
Version: 2.2.1
Commit: [b5c77664dc5834ee29b2909dd71b2fab640f168c](https://github.com/Dewb/monome-rack/commit/b5c77664dc5834ee29b2909dd71b2fab640f168c)

Changelog: fix user-reported crash

**Comment by Dewb** [comment]
Version: 2.2.2
Commit: [562c323ccacbb757f57aed81da3b06dd5ff90d9c](https://github.com/Dewb/monome-rack/commit/562c323ccacbb757f57aed81da3b06dd5ff90d9c)

Changelog: faderbank voltage range option, polyphonic option, UI tweaks

**Comment by Dewb** [comment]
Version: 2.2.3
Commit: [48d8ebf05ead58b1dab337c13b2935343fea134c](https://github.com/Dewb/monome-rack/commit/48d8ebf05ead58b1dab337c13b2935343fea134c)

Changelog ([details](https://github.com/Dewb/monome-rack/compare/v2.2.2...v2.2.3))
* Teletype international/custom keyboard layout support
* Faderbank bug fixes: fix 1 pixel panel gap, initialize voltage ranges correctly.

**Comment by Dewb** [comment]
Version: 2.2.5
Commit: [4ee3221ace4bea0e8ee2ad92fa4095a41adba244](https://github.com/Dewb/monome-rack/commit/4ee3221ace4bea0e8ee2ad92fa4095a41adba244)

Changelog ([details](https://github.com/Dewb/monome-rack/releases/tag/v2.2.4)):
* Teletype 5.0 is out of beta; update firmware to released version and make 5.0 the default (existing patches remain on 4.0)
* Ansible CV outputs should go all the way to zero

**Comment by Dewb** [comment]
Version: 2.2.6
Commit: [73be53db80a0ba061ac344629bda2aa1129c8c7d](https://github.com/Dewb/monome-rack/commit/73be53db80a0ba061ac344629bda2aa1129c8c7d)

Thanks for the quick turnaround! I unfortunately have a question/issue about the library build process stemming from the 2.2.5 update. 

<details><summary>Details</summary>

The library build of 2.2.5 reports the correct commit hash for Teletype 5.0, but the tag-derived version number is still 4.0.

<img src="https://github.com/VCVRack/library/assets/712405/1782bbae-8f21-47e6-8eeb-6bd224599a64" width="45%">

Some possible hypotheses for what is happening here:
1. The library build process might not be doing a clean before each build, which would be a completely fair thing to do. 2.2.6 should fix this case. But the commit hash was correctly updated, meaning the build step did run, therefore this is probably not sufficient to fix it.
2. The library build process might be intentionally not fetching the full tag history, either by doing a shallow clone or providing `--no-tags`. If this were the case, then the 4.0.0 tag probably would have never worked, so I think this can be ruled out.
3. The library build process might need to run `git submodule sync` before `git submodule update` in case the plugin repo contains submodules and the contents of `.gitmodules` has changed. The contents of `.gitmodules` did change in 2.2.5 to point the teletype5 module url to the upstream repo. And the old url did not contain the v5.0.0 tag, so the output is consistent with this hypothesis. But I see in `update.py` that `git submodule sync` *is* being called; so if that's the version of the script being used, that should rule out this hypothesis also.

I've added the v5.0.0 tag to the old repo so maybe the problem will go away with 2.2.6, but it would be good to get to the bottom of this as I do plan to make more changes to the .gitmodules configuration.

</details>

**Comment by Dewb** [comment]
Aha, ignore all my blather above, I think this is the issue: https://github.com/VCVRack/library/pull/785

**Comment by cschol** [comment]
Build failure with 2.2.6: https://github.com/Dewb/monome-rack/issues/193

**Comment by Dewb** [comment]
Version: 2.2.7
Commit: [16827b0d3fe8c8d291d903dc6d84102718007e9a](https://github.com/Dewb/monome-rack/commit/16827b0d3fe8c8d291d903dc6d84102718007e9a)

**Comment by Dewb** [comment]
Version: 2.2.8
Commit: [a60f6763f47ceea3acd1f4c0746ed9d35b8d8cb2](https://github.com/Dewb/monome-rack/commit/a60f6763f47ceea3acd1f4c0746ed9d35b8d8cb2)
Changelog: https://github.com/Dewb/monome-rack/releases/tag/v2.2.8
