### ISSUE TITLE
TheAllElectricSmartGrid

### ISSUE THREAD

**Issue by jvictor0** [VCVRack/community#771]
Source code: https://github.com/jvictor0/theallelectricsmartgrid
Version: 2.0.0
Git Commit Hash: c53790f562912be16f23c690c82d9b9da9626d64

**Comment by jvictor0** [comment]
manual: https://jvictor0.github.io/theallelectricsmartgrid/lamejuis
video manual: https://www.youtube.com/watch?v=vQx_pSbcf3U&t=1s

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by jvictor0** [comment]
Thank you!

**Comment by jvictor0** [comment]
Hey,

I would like to make an update

Source code: https://github.com/jvictor0/theallelectricsmartgrid
Version: 2.0.1
Git commit Hash: 44916cffeb22ae76edaf87b7b04b2ca57880e8e8

Thank you very much

**Comment by jvictor0** [comment]
Found a bug, bumped the version.

Sorry about that

Source code: https://github.com/jvictor0/theallelectricsmartgrid
Version: 2.0.2
Git commit Hash: b05643e5fc4c65823ccef1b90204fada53e99202

**Comment by jvictor0** [comment]
I just realized I made a bit of an error.  I wrote "SmartGridMusic" as my brand in plugin.json.  I must have written that months ago without thinking about it, it really should say "The All Electric Smart Grid", but I didn't notice til now that my name in the vcv library is SmartGridMusic.  

Would it break things if I changed the brand (like, people ending up with duplicate modules or something)?  If not, let me know and I'll put up a new version with the updated plugin.json.   If its too late to change, I'll just live with it.

**Comment by AndrewBelt** [comment]
Changing the brand name is no issue. Only the plugin/module slug can't be changed after release, otherwise it breaks people's patches.
You could also change the plugin *name* to include spaces like the brand.

**Comment by jvictor0** [comment]
Awesome, thanks!

Source code: https://github.com/jvictor0/theallelectricsmartgrid
Version: 2.0.3
Git commit Hash: 470baeb7b6cc6b6a53c7f97e4c70ba03da68e230

**Comment by jvictor0** [comment]
small update

Source code: https://github.com/jvictor0/theallelectricsmartgrid
Version: 2.0.4
Git commit Hash: 6e98ca0328bf6ae8f7907892b2b899553afe772d

**Comment by jvictor0** [comment]
new update

Source code: https://github.com/jvictor0/theallelectricsmartgrid
version: 2.1.0
hash: debdfae1a3de43a65e77d89df888fa77da61fe8d
