### ISSUE TITLE
CuteFoxModules

### ISSUE THREAD

**Issue by CuteFoxModules** [VCVRack/community#773]
Code: https://github.com/CuteFoxModules/CuteFoxModules

It's my first module, and first time using Github.
I've only been able to test it on Windows.
Let me know if I need to do anything else.

EDIT: Sorry, I wrote the module slug instead of plugin slug in the title, I hope this is correct now.
Thanks!

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by CuteFoxModules** [comment]
Hello,

Updated readme and fixed plugin.json 

Version: 2.0.1
Branch: master
Hash: 8a38d025030a2f2a7bafb1b9fd81a1b4e1e2cee9
Source: https://github.com/CuteFoxModules/CuteFoxModules
