### ISSUE TITLE
SS-Modules

### ISSUE THREAD

**Issue by strongs20** [VCVRack/community#774]
Made my first plugin:
https://github.com/strongs20/SS-modules
Includes a unique melody generator module

**Comment by cschol** [comment]
Invalid entries in manifest file: https://github.com/strongs20/SS-modules/issues/1

**Comment by strongs20** [comment]
> Invalid entries in manifest file: [strongs20/SS-modules#1](https://github.com/strongs20/SS-modules/issues/1)

Just fixed the following issues in newest commit.
Hash: 1894a7497e2742108cd9501a7d0680fe3633c731

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
