### ISSUE TITLE
patina

### ISSUE THREAD

**Issue by epadilla** [VCVRack/community#776]
Hello, submitting my new plugin for release. Thank you!

Slug: patina
Name: Patina
Source: https://github.com/epadilla/patina
Version: v2.0.1
Hash: [a18b720b9cd5ec8a24fd89f2de875b752ec1a28c](https://github.com/epadilla/patina/commit/a18b720b9cd5ec8a24fd89f2de875b752ec1a28c)

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
