### ISSUE TITLE
NLS

### ISSUE THREAD

**Issue by michelezaccagnini** [VCVRack/community#778]
[https://github.com/michelezaccagnini/NLS](https://github.com/michelezaccagnini/NLS)
Version 2.1.6.0
commit hash: 7a5fe348644d68eb9931c25e0212ab330f916c82

**Comment by cschol** [comment]
Plugin manifest issues: https://github.com/michelezaccagnini/NLS/issues/2

**Comment by michelezaccagnini** [comment]
> Plugin manifest issues: [michelezaccagnini/NLS#2](https://github.com/michelezaccagnini/NLS/issues/2)

Fixed it

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
