### ISSUE TITLE
october

### ISSUE THREAD

**Issue by natw** [VCVRack/community#780]
https://github.com/natw/october-modules/
v2.0.0
489a735e592ae192e1b6612a4f8254d9dedf21d2

**Comment by cschol** [comment]
Compile failure on Windows platform when cross-compiling with Rack Plugin Toolchain: https://github.com/natw/october-modules/issues/1

**Comment by AndrewBelt** [comment]
Some suggestions:
- Set "manualUrl" to https://github.com/natw/october-modules/blob/main/README.md which is a more direct manual page.
- Module slugs are specific to the plugin slug, so there's no need for the "october-" prefix.

**Comment by natw** [comment]
v2.0.0
30ffc3c149924afc8428ec193587a334401f9b49


I still haven't gotten the windows cross-compiling working to check for sure, but it sounds like the non-f versions of those functions should exist on windows.

**Comment by natw** [comment]
v2.0.0
e1522478330ce407ce86d00ea401c6db2b44f725

It probably helps to get all of them.

**Comment by cschol** [comment]
Plugin fails to load: https://github.com/natw/october-modules/issues/2

**Comment by natw** [comment]
v2.0.0
8abb7834c3557a807c7a731e3b8b068043df02c6

ok, feeling good about this one XD

**Comment by squinkylabs** [comment]
btw, it's not super difficult to use the official toolchain, especially if you skip the mac step. (You sort of need to physically have a mac for a bit to harvest the SDK for the mac).

**Comment by natw** [comment]
yeah, I had some little issue I can't even remember, but it mostly Just Worked.

**Comment by AndrewBelt** [comment]
Some of the modules have roughly the same panel layout as hardware modules.
NCOM looks like https://serge-modular.com/serge_eurorack?mod=RS_NCOM_E
SSG looks like http://www.loudestwarning.co.uk/portfolio/ssg-dtg-noise/
Random Voltage Generator looks a bit like Buchla 266 Source of Uncertainty
Typically we don't allow clones of component layouts or panel designs without permission from the owner. See https://vcvrack.com/manual/PluginLicensing#VCV-Plugin-Ethics-Guidelines so I'm not sure how to proceed here.

**Comment by cschol** [comment]
@natw I am closing this issue for now. If you are still interested in integration in the library, please respond to Andrew's comment above. Thanks.
