### ISSUE TITLE
HarmonicAnomalies

### ISSUE THREAD

**Issue by lucaskuzma** [VCVRack/community#781]
- https://github.com/thestrangeagency/HarmonicAnomalies
- 2.0.0
- 18e92f2879ed0d2e569c242a1d280370569b1f8f

**Comment by lucaskuzma** [comment]
On a roll. Here is an update. Done for now.
- https://github.com/thestrangeagency/HarmonicAnomalies
- 2.0.1
- 1a040f4e4fd0ec9a4b37dac58a79b27234da985e

**Comment by cschol** [comment]
Manifest issue: https://github.com/thestrangeagency/HarmonicAnomalies/issues/4

**Comment by lucaskuzma** [comment]
fixed both issues raised by @cschol 

- https://github.com/thestrangeagency/HarmonicAnomalies
- 2.0.2
- 9f2eacbb353bd1f3429d06b51166f0ce4b941c53

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
