### ISSUE TITLE
minimal-friction

### ISSUE THREAD

**Issue by ab9st8** [VCVRack/community#782]
A new plugin with only one module for now and others in plans.

https://github.com/ab9st8/minimal-friction

Let me know if something's wrong!

**Comment by ab9st8** [comment]
Just in case it wasn't clear:

* version: 1.0.0
* hash: e7bfdb4307c53c9636f02c2346bf83432df31b5d

**Comment by ab9st8** [comment]
Update for Rack v2:
* version: 2.0.0
* hash: 51eebd1f25def24d581c5f69e1c2a4d654f67048

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by ab9st8** [comment]
Hello! One new module has been added

* version: 2.1.0
* hash: 0dd3ae30ebef03855aaecf217a8405af6f6ae1a5
