### ISSUE TITLE
MUS-X

### ISSUE THREAD

**Issue by Jojosito** [VCVRack/community#783]
- [https://github.com/Jojosito/MUS-X](https://github.com/Jojosito/MUS-X)
- 2.0.0
- 6d79b7279f6f1b78aaf52351b999ac46ea97db39

**Comment by cschol** [comment]
Invalid URL in plugin manifest: https://github.com/Jojosito/MUS-X/issues/5

**Comment by Jojosito** [comment]
Thanks! I fixed the plugin manifest.

- https://github.com/Jojosito/MUS-X
- 2.0.0
- 081971e6b22dde600584f7ed772d423a974b6139

**Comment by cschol** [comment]
URL is still invalid. Updated original issue in source repository.

**Comment by Jojosito** [comment]
Sorry. It validates now

- https://github.com/Jojosito/MUS-X
- 2.0.0
- 74967f786f8de85f3684091c650ac2b3e9276b40

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by Jojosito** [comment]
- https://github.com/Jojosito/MUS-X
- 2.0.1
- 83c5b665f82247eaa520e849694c2dfbe774a457

**Comment by Jojosito** [comment]
https://github.com/Jojosito/MUS-X
2.0.2
e884f67ac5f6ff1a392bc99e81ea044e7544115b

**Comment by cschol** [comment]
Compile failure on macOS platform: https://github.com/Jojosito/MUS-X/issues/11

**Comment by Jojosito** [comment]
I replaced 'constexpr' with 'const'. I don't have a Mac, but I think it should work now. Thanks!

https://github.com/Jojosito/MUS-X
2.0.2
1b9eff950f4ce7de63b137d521690ec655f2110e

**Comment by Jojosito** [comment]
https://github.com/Jojosito/MUS-X
2.1.0
84398e97ac9bbf3786abeff64b33c980af00c8b7

**Comment by Jojosito** [comment]
https://github.com/Jojosito/MUS-X
2.1.1
f622217ec6b709b7707fb76f85026e0faa93b893
