### ISSUE TITLE
sn

### ISSUE THREAD

**Issue by transcriptaze** [VCVRack/community#784]
Hi,

I'd like to submit a plugin to the library:

- URL: https://github.com/transcriptaze/sn-vcv
- version: v2.0.0
- commit: 94c996eaa9bc6854ccb6803610bc30d5a3becffc

**Comment by cschol** [comment]
@transcriptaze please remove any reference to `VCV` from the plugin. `VCV` is a brand name and should not be used in any open source plugins.

**Comment by transcriptaze** [comment]
**Think** I got all the VCV references:

- URL: https://github.com/transcriptaze/sn-vcv
- version: v2.0.0
- commit: 09ab5da0692a4c4000ac2a5a3ae7090c590dba34

**Comment by cschol** [comment]
Invalid URLs in manifest: https://github.com/transcriptaze/sn-vcv/issues/1

**Comment by transcriptaze** [comment]
**Really** thought I had checked those - should be correct now.

- URL: https://github.com/transcriptaze/sn-vcv
- version: v2.0.0
- commit: 4acab42eafc196758a4ff628e22fd29508dc4652

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by transcriptaze** [comment]
Thanks so much!
