### ISSUE TITLE
STS-Multiplier

### ISSUE THREAD

**Issue by mlaban64** [VCVRack/community#786]
Source is at https://github.com/mlaban64/STS-Multiplier

This is the first publish, hence version 2.0.0.
I hope this is sufficient

**Comment by cschol** [comment]
Is there any reason why all of your modules are separate plugins? I would recommend you create ONE plugin, perhaps call is "STS" and include all of your modules into this plugin.

**Comment by mlaban64** [comment]
Fair point...will have a look at that...feel free to close the other STS modules until I've sorted that one out...

**Comment by cschol** [comment]
Sounds good. I think it will be much easier for users to have one plugin with multiple modules in it. Let me know if you have any questions.
