### ISSUE TITLE
astrokkidd

### ISSUE THREAD

**Issue by astrokkidd** [VCVRack/community#787]
https://github.com/astrokkidd/astrokkiddVCV

**Comment by astrokkidd** [comment]
If I'm missing something or did something incorrectly, please let me know. I'm brand new to this.

**Comment by cschol** [comment]
Plugin is going through initial review and will be integrated soon.

**Comment by cschol** [comment]
Failed to load panel SVG: https://github.com/astrokkidd/astrokkiddVCV/issues/1

**Comment by astrokkidd** [comment]
Should be fixed
Hash: 8249810b0050b0a7ed6fbc0ecf538be7b4d68af5

**Comment by AndrewBelt** [comment]
Why do users need this plugin in the VCV Library? It's an exact clone of the tutorial module in https://vcvrack.com/manual/PluginDevelopmentTutorial

**Comment by astrokkidd** [comment]
It's for a school project. I wanted to be able to set up my plug-in on the library, then add more modules as I learned to develop them so that they'll be easy to distribute. You can close the issue, though, since I realized it's a bad idea. I'll wait until I have an original module to request to add it. Or I'll learn how to use the toolchain. Sorry for the waste of time.

**Comment by AndrewBelt** [comment]
Okay I'll close this for now, but if you add new modules, let us know in this issue and we'll re-open, review, and release on the VCV Library!
