### ISSUE TITLE
SmarTAZZStudio-Free

### ISSUE THREAD

**Issue by mlaban64** [VCVRack/community#792]
https://github.com/mlaban64/STS-Free

**Comment by mlaban64** [comment]
@AndrewBelt : Someone pointed out that there has been another plugin called STS in the past, and to avoid confusion, he recommended changing it into e.g. STS-Free.

The old STS plugin appears to be for Rack v1 and is here: https://library.vcvrack.com/STS

As I have nothing to do with this old plugin, I wonder if there is a point in changing the Slug...I have no issue keeping it, but I am not sure if that can cause any confusion or issues...

Let me know if you prefer a change or if I can stick to STS as a slug...

**Comment by AndrewBelt** [comment]
Thanks for mentioning this. It'd be a good idea to change the slug to avoid confusion with the old STS.
I'd recommend not using an acronym and changing the slug to `SmarTAZZStudio` or something.

**Comment by cschol** [comment]
Also, IF you are planning to differentiate between Free and Paid modules, I recommend adding the `-Free` suffix to the slug for this plugin: `SmarTAZZStudio-Free`.

**Comment by mlaban64** [comment]
@AndrewBelt , @cschol: Done...slug now changed to SmarTAZZStudio-Free

commit# = 87ef2eb65e0837a4811a44c10cc36d94bb329f4f

**Comment by mlaban64** [comment]
Just to make sure: Latest commit# =  217ac71aec615a7cea525414d19ffd0f18a2b2d1

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by mlaban64** [comment]
Hi all,

A new version (2.1.0) available here: https://github.com/mlaban64/STS-Free
commit branch = 8233b6f9830935c37f8d296087fce55ab463faed

**Comment by mlaban64** [comment]
Hi all,

Had to correct the manifest...

A new version (2.1.0) available here: https://github.com/mlaban64/STS-Free
commit branch = e9070a4796fd43ec24c7331dbd5e70e8e5a4f49b 

@cschol: Do you need anything else, or is this sufficient to update the plugins?

**Comment by mlaban64** [comment]
Hi all,

A new version (2.2.0) available here: https://github.com/mlaban64/STS-Free
commit branch = c0a3e3f2d950b1a235d5aad254777f4ab578c660

@cschol: Do you need anything else, or is this sufficient to update the plugins?

**Comment by mlaban64** [comment]
Hi all,

A new version is available of my plugin here: https://github.com/mlaban64/STS-Free

commit branch = efe3d2dec323bab69c2e04696ba048bf8e9e2f12 

@cschol : Let me know if you need anything else.
Thanks!

**Comment by mlaban64** [comment]
A new version (2.4.0) is available of my plugin here: https://github.com/mlaban64/STS-Free

commit branch = 6e7822ce4a8b41d3a778e2e402e57f826dc37b94

@cschol : Let me know if you need anything else.
Thanks!

**Comment by mlaban64** [comment]
A new version (2.4.1) is available of my plugin here: https://github.com/mlaban64/STS-Free

commit branch = 55aa54239a503ed8270de34a822906ec53e666fb

@cschol : Let me know if you need anything else.

Thanks!
