### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by herbert-50** [VCVRack/community#794]
https://github.com/herbert-50/SSE-One/tree/main

**Comment by cschol** [comment]
Invalid manifest content: https://github.com/herbert-50/SSE-One/issues/1

**Comment by herbert-50** [comment]
Ok, I corrected it. Please try the validation again.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by herbert-50** [comment]
Thank you very much for your work!

**Comment by herbert-50** [comment]
A new version was released on github.

Version 2.0.1
commit hash: 60e691ae42636e7afaefccdf339596771bf30380

**Comment by herbert-50** [comment]
A new version with some bug fixes was released.

Version 2.0.2
commit hash: ff3505b67b2b07e7787c40a89d06b9c42a2ddd65
