### ISSUE TITLE
MML

### ISSUE THREAD

**Issue by CHLOzzz** [VCVRack/community#796]
https://github.com/CHLOzzz/MML

**Comment by AndrewBelt** [comment]
For the "authorEmail" property, I suggest using a comma with no spaces, so clicking on it on the VCV Library page will open your email client with both addresses in the To field. e.g. `cmccarth@mtu.edu,robertsc@mtu.edu`

**Comment by CHLOzzz** [comment]
Thank you for the recommendation, I have implemented the change.

Do I need to iterate the version as well from `2.0.0` to `2.0.1`?

**Comment by AndrewBelt** [comment]
No, not until we release a build. We'll do a full review shortly.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by CHLOzzz** [comment]
Hi VCV team, version 2.1.0 of my plugin should be ready to be updated in the Library.
