### ISSUE TITLE
eightfold

### ISSUE THREAD

**Issue by scanner-darkly** [VCVRack/community#798]
https://github.com/scanner-darkly/eightfold
v2.0.0
066b89bf1ae895d4a6c4410801deb4705c2498fa

this is a new plugin with 3 modules. thanks!

**Comment by AndrewBelt** [comment]
Have you considered adding these modules to your existing plugin? https://github.com/scanner-darkly/vcv-collection-one

**Comment by scanner-darkly** [comment]
i have - vcv-collection-one was my original plugin and i used a rather generic name, while eightfold reflects the theme for the new collection (modules that generate 8 voices or can process 8 signals at once). i'm not planning to maintain vcv-collection-one any further, it will be superseded by this plugin.

**Comment by scanner-darkly** [comment]
v2.0.1
[b8c3b1abb76f6602dfbf49d57232115b01250df0](https://github.com/scanner-darkly/eightfold/commit/b8c3b1abb76f6602dfbf49d57232115b01250df0)

thanks!
