### ISSUE TITLE
[discussion] Downloads by Architecture

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#8]
Making everybody store and download versions for systems they don't use is going to be a waste of space and bandwidth for everybody, and requires that developers run a script or something to merge their zips. It's more sensible to split downloads into distinct architectures. I hope this ship hasn't sailed.

**Comment by AndrewBelt** [comment]
This is such a trivial issue. But, here are the tradeoffs.

Merged zips:
- easier for developers to organize for musicians, no need to juggle three ZIP files
- less time for developers to update their manifests
- ensures that all resources are the same between architectures

Split zips:
- Saves 2*plugin size, uncompressed, which is typically ~100kb each.
- No need to run `zipmerge.sh AudibleInstruments-0.5.0-*.zip AudibleInstruments-0.5.0.zip`

I'm extremely busy on more important priorities of Rack, so I'll come back to this in a month or two.

**Comment by jeremywen** [comment]
So I found that 16 of 37 have zips files that need to be merged.  Those devs could just edit their latest release and replace the zips with one merged zip.  
 https://docs.google.com/spreadsheets/d/19EuENTzFQTlhYqIuCwJ_aZbEJ3RTIv3ZzqghNLK6p04/edit#gid=0

**Comment by AndrewBelt** [comment]
Actually, thought of a use case for this. Two parties could be in charge of individual architectures. Of course it increases manifest complexity x3.

```json
{
	...
	"arch": {
		"win": {
			"download": "...",
			"sha256": "..."
		},
		"mac": {
			"download": "...",
			"sha256": "..."
		},
		"lin": {
			"download": "...",
			"sha256": "..."
		},
	}
}```

**Comment by jeremywen** [comment]
Ya I was wondering the same thing.  This will help with the crowd sourced builds that I was talking about originally 😄 This will also help with the initial updates to get this thing going.  Then devs can decide which way works best for them.

**Comment by AndrewBelt** [comment]
Feel free to switch the manifest files and README to my above schema. Otherwise I'll do it in 3-4 days.

**Comment by jeremywen** [comment]
Ok got it.  This is better.

**Comment by jeremywen** [comment]
And by got it, I mean I will do this.

**Comment by jeremywen** [comment]
look good? https://github.com/VCVRack/community I will keep updating manifests...

**Comment by AndrewBelt** [comment]
Looks great!

**Comment by AndrewBelt** [comment]
Renamed "arch" to "download" because it makes a bit more sense.

**Comment by jeremywen** [comment]
ok cool, will rename the ones I have fixed...

**Comment by jeremywen** [comment]
um lol I guess I will split this into two manifests https://github.com/adbrant/ArableInstruments/releases

**Comment by AndrewBelt** [comment]
Looks like it. Would definitely be two separate plugins.

**Comment by jeremywen** [comment]
Instead of `downloads` with a `download` property, shouldn't we have downloads with a `url` property?

**Comment by AndrewBelt** [comment]
Then we'd want the other keys to be "manualUrl" etc.

**Comment by jeremywen** [comment]
haha ok nevermind

**Comment by AndrewBelt** [comment]
I mean we could. They seem fine to me as is, but any other organization is fine as long as it makes sense and is eventually stable.

**Comment by jeremywen** [comment]
I agree.  I will continue updating manifests...
