### ISSUE TITLE
WavsynModular

### ISSUE THREAD

**Issue by mogrifier** [VCVRack/community#802]
https://github.com/mogrifier/WavsynModular
Version 2.0.0
commit 38d1bd7332d26d72abb6743e946fec734b474333

**Comment by mogrifier** [comment]
BTW, I know this has moved to a new stage, but I have done quite a bit more work including adding a new module. I didn't update the version since this hasn't been published yet, but here is the new commit hash:

 d7ee24c1e7390dd8d4e9a1bf75456f408eca8955

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by mogrifier** [comment]
I have added a new module, TRIP. Thanks for your review and hard work!

https://github.com/mogrifier/WavsynModular

version: 2.1.0
branch: main
Commit 10549f3bc411df6f1ebb5d7bd6e7be3c3e136714

**Comment by mogrifier** [comment]
I have added a new module, SMITTY. Thanks again!

https://github.com/mogrifier/WavsynModular

version: 2.2.0
branch: main
Commit 9e625570cadaa65074495b8959c73ec47ddb4ec8
