### ISSUE TITLE
FrequencyDomain

### ISSUE THREAD

**Issue by almostEric** [VCVRack/community#803]
latestVersion : 2.0.1
commit hash: 4d4cec4511d72fcdf1799a237044aaa2fc2d715e
branch: Master

**Comment by AndrewBelt** [comment]
What repo URL?

**Comment by almostEric** [comment]
Sorry about that.

https://github.com/almostEric/Frequency-Domain.git

 

Eric Sterling | CTO DigitalPour | 503.724.6536

 <https://zoho.email-view.com/click.zt?linkDgs=312b686309b19&mailDgs=312b686309b16> www.digitalpour.com   | <https://zoho.email-view.com/click.zt?linkDgs=312b686309b1a&mailDgs=312b686309b16> @DigitalPour  |  <https://zoho.email-view.com/click.zt?linkDgs=312b686309b18&mailDgs=312b686309b16> Facebook

**Comment by fractalgee** [comment]
@cschol

**Comment by cschol** [comment]
Compile failure: https://github.com/almostEric/Frequency-Domain/issues/1

**Comment by almostEric** [comment]
latestVersion: 2.0.1
commitHash: 3a1abb8dd7c44344ba66bc1609f6dcf62ddcba3e
branch: master

**Comment by almostEric** [comment]
Not sure how I am supposed to fix this compile error? I am building against 2.5.2 successfully, and the "missing" dlls are part of vcv?

**Comment by almostEric** [comment]
latestVersion: 2.0.1
commitHash: 89db78a27d364d88f76953ab41e80d9eef53a5b6
branch: master

**Comment by almostEric** [comment]
turns out those includes were not being used, so...

**Comment by cschol** [comment]
Updated issue above with patch that fixes build.

Also: https://github.com/almostEric/Frequency-Domain/issues/2

**Comment by almostEric** [comment]
latestVersion: 2.0.1
commitHash: 37c320fb898afc835b6e25ca68c796cc3ad6c92d
branch: master

I fixed that other file and used bfg repo-cleaner. it says it removed the plugin.dll but I'm still seeing it.
Let me know this commit works

**Comment by cschol** [comment]
Thanks. Build completes successfully. `plugin.dll` file is still present in the repo in this revision. Not sure what happened with BFG Cleaner.

**Comment by almostEric** [comment]
So is plugin.dll being present (even though removed from repo) preventing frequency domain being updated in library?Why does vcv suck so bad at communicating these days 😕Sent from my iPhoneOn 30 Jun 2024, at 16:15, cschol ***@***.***> wrote:﻿
Thanks. Build completes successfully. plugin.dll file is still present in the repo in this revision. Not sure what happened with BFG Cleaner.

**Comment by cschol** [comment]
SHA `37c320fb898afc835b6e25ca68c796cc3ad6c92d` doesn't exist in the repo.

`plugin.dll` is still present:

![image](https://github.com/user-attachments/assets/1b3e718a-e37f-4849-be35-620c4e3511a7)

Watch your communication style.

**Comment by almostEric** [comment]
latestVersion: 2.0.2
commitHash: 97e518c56d095f5c9be04f71b1431687044f2da8
branch: master

**Comment by almostEric** [comment]
latestVersion: 2.0.3
commitHash: 739fb4b0b824be482c3b75b81c49645bed621367
branch: master

**Comment by AndrewBelt** [comment]
Compile error
```
In file included from src/controller/BoxOfRevelation.cpp:1:
In file included from src/controller/BoxOfRevelation.hpp:10:
src/controller/../model/dsp/filter/CombFilter.hpp:9:10: fatal error: 'simd/vector.hpp' file not found
#include <simd/vector.hpp>
         ^~~~~~~~~~~~~~~~~
```
The cause is incorrect filename case, but it's not recommended to include individual files from the Rack SDK. Include `rack.hpp` instead.

**Comment by almostEric** [comment]
latestVersion: 2.0.3
commitHash: 8d4a4556569ddeda2bab251e092cb72acd314195
branch: master

**Comment by almostEric** [comment]
Is the build system more brittle now? These are not new modules - all of this code compiled on my machine, and all of these modules are already in the library with code that used to work, but now breaks.

Anyway, should be good now
