### ISSUE TITLE
Hutara 

### ISSUE THREAD

**Issue by hutara** [VCVRack/community#804]
hi
https://github.com/hutara/Hutara-modules
commit/18da52ce02432bcc996358eec089f6e2ddc1f7ad
Thanks

**Comment by cschol** [comment]
Integration issues: https://github.com/hutara/Hutara-modules/issues/1

**Comment by hutara** [comment]
hi, I did what you said and I hope the problem is solved. Thank you for your time

https://github.com/hutara/Hutara-modules
commit: edc711668d2a93aadf7682e5e122b56f6b1adf87

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
