### ISSUE TITLE
NullSet

### ISSUE THREAD

**Issue by nicholas-j-denning** [VCVRack/community#805]
I'd like to release my plugin to the library.
https://github.com/nicholas-j-denning/NullSet

version: 2.0.0
branch: main
commit: 3637d33896d66c4aa0abb0e0e7e3e42f1fd3acb9

**Comment by nicholas-j-denning** [comment]
Hi, it's been a month since I submitted this, and I haven't heard anything.

I noticed my issue never received the 'plugin' label and that other plugins submitted after mine have already been added to the library. If you just need more time, that's no problem, but I'm new to this, so I just wanted to check that I did everything correctly.

**Comment by AndrewBelt** [comment]
My apologies! I must have missed this last month and it must have gotten buried. I've added the Plugin tag so it will be reviewed soon.
