### ISSUE TITLE
gwrthiant

### ISSUE THREAD

**Issue by dustractor** [VCVRack/community#806]
https://github.com/dustractor/gwrthiant.git

Initial version: 2.0.2

commit hash: de121510ee03acf54484a1ac746791ee0f887ed3

branch: main

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.
