### ISSUE TITLE
4msCompany

### ISSUE THREAD

**Issue by danngreen** [VCVRack/community#808]
https://github.com/4ms/4ms-vcv

Version: 2.0.0
Commit: d93570433fdf57716d2a5410c9e30421486c66a0

**Comment by AndrewBelt** [comment]
Just a few manifest suggestions before @cschol's full review:
- Change brand from `4msCompany` to `4ms` so your modules will appear as "4ms Ensemble Oscillator" etc which looks cleaner.
- Add "manualUrl" to all modules that can go to e.g. https://4mscompany.com/enosc or https://4mscompany.com/media/ENOSC/manual/Ensemble-Osc-manual.pdf

**Comment by danngreen** [comment]
Thanks, good points. Done.

Commit: eb272818467aa5869d287f306e4f0068815adea0

**Comment by danngreen** [comment]
Last-minute bug fix (macOS 10.13 compatibility, certain modules crashed on Windows)

Version: 2.0.1
Commit: ab45d2f4db36c8a49ae2ff388d3f37dc74438f4d

**Comment by danngreen** [comment]
Another bug fix!

Version: 2.0.2
Commit: 958ef2f223c746f1dbc48a3f6f7dd0cc1bde508f

**Comment by danngreen** [comment]
Latest version: 2.0.5
Commit: e7d76718332f766e5a17534e8a2099ac0a1e1cc2

I don't want to complicate the process, let me know if I should stop posting updates here. My thought is that we might as well have the latest version when it's our turn in the queue.

**Comment by AndrewBelt** [comment]
Apologies for the delay. I haven't been able to get our build system for C++20 working yet. I'll have to look into this after I get back from Knobcon on Sept 10.

**Comment by danngreen** [comment]
Ok, no problem. Enjoy Knobcon!

**Comment by danngreen** [comment]
Latest version: 2.0.6
Commit: 622727635df6f111399635e43caeaf261716e771

**Comment by AndrewBelt** [comment]
I can't get my osxcross cross-build system to build code that uses C++20 concepts. We're going to have to treat this plugin like freeware, where you submit build packages to support@vcvrack.com. Send an email and I'll send you the instructions for submitting binaries to the VCV Library.
