### ISSUE TITLE
Confused about slugs

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/community#81]
I am confused about slugs

in my Autodafe.cpp

```
void init(rack::Plugin *p) {
    plugin = p;
    plugin->slug = "Autodafe - Drum Kit";

    #ifdef VERSION
    p->version = TOSTRING(VERSION);
    #endif
```

should my manifest file reflect the SAME EXACT Slug? Without spaces?
In my Manifest I have something like "AutodafeDrumKit" at the moment...

**Comment by AndrewBelt** [comment]
"Autodafe - Drum Kit" should be your slug forever and should match the manifest.

**Comment by antoniograzioli** [comment]
ok, but:

> slug*: Unique identifier for your plugin. Should never change. Avoid spaces. Prefix with your company or developer name if you plan to release multiple plugins, e.g. "VCV-PulseMatrix". But most importantly, should never change.

So, no problems if I use spaces in the slug?

**Comment by AndrewBelt** [comment]
Ideally, but most importantly it should not change.

**Comment by antoniograzioli** [comment]
ok, so I have better change the slug in my plugins and not in the manifest

**Comment by AndrewBelt** [comment]
No, the C++ slug is the one you should use. Change the manifest slug to match the C++.

**Comment by antoniograzioli** [comment]
if I use slug "Autodafe - Drum Kit" , "make dist" doesn't work...it creates  different folder one for the "-", one for "Drum" and one for "Kit"..."Autodafe" folder is skipped...

I think I had better move to a "spaceless" slug...

**Comment by antoniograzioli** [comment]
I can confirm that spaces in the slug are not a good idea at all...

1) i had to put SLUG ="my plugin with spaces in its name" in double quotes in order to "make dist" work, but then:
2) when Rack downloads 'my plugin with spaces in its name.zip' it probably gets a 404 error and downloads only 229 KB (the 404 page, probably), zipped and the unzip process fails.

**Comment by AndrewBelt** [comment]
Looks like you chose on changing the slugs. Probably better for the long run.

**Comment by antoniograzioli** [comment]
yes, actually if a ZIP file contains spaces in it Rack is not able to download it. Hence the change
