### ISSUE TITLE
WavsynModular

### ISSUE THREAD

**Issue by mogrifier** [VCVRack/community#811]
I have added a new module, TRIP. Thanks for your review and hard work.

https://github.com/mogrifier/WavsynModular

version: 2.1.0
branch: main
commit b4fa1da440db5aea1f5fba975bd74161517a7bbb

**Comment by mogrifier** [comment]
I noticed some inconsistent tooltips so made an update. This is the new commit.

commit 10549f3bc411df6f1ebb5d7bd6e7be3c3e136714

**Comment by cschol** [comment]
Please reuse the existing issue to submit new versions: #802 . We will reopen it.
