### ISSUE TITLE
Wygonium

### ISSUE THREAD

**Issue by gwygonik** [VCVRack/community#812]
https://github.com/gwygonik/WygoniumModules
2.0.0
34782aee2717c5e5a1c481c022b01f35f142b87a

**Comment by cschol** [comment]
Integration issues: https://github.com/gwygonik/WygoniumModules/issues/1

**Comment by gwygonik** [comment]
Thanks! Apologies for problems, my bad when moving things to github. Cleaning up.

**Comment by gwygonik** [comment]
Let's try this.

https://github.com/gwygonik/ORBsqVi
2.0.0
ed84f0151b5c8baf513d02d7d966f20d9bb8a34c

**Comment by gwygonik** [comment]
Updated for Windows Compilation

https://github.com/gwygonik/ORBsqVi
2.0.1
bdcc68aeb31ad7507a5ed9622d1840166a959940

**Comment by cschol** [comment]
Missing Makefile: https://github.com/gwygonik/ORBsqVi/issues/2

**Comment by gwygonik** [comment]
Added makefile

https://github.com/gwygonik/ORBsqVi
2.0.1 (still)
049c8b715b6d90b57f3b22e8d8f658785e6ad096

**Comment by gwygonik** [comment]
I noticed that the primary plugin uses the same methods that needed math::rack namespace for the Windows compilation issue with the display widget, but these weren't listed in the reported issue so they weren't changed. I'm hesitant to change any code at this point as a) it does still compile, and b) you're in-progress of the review and integration. If you encounter compilation issues and this needs updating, I'm happy to push an update. Sorry for any noise/annoyance/frustration.

**Comment by cschol** [comment]
Cross-compilation for Windows with our toolchain did not result in any build issues, so it should be fine. Sometimes the msys/mingw environment might have a newer compiler that doesn't accept the code and results in compile failures.

**Comment by gwygonik** [comment]
https://github.com/gwygonik/ORBsqVi
2.0.2
6c714231ef52dbaf0bf3fb7f5fe0ebcb539de59e

**Comment by gwygonik** [comment]
https://github.com/gwygonik/ORBsqVi
2.0.4
c5eddc18ffd2d34a1c315a807ce715269f585bc1

**Comment by gwygonik** [comment]
I'm terribly sorry. Still working out a robust testing strategy, and missed a case earlier.

https://github.com/gwygonik/ORBsqVi
2.0.4
d9cf8d7f46dfb75e021b2b6b5daf9b86a923dff1
