### ISSUE TITLE
DigitalAtavism

### ISSUE THREAD

**Issue by lazerfalcon** [VCVRack/community#814]
URL: https://github.com/lazerfalcon/DigitalAtavism/
Let me know if anything else is required to get these modules integrated.

Cheers,
Shawn

**Comment by lazerfalcon** [comment]
Is anything else required to advance integration?

version: v2.0.0
hash: 8db69f7b0b60b9b65f79d166325839438ea01f81

**Comment by cschol** [comment]
Invalid tag in manifest file: https://github.com/lazerfalcon/DigitalAtavism/issues/1

**Comment by lazerfalcon** [comment]
Updated. Please try with the following hash:
553fa27b91cd3db22b11ab7b37dd17f96ee6e855
