### ISSUE TITLE
BlackNoiseModular

### ISSUE THREAD

**Issue by hemmer** [VCVRack/community#815]
First release of Black Noise Modular for VCV. cc @BlackNoiseModular 

repo url: https://github.com/BlackNoiseModular/VCV
version: v2.0.0
hash: 308621dd8ff02fe45819d36026075e7af05c0385

**Comment by AndrewBelt** [comment]
On Linux the panel doesn't load. The filename case is incorrect.
```
[2.881 warn src/window/Svg.cpp:112 load] Failed to load SVG /home/vortico/.local/share/Rack2/plugins-lin-x64/BlackNoiseModular/res/panels/GomaII.svg
```

**Comment by hemmer** [comment]
Ah damn that's annoying, I've pushed a quick fix update here. I see it's closed as completed though, so is it integrated already? Fine either way, new details below:

repo url: https://github.com/BlackNoiseModular/VCV
version: v2.0.1
hash: 8050ef57cec485f3f0a7c11c3d8fb16fca4577e3

**Comment by hemmer** [comment]
Hi @AndrewBelt - unfortunately we had scheduled to launch a video with Omri for tonight (which he can't move any later), is there any chance this could be integrated today? I fixed within the hour once you flagged the issue. Or if not is there a rough timescale, e.g. few days, few weeks? No worries if not possible - it does make it difficult to coordinate professional launches on VCV without this sort of information unfortunately though.

**Comment by hemmer** [comment]
Minor update, just to add missing tags to `plugin.json`

repo url: https://github.com/BlackNoiseModular/VCV
version: v2.0.2
hash: 040f1da0f6f33f014e607fe470630e273862a22b

**Comment by cschol** [comment]
Version number needs update: https://github.com/BlackNoiseModular/VCV/issues/6

**Comment by hemmer** [comment]
Ah sorry

repo url: https://github.com/BlackNoiseModular/VCV
version: v2.0.2
hash: c3db83a58e98afbf37eee8b3235f8a69c69e4e8a
